{
  "openapi": "3.1.0",
  "info": {
    "title": "",
    "version": "1.0.0"
  },
  "paths": {
    "/dataplan/quota-rules/v1": {
      "get": {
        "description": "Returns the current quota allocation rules.\n\nRequires the following permissions:\n- `team-quota-rules:Read`",
        "operationId": "QuotaAllocationRuleSetService_GetQuotaAllocationRuleSet",
        "parameters": [
          {
            "description": "Unique identifier.",
            "in": "query",
            "name": "id",
            "required": false,
            "schema": {
              "description": "Unique identifier.",
              "minLength": 0,
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetQuotaAllocationRuleSetResponse"
                }
              }
            },
            "description": ""
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Bad Request"
          },
          "401": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Unauthorized request"
          },
          "404": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Rule set not found"
          },
          "500": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Internal server error"
          }
        },
        "summary": "Get quota allocation rule set",
        "tags": [
          "Quota Allocation Rule Set service"
        ],
        "x-coralogixPermissions": [
          "team-quota-rules:Read"
        ]
      },
      "put": {
        "description": "Updates the quota allocation rules.\n\nRequires the following permissions:\n- `team-quota-rules:Manage`",
        "operationId": "QuotaAllocationRuleSetService_ReplaceQuotaAllocationRuleSet",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "description": "Request to replace quota allocation rule set",
                "properties": {
                  "ruleSet": {
                    "$ref": "#/components/schemas/QuotaAllocationEntityTypeRuleSet"
                  }
                },
                "required": [
                  "ruleSet"
                ],
                "title": "Replace quota allocation rule set request",
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ReplaceQuotaAllocationRuleSetResponse"
                }
              }
            },
            "description": ""
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Bad Request"
          },
          "401": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Unauthorized request"
          },
          "404": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Rule set not found"
          },
          "500": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Internal server error"
          }
        },
        "summary": "Replace quota allocation rule set",
        "tags": [
          "Quota Allocation Rule Set service"
        ],
        "x-coralogixPermissions": [
          "team-quota-rules:Manage"
        ]
      },
      "post": {
        "description": "Creates new quota allocation rules.\n\nRequires the following permissions:\n- `team-quota-rules:Manage`",
        "operationId": "QuotaAllocationRuleSetService_CreateQuotaAllocationRuleSet",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "description": "Request to create a new quota allocation rule set",
                "properties": {
                  "ruleSet": {
                    "$ref": "#/components/schemas/QuotaAllocationEntityTypeRuleSet"
                  }
                },
                "required": [
                  "ruleSet"
                ],
                "title": "Create quota allocation rule set request",
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CreateQuotaAllocationRuleSetResponse"
                }
              }
            },
            "description": ""
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Bad Request"
          },
          "401": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Unauthorized request"
          },
          "409": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Rule set already exists"
          },
          "500": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Internal server error"
          }
        },
        "summary": "Create quota allocation rule set",
        "tags": [
          "Quota Allocation Rule Set service"
        ],
        "x-coralogixPermissions": [
          "team-quota-rules:Manage"
        ]
      },
      "delete": {
        "description": "Deletes the quota allocation rules.\n\nRequires the following permissions:\n- `team-quota-rules:Manage`",
        "operationId": "QuotaAllocationRuleSetService_DeleteQuotaAllocationRuleSet",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeleteQuotaAllocationRuleSetResponse"
                }
              }
            },
            "description": ""
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Bad Request"
          },
          "401": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Unauthorized request"
          },
          "404": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Rule set not found"
          },
          "500": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Internal server error"
          }
        },
        "summary": "Delete quota allocation rule set",
        "tags": [
          "Quota Allocation Rule Set service"
        ],
        "x-coralogixPermissions": [
          "team-quota-rules:Manage"
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "CreateQuotaAllocationRuleSetResponse": {
        "title": "Create quota allocation rule set response",
        "type": "object",
        "properties": {
          "ruleSet": {
            "$ref": "#/components/schemas/QuotaAllocationEntityTypeRuleSet"
          }
        },
        "description": "Response confirming quota allocation rule set has been successfully created",
        "externalDocs": {
          "url": ""
        }
      },
      "DeleteQuotaAllocationRuleSetResponse": {
        "title": "Delete quota allocation rule set response",
        "type": "object",
        "properties": {
          "id": {
            "minLength": 0,
            "type": "string",
            "description": "Unique identifier."
          }
        },
        "description": "Response confirming quota allocation rule set has been successfully deleted",
        "externalDocs": {
          "url": ""
        }
      },
      "Error": {
        "type": "object",
        "properties": {
          "code": {
            "maximum": 599,
            "minimum": 100,
            "type": "integer",
            "description": "HTTP status code of the error (for example 400, 404, 500).",
            "format": "int32"
          },
          "message": {
            "maxLength": 4096,
            "minLength": 0,
            "pattern": "^[\\s\\S]*$",
            "type": "string",
            "description": "Human-readable description of the error."
          }
        },
        "description": "Standard error response body returned for a failed request."
      },
      "FilterPathAndValues": {
        "title": "FilterPathAndValues",
        "required": [
          "path"
        ],
        "type": "object",
        "oneOf": [
          {
            "required": [
              "multipleValues"
            ],
            "type": "object"
          },
          {
            "required": [
              "filters"
            ],
            "type": "object"
          }
        ],
        "properties": {
          "filters": {
            "allOf": [
              {
                "$ref": "#/components/schemas/Filters"
              }
            ],
            "description": "The filters."
          },
          "multipleValues": {
            "$ref": "#/components/schemas/MultipleValues"
          },
          "path": {
            "minLength": 0,
            "type": "string",
            "examples": [
              "test"
            ]
          }
        },
        "description": "This data structure represents a filter path and values",
        "externalDocs": {
          "url": ""
        }
      },
      "Filters": {
        "title": "Filters",
        "required": [
          "pathAndValues"
        ],
        "type": "object",
        "properties": {
          "operator": {
            "allOf": [
              {
                "$ref": "#/components/schemas/v3.FilterOperator"
              }
            ],
            "examples": [
              "FILTER_OPERATOR_OR"
            ]
          },
          "pathAndValues": {
            "minItems": 0,
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/FilterPathAndValues"
            }
          }
        },
        "description": "This data structure represents a filter",
        "externalDocs": {
          "url": ""
        }
      },
      "GetQuotaAllocationRuleSetResponse": {
        "title": "Get quota allocation rule set response",
        "type": "object",
        "properties": {
          "ruleSet": {
            "$ref": "#/components/schemas/QuotaAllocationEntityTypeRuleSet"
          }
        },
        "description": "Response containing quota allocation rule set",
        "externalDocs": {
          "url": ""
        }
      },
      "MultipleValues": {
        "type": "object",
        "properties": {
          "matcher": {
            "$ref": "#/components/schemas/events.v3.FilterMatcher"
          },
          "values": {
            "minItems": 0,
            "type": "array",
            "items": {
              "minLength": 0,
              "type": "string"
            }
          }
        }
      },
      "QuotaAllocationEntityTypeRule": {
        "title": "Quota allocation entity type rule",
        "required": [
          "entityType",
          "allocation",
          "enabled",
          "canOverflow"
        ],
        "type": "object",
        "properties": {
          "allocation": {
            "type": "number",
            "description": "The allocation.",
            "format": "float"
          },
          "allocationType": {
            "allOf": [
              {
                "$ref": "#/components/schemas/QuotaAllocationType"
              }
            ],
            "description": "Determines whether allocation is interpreted as a percentage or locked units. Unspecified defaults to percentage for backwards compatibility."
          },
          "canOverflow": {
            "type": "boolean",
            "description": "The can overflow."
          },
          "cxManaged": {
            "type": "boolean",
            "description": "Indicates whether the quota allocation rule is managed by Coralogix. This field is returned by the service and must not be sent in Create or Replace requests.",
            "readOnly": true
          },
          "enabled": {
            "type": "boolean",
            "description": "Whether this resource is enabled."
          },
          "entityType": {
            "minLength": 0,
            "type": "string",
            "description": "The entity type."
          }
        },
        "description": "Defines quota allocation rule for a specific entity type",
        "externalDocs": {
          "url": ""
        }
      },
      "QuotaAllocationEntityTypeRuleSet": {
        "title": "Quota allocation entity type rule set",
        "required": [
          "rules"
        ],
        "type": "object",
        "properties": {
          "id": {
            "minLength": 0,
            "type": "string",
            "description": "Unique identifier."
          },
          "rules": {
            "minItems": 0,
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/QuotaAllocationEntityTypeRule"
            },
            "description": "List of rules."
          }
        },
        "description": "Contains a collection of quota allocation rules for entity types",
        "externalDocs": {
          "url": ""
        }
      },
      "QuotaAllocationType": {
        "title": "Quota allocation type",
        "enum": [
          "QUOTA_ALLOCATION_TYPE_UNSPECIFIED",
          "QUOTA_ALLOCATION_TYPE_PERCENTAGE",
          "QUOTA_ALLOCATION_TYPE_LOCKED_UNITS"
        ],
        "type": "string",
        "description": "Specifies whether the allocation value is interpreted as a percentage or as locked units."
      },
      "ReplaceQuotaAllocationRuleSetResponse": {
        "title": "Replace quota allocation rule set response",
        "type": "object",
        "properties": {
          "ruleSet": {
            "$ref": "#/components/schemas/QuotaAllocationEntityTypeRuleSet"
          }
        },
        "description": "Response confirming quota allocation rule set has been successfully replaced",
        "externalDocs": {
          "url": ""
        }
      },
      "events.v3.FilterMatcher": {
        "enum": [
          "FILTER_MATCHER_TEXT_OR_UNSPECIFIED",
          "FILTER_MATCHER_REGEXP"
        ],
        "type": "string"
      },
      "v3.FilterOperator": {
        "enum": [
          "FILTER_OPERATOR_AND_OR_UNSPECIFIED",
          "FILTER_OPERATOR_OR"
        ],
        "type": "string",
        "description": "Filter operator."
      }
    }
  }
}