openapi: 3.0.3
info:
  title: Test API Services
  version: 1.0.0
  description: A simple spec designed to be split by the users and products tags.

tags:
  - name: users
    description: Operations related to user accounts.
  - name: products
    description: Managing catalog items.

paths:
  /users:
    get:
      tags:
        - users
      summary: List all users
      operationId: listUsers
      responses:
        "200":
          description: A list of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
    post:
      tags:
        - users
      summary: Create a new user
      operationId: createUser
      responses:
        "201":
          description: User created successfully.

  /products/{productId}:
    parameters:
      - name: productId
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
        - products
      summary: Get product details
      operationId: getProductById
      responses:
        "200":
          description: Product details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"

components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier.
        name:
          type: string
          description: Name of the item.
