name = 'cx-api'
proto_out_dir = './proto'

[rules-api-protobuf]
url = 'github.com/coralogix/rules-api-protobuf'
revision = 'v0.17.1'

[alerts-api-protobuf]
url = 'github.com/coralogix/cx-api-alerts'
revision = "v0.5.8"

[cx-api-views]
url = 'github.com/coralogix/cx-api-views'
revision = "v1.2"
allow_policies = [
    "/com/coralogixapis/views/v1/audit_log.proto",
    "/com/coralogixapis/views/v1/filters.proto",
    "/com/coralogixapis/views/v1/search_query.proto",
    "/com/coralogixapis/views/v1/services/views_folders_service.proto",
    "/com/coralogixapis/views/v1/services/views_service.proto",
    "/com/coralogixapis/views/v1/time_selection.proto",
    "/com/coralogixapis/views/v1/view_folder.proto",
]

[cx-api-actions]
url = 'github.com/coralogix/cx-api-actions'
revision = "v0.4.0"

[cx-api-extensions]
url = 'github.com/coralogix/cx-api-extensions'
revision = "v1.0.5"
allow_policies = [
    "/com/coralogix/extensions/v1/*",
    "/com/coralogix/integrations/v1/*",
    "/com/coralogix/outgoing_webhooks/v1/*",
]

[cx-api-quota]
url = 'github.com/coralogix/cx-api-quota'
revision = 'v0.0.8'

[cx-api-dashboards]
url = 'github.com/coralogix/cx-api-dashboards'
allow_policies = [
    "src/com/coralogixapis/dashboards/v1/ast/*",
    "src/com/coralogixapis/dashboards/v1/common/*",
    "src/com/coralogixapis/dashboards/v1/types.proto",
    "src/com/coralogixapis/dashboards/v1/services/dashboard_catalog_service.proto",
    "src/com/coralogixapis/dashboards/v1/services/dashboard_folders_service.proto",
    "src/com/coralogixapis/dashboards/v1/services/dashboards_service.proto",
]
revision = "v2.1.0"

[cx-api-logs2metrics]
url = 'github.com/coralogix/cx-api-logs2metrics'
# allow_policies = [
#     "/com/coralogixapis/logs2metrics/v2/logs_query.proto",
#     "/com/coralogixapis/events2metrics/v2/events2metrics_definition.proto",
#     "/com/coralogixapis/events2metrics/v2/events2metrics_service.proto"
# ]
revision = 'v0.3.0'

[cx-api-data-usage]
url = 'github.com/coralogix/cx-api-data-usage'
revision = "v0.1.18"

[cx-api-enrichment]
url = 'github.com/coralogix/cx-api-enrichment'
revision = "v0.5.7"

[cx-api-tags]
url = 'github.com/coralogix/cx-api-tags'
revision = 'v0.0.6'

[cx-api-organisations]
url = 'github.com/coralogix/cx-api-organisations'
allow_policies = ["/com/coralogixapis/aaa/*"]
revision = "v0.1.32"

[cx-api-service-catalog]
url = 'github.com/coralogix/cx-api-service-catalog'
revision = "v0.3.110"

[cx-api-common]
url = "github.com/coralogix/cx-api-common"
revision = "v1.0.9"

[cx-api-scopes-service]
url = 'github.com/coralogix/cx-api-scopes'
allow_policies = ["/com/coralogixapis/*"]
revision = 'v0.0.1'

[cx-api-apm]
url = 'github.com/coralogix/cx-api-apm'
revision = 'v2.0.6'

[cx-api-alert-scheduler]
url = 'github.com/coralogix/alert-scheduler-rule-protobuf'
revision = 'v0.0.1'

[cx-api-permissions]
url = 'github.com/coralogix/cx-api-permissions'
revision = "v0.1.91"
allow_policies = [
    "/com/coralogix/permissions/models/v1/*",
    "/com/coralogix/permissions/v1/actions_resources.proto",
    "/com/coralogix/permissions/v1/common.proto",
    "/com/coralogix/permissions/v1/permissions_mgmt.proto",
    "/com/coralogix/permissions/v1/team_permissions_mgmt_service.proto",
    "/com/coralogixapis/aaa/apikeys/v3/*",
    "/com/coralogixapis/aaa/rbac/v2/*",
    "/com/coralogixapis/aaa/sso/v2/*",
]

[cx-api-archive]
url = 'github.com/coralogix/cx-api-archive'
revision = "v0.0.85"

[cx-api-metrics-configurator]
url = 'github.com/coralogix/cx-api-metrics-configurator'
allow_policies = [
    "/com/coralogix/metrics/metrics-configurator.proto",
    "/com/coralogix/metrics/metrics-tco.proto",
]
revision = 'v0.0.2'

[cx-api-metrics-rule-manager]
url = "github.com/coralogix/cx-api-clientsets"
revision = "v0.0.7"
allow_policies = ["/com/coralogixapis/metrics-rule-manager/*"]

[cx-api-notification-center]
url = 'github.com/coralogix/cx-api-notification-center'
revision = "v0.4.2"
allow_policies = [
    "/com/coralogixapis/notification_center/common/*",
    "/com/coralogixapis/notification_center/connectors/v1/connector.proto",
    "/com/coralogixapis/notification_center/connectors/v1/connectors_service.proto",
    "/com/coralogixapis/notification_center/entities/v1/entities_service.proto",
    "/com/coralogixapis/notification_center/notifications/v1/notification.proto",
    "/com/coralogixapis/notification_center/notifications/v1/testing.proto",
    "/com/coralogixapis/notification_center/notifications/v1/testing_service.proto",
    "/com/coralogixapis/notification_center/presets/v1/preset.proto",
    "/com/coralogixapis/notification_center/presets/v1/presets_service.proto",
]

[google-api]
url = "github.com/googleapis/googleapis"
revision = "54d659d0ae74f39e92755948b821a1495b3cb3c8"
allow_policies = [
    "/google/api/annotations.proto",
    "/google/api/client.proto",
    "/google/api/field_behavior.proto",
    "/google/api/http.proto",
    "/google/api/launch_stage.proto",
    "/google/api/resource.proto",
    "google/rpc/code.proto",
    "google/rpc/status.proto",
]

[global-mapping]
url = 'github.com/coralogix/cx-api-global-mapping'
revision = 'v1.26.0'
