name = 'cx-api'
proto_out_dir = './proto'

[rules-api-protobuf]
branch = 'master'
url = 'github.com/coralogix/rules-api-protobuf'

[alerts-api-protobuf-v3]
branch = 'master'
url = 'github.com/coralogix/cx-api-alerts'

[cx-api-views]
branch = 'master'
url = 'github.com/coralogix/cx-api-views'

[cx-api-actions]
branch = 'master'
url = 'github.com/coralogix/cx-api-actions'

[cx-api-extensions]
branch = 'master'
url = 'github.com/coralogix/cx-api-extensions'

[cx-api-quota]
branch = 'master'
url = 'github.com/coralogix/cx-api-quota'

[cx-api-dashboards]
branch = 'master'
url = 'github.com/coralogix/cx-api-dashboards'
allow_policies = ["/com/coralogixapis/*"]
rev = "c2262fd30e8ef677d4731a498ed29dd69af87494"

[cx-api-dataprime]
branch = 'master'
url = 'github.com/coralogix/cx-api-dataprime'
content_roots = ["/service", "ast"]

[cx-api-logs2metrics]
branch = 'master'
url = 'github.com/coralogix/cx-api-logs2metrics'
deny_policies = ["/com/coralogixapis/logs2metrics/audit_log.proto"]

[cx-api-data-usage]
branch = 'master'
url = 'github.com/coralogix/cx-api-data-usage'

[cx-api-enrichment]
branch = 'master'
url = 'github.com/coralogix/cx-api-enrichment'

[cx-api-tags]
branch = 'master'
url = 'github.com/coralogix/cx-api-tags'

# [cx-api-incidents]
# branch = 'master'
# url = 'github.com/coralogix/cx-api-incidents'

[cx-api-organisations]
branch = 'master'
url = 'github.com/coralogix/cx-api-organisations'
allow_policies = ["/com/coralogixapis/aaa/*"]

[cx-api-service-catalog]
branch = 'master'
url = 'github.com/coralogix/cx-api-service-catalog'

[cx-api-scopes-service]
branch = 'master'
url = 'github.com/coralogix/scopes-service'
allow_policies = ["/com/coralogixapis/*"]
content_roots = ["/modules/service/proto/"]

[cx-api-schema-store]
branch = 'master'
url = 'github.com/coralogix/cx-api-schema-store'

[cx-api-apm]
branch = 'master'
url = 'github.com/coralogix/cx-api-apm'

[cx-api-alert-scheduler]
branch = 'master'
url = 'github.com/coralogix/alert-scheduler-rule-protobuf'

[cx-api-permissions]
revision = "v0.1.62"
url = 'github.com/coralogix/cx-api-permissions'
allow_policies = ["/com/coralogixapis/aaa/apikeys/v3/*"]

[cx-api-archive]
branch = 'master'
url = 'github.com/coralogix/cx-api-archive'

[cx-api-metrics-configurator]
branch = 'master'
url = 'github.com/coralogix/metrics-configurator'
allow_policies = ["/com/coralogix/metrics/*"]
content_roots = ["/proto/"]


[google-api]
url = "github.com/googleapis/googleapis"
allow_policies = [
    "/google/api/annotations.proto",
    "/google/api/client.proto",
    "/google/api/field_behavior.proto",
    "/google/api/http.proto",
    "/google/api/launch_stage.proto",
    "/google/api/resource.proto",
    "google/rpc/status.proto",
]

[global-mapping]
branch = 'master'
url = 'github.com/coralogix/cx-api-global-mapping'
