{
  "openapi": "3.1.0",
  "info": {
    "title": "",
    "version": "1.0.0"
  },
  "paths": {
    "/data-exploration/views/v1/folders": {
      "get": {
        "description": "List view's folders",
        "operationId": "ViewsFoldersService_ListViewFolders",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "example": {
                  "folders": [
                    {
                      "id": "0cd4ed54-9b59-4eef-b329-151a167e2304",
                      "name": "My Folder"
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ListViewFoldersResponse"
                }
              }
            },
            "description": ""
          }
        },
        "summary": "List view folders service",
        "tags": [
          "Folders for views service"
        ]
      },
      "put": {
        "description": "Replaces an existing view folder",
        "operationId": "ViewsFoldersService_ReplaceViewFolder",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "description": "View folder.",
                "properties": {
                  "id": {
                    "description": "Unique identifier for folders",
                    "examples": [
                      "3dc02998-0b50-4ea8-b68a-4779d716fa1f"
                    ],
                    "maxLength": 36,
                    "minLength": 36,
                    "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
                    "type": "string"
                  },
                  "name": {
                    "description": "Folder name",
                    "examples": [
                      "My Folder"
                    ],
                    "maxLength": 100,
                    "minLength": 1,
                    "pattern": "^[\\s\\S]*$",
                    "type": "string"
                  }
                },
                "required": [
                  "name"
                ],
                "title": "ViewFolder",
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "example": {
                  "id": "0cd4ed54-9b59-4eef-b329-151a167e2304",
                  "name": "My Folder"
                },
                "schema": {
                  "$ref": "#/components/schemas/ViewFolder"
                }
              }
            },
            "description": ""
          }
        },
        "summary": "Replace View Folder service",
        "tags": [
          "Folders for views service"
        ]
      },
      "post": {
        "description": "Create view folder",
        "operationId": "ViewsFoldersService_CreateViewFolder",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "description": "Create view folder.",
                "properties": {
                  "name": {
                    "description": "Folder name",
                    "examples": [
                      "My Folder"
                    ],
                    "maxLength": 100,
                    "minLength": 1,
                    "pattern": "^[\\s\\S]*$",
                    "type": "string"
                  }
                },
                "title": "CreateViewFolderRequest",
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "example": {
                  "id": "0cd4ed54-9b59-4eef-b329-151a167e2304",
                  "name": "My Folder"
                },
                "schema": {
                  "$ref": "#/components/schemas/ViewFolder"
                }
              }
            },
            "description": ""
          }
        },
        "summary": "Create View Folder service",
        "tags": [
          "Folders for views service"
        ]
      }
    },
    "/data-exploration/views/v1/folders/{id}": {
      "get": {
        "description": "Create view folder",
        "operationId": "ViewsFoldersService_GetViewFolder",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "example": {
                  "id": "0cd4ed54-9b59-4eef-b329-151a167e2304",
                  "name": "My Folder"
                },
                "schema": {
                  "$ref": "#/components/schemas/ViewFolder"
                }
              }
            },
            "description": ""
          }
        },
        "summary": "Get View Folder service",
        "tags": [
          "Folders for views service"
        ]
      },
      "delete": {
        "description": "Deletes a view folder by ID",
        "operationId": "ViewsFoldersService_DeleteViewFolder",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeleteViewFolderResponse"
                }
              }
            },
            "description": ""
          }
        },
        "summary": "Delete View Folder service",
        "tags": [
          "Folders for views service"
        ]
      },
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "Unique identifier for folders",
          "required": true,
          "schema": {
            "maxLength": 36,
            "minLength": 36,
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
            "type": "string",
            "description": "Unique identifier for folders",
            "examples": [
              "3dc02998-0b50-4ea8-b68a-4779d716fa1f"
            ]
          }
        }
      ]
    }
  },
  "components": {
    "schemas": {
      "DeleteViewFolderResponse": {
        "type": "object",
        "additionalProperties": false,
        "description": "Response returned after successfully deleting a view folder.",
        "externalDocs": {
          "url": ""
        }
      },
      "FilterPathAndValues": {
        "title": "FilterPathAndValues",
        "required": [
          "path"
        ],
        "type": "object",
        "oneOf": [
          {
            "required": [
              "multipleValues"
            ],
            "type": "object"
          },
          {
            "required": [
              "filters"
            ],
            "type": "object"
          }
        ],
        "properties": {
          "filters": {
            "allOf": [
              {
                "$ref": "#/components/schemas/Filters"
              }
            ],
            "description": "The filters."
          },
          "multipleValues": {
            "$ref": "#/components/schemas/MultipleValues"
          },
          "path": {
            "minLength": 0,
            "type": "string",
            "examples": [
              "test"
            ]
          }
        },
        "description": "This data structure represents a filter path and values",
        "externalDocs": {
          "url": ""
        }
      },
      "Filters": {
        "title": "Filters",
        "required": [
          "pathAndValues"
        ],
        "type": "object",
        "properties": {
          "operator": {
            "allOf": [
              {
                "$ref": "#/components/schemas/v3.FilterOperator"
              }
            ],
            "examples": [
              "FILTER_OPERATOR_OR"
            ]
          },
          "pathAndValues": {
            "minItems": 0,
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/FilterPathAndValues"
            }
          }
        },
        "description": "This data structure represents a filter",
        "externalDocs": {
          "url": ""
        }
      },
      "ListViewFoldersResponse": {
        "type": "object",
        "properties": {
          "folders": {
            "maxItems": 100000,
            "minItems": 0,
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ViewFolder"
            },
            "description": "The folders."
          }
        },
        "description": "Response containing a list of view folders.",
        "externalDocs": {
          "url": ""
        }
      },
      "MultipleValues": {
        "type": "object",
        "properties": {
          "matcher": {
            "$ref": "#/components/schemas/events.v3.FilterMatcher"
          },
          "values": {
            "minItems": 0,
            "type": "array",
            "items": {
              "minLength": 0,
              "type": "string"
            }
          }
        }
      },
      "ViewFolder": {
        "title": "ViewFolder",
        "required": [
          "name"
        ],
        "type": "object",
        "properties": {
          "id": {
            "maxLength": 36,
            "minLength": 36,
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
            "type": "string",
            "description": "Unique identifier for folders",
            "examples": [
              "3dc02998-0b50-4ea8-b68a-4779d716fa1f"
            ]
          },
          "name": {
            "maxLength": 100,
            "minLength": 1,
            "pattern": "^[\\s\\S]*$",
            "type": "string",
            "description": "Folder name",
            "examples": [
              "My Folder"
            ]
          }
        },
        "description": "View folder.",
        "externalDocs": {
          "url": ""
        }
      },
      "events.v3.FilterMatcher": {
        "enum": [
          "FILTER_MATCHER_TEXT_OR_UNSPECIFIED",
          "FILTER_MATCHER_REGEXP"
        ],
        "type": "string"
      },
      "v3.FilterOperator": {
        "enum": [
          "FILTER_OPERATOR_AND_OR_UNSPECIFIED",
          "FILTER_OPERATOR_OR"
        ],
        "type": "string",
        "description": "Filter operator."
      }
    }
  }
}