// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.1
// source: com/coralogix/permissions/v1/team_permissions_mgmt_service.proto

package v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv3/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// / Get team group request
type GetTeamGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Team group id
	GroupId       *TeamGroupId `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamGroupRequest) Reset() {
	*x = GetTeamGroupRequest{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamGroupRequest) ProtoMessage() {}

func (x *GetTeamGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamGroupRequest.ProtoReflect.Descriptor instead.
func (*GetTeamGroupRequest) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetTeamGroupRequest) GetGroupId() *TeamGroupId {
	if x != nil {
		return x.GroupId
	}
	return nil
}

// / Get team group response
type GetTeamGroupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Team group
	Group         *TeamGroup `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamGroupResponse) Reset() {
	*x = GetTeamGroupResponse{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamGroupResponse) ProtoMessage() {}

func (x *GetTeamGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamGroupResponse.ProtoReflect.Descriptor instead.
func (*GetTeamGroupResponse) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetTeamGroupResponse) GetGroup() *TeamGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

type GetTeamGroupByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamGroupByNameRequest) Reset() {
	*x = GetTeamGroupByNameRequest{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamGroupByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamGroupByNameRequest) ProtoMessage() {}

func (x *GetTeamGroupByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamGroupByNameRequest.ProtoReflect.Descriptor instead.
func (*GetTeamGroupByNameRequest) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTeamGroupByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetTeamGroupByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *TeamGroup             `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamGroupByNameResponse) Reset() {
	*x = GetTeamGroupByNameResponse{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamGroupByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamGroupByNameResponse) ProtoMessage() {}

func (x *GetTeamGroupByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamGroupByNameResponse.ProtoReflect.Descriptor instead.
func (*GetTeamGroupByNameResponse) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTeamGroupByNameResponse) GetGroup() *TeamGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

// / Get all team groups request
type GetTeamGroupsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Team to fetch team groups for. If not set, fetches groups associated with logged in team
	// / Bear in mind that an user can only fetch groups for logged in team. Unless you want to express this as a
	// / validation of what the logged in team should be, this field can remain empty.
	TeamId        *TeamId `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3,oneof" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamGroupsRequest) Reset() {
	*x = GetTeamGroupsRequest{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamGroupsRequest) ProtoMessage() {}

func (x *GetTeamGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamGroupsRequest.ProtoReflect.Descriptor instead.
func (*GetTeamGroupsRequest) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetTeamGroupsRequest) GetTeamId() *TeamId {
	if x != nil {
		return x.TeamId
	}
	return nil
}

// / Get all team groups response
type GetTeamGroupsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Groups associated with team
	Groups        []*TeamGroup `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamGroupsResponse) Reset() {
	*x = GetTeamGroupsResponse{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamGroupsResponse) ProtoMessage() {}

func (x *GetTeamGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamGroupsResponse.ProtoReflect.Descriptor instead.
func (*GetTeamGroupsResponse) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetTeamGroupsResponse) GetGroups() []*TeamGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

// / Create team group request
type CreateTeamGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Team group name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// / Team which the group will be associated with. If not set, creates group and associates it with logged in team
	// / Bear in mind that an user can only create team for logged in team. Unless you want to express this as a
	// / validation of what the logged in team should be, this field can remain empty.
	TeamId *TeamId `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3,oneof" json:"team_id,omitempty"`
	// / Team group description
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// / Team group external_id. Applies if team is externally defined.
	ExternalId *string `protobuf:"bytes,4,opt,name=external_id,json=externalId,proto3,oneof" json:"external_id,omitempty"`
	// / Roles to associate with team group
	RoleIds []*RoleId `protobuf:"bytes,5,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	// / Users to associate with team group
	UserIds []*UserId `protobuf:"bytes,6,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	// / Optionally set team group scope filters
	ScopeFilters   *ScopeFilters `protobuf:"bytes,7,opt,name=scope_filters,json=scopeFilters,proto3,oneof" json:"scope_filters,omitempty"`
	NextGenScopeId *string       `protobuf:"bytes,8,opt,name=next_gen_scope_id,json=nextGenScopeId,proto3,oneof" json:"next_gen_scope_id,omitempty"`
	// / Group Type, defines the access to the group itself, should default to OPEN
	GroupType     GroupType `protobuf:"varint,9,opt,name=group_type,json=groupType,proto3,enum=com.coralogix.permissions.v1.GroupType" json:"group_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamGroupRequest) Reset() {
	*x = CreateTeamGroupRequest{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamGroupRequest) ProtoMessage() {}

func (x *CreateTeamGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamGroupRequest) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTeamGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTeamGroupRequest) GetTeamId() *TeamId {
	if x != nil {
		return x.TeamId
	}
	return nil
}

func (x *CreateTeamGroupRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateTeamGroupRequest) GetExternalId() string {
	if x != nil && x.ExternalId != nil {
		return *x.ExternalId
	}
	return ""
}

func (x *CreateTeamGroupRequest) GetRoleIds() []*RoleId {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *CreateTeamGroupRequest) GetUserIds() []*UserId {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *CreateTeamGroupRequest) GetScopeFilters() *ScopeFilters {
	if x != nil {
		return x.ScopeFilters
	}
	return nil
}

func (x *CreateTeamGroupRequest) GetNextGenScopeId() string {
	if x != nil && x.NextGenScopeId != nil {
		return *x.NextGenScopeId
	}
	return ""
}

func (x *CreateTeamGroupRequest) GetGroupType() GroupType {
	if x != nil {
		return x.GroupType
	}
	return GroupType_GROUP_TYPE_UNSPECIFIED
}

// / Create team group response
type CreateTeamGroupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Team group id
	GroupId       *TeamGroupId `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamGroupResponse) Reset() {
	*x = CreateTeamGroupResponse{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamGroupResponse) ProtoMessage() {}

func (x *CreateTeamGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateTeamGroupResponse) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTeamGroupResponse) GetGroupId() *TeamGroupId {
	if x != nil {
		return x.GroupId
	}
	return nil
}

// / Update team group request
type UpdateTeamGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Team group to be updated
	GroupId *TeamGroupId `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// / Updated team group name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// / Updated team group description
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// / Updated team group external_id
	ExternalId *string `protobuf:"bytes,4,opt,name=external_id,json=externalId,proto3,oneof" json:"external_id,omitempty"`
	// / If set, new roles to associate with team group
	RoleUpdates *UpdateTeamGroupRequest_RoleUpdates `protobuf:"bytes,5,opt,name=role_updates,json=roleUpdates,proto3,oneof" json:"role_updates,omitempty"`
	// / If set, new users to associate with team group
	UserUpdates *UpdateTeamGroupRequest_UserUpdates `protobuf:"bytes,6,opt,name=user_updates,json=userUpdates,proto3,oneof" json:"user_updates,omitempty"`
	// / If set, updates new team group scope filters
	ScopeFilters *ScopeFilters `protobuf:"bytes,7,opt,name=scope_filters,json=scopeFilters,proto3,oneof" json:"scope_filters,omitempty"`
	// / If set, updates new team group next gen scope
	NextGenScopeId *string `protobuf:"bytes,8,opt,name=next_gen_scope_id,json=nextGenScopeId,proto3,oneof" json:"next_gen_scope_id,omitempty"`
	// / If set, updates team group type
	GroupType     *GroupType `protobuf:"varint,9,opt,name=group_type,json=groupType,proto3,enum=com.coralogix.permissions.v1.GroupType,oneof" json:"group_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeamGroupRequest) Reset() {
	*x = UpdateTeamGroupRequest{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamGroupRequest) ProtoMessage() {}

func (x *UpdateTeamGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateTeamGroupRequest) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTeamGroupRequest) GetGroupId() *TeamGroupId {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *UpdateTeamGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTeamGroupRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateTeamGroupRequest) GetExternalId() string {
	if x != nil && x.ExternalId != nil {
		return *x.ExternalId
	}
	return ""
}

func (x *UpdateTeamGroupRequest) GetRoleUpdates() *UpdateTeamGroupRequest_RoleUpdates {
	if x != nil {
		return x.RoleUpdates
	}
	return nil
}

func (x *UpdateTeamGroupRequest) GetUserUpdates() *UpdateTeamGroupRequest_UserUpdates {
	if x != nil {
		return x.UserUpdates
	}
	return nil
}

func (x *UpdateTeamGroupRequest) GetScopeFilters() *ScopeFilters {
	if x != nil {
		return x.ScopeFilters
	}
	return nil
}

func (x *UpdateTeamGroupRequest) GetNextGenScopeId() string {
	if x != nil && x.NextGenScopeId != nil {
		return *x.NextGenScopeId
	}
	return ""
}

func (x *UpdateTeamGroupRequest) GetGroupType() GroupType {
	if x != nil && x.GroupType != nil {
		return *x.GroupType
	}
	return GroupType_GROUP_TYPE_UNSPECIFIED
}

// / Update team group response
type UpdateTeamGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeamGroupResponse) Reset() {
	*x = UpdateTeamGroupResponse{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamGroupResponse) ProtoMessage() {}

func (x *UpdateTeamGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdateTeamGroupResponse) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{9}
}

// / Delete team group request
type DeleteTeamGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Team group id
	GroupId       *TeamGroupId `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamGroupRequest) Reset() {
	*x = DeleteTeamGroupRequest{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamGroupRequest) ProtoMessage() {}

func (x *DeleteTeamGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeamGroupRequest) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTeamGroupRequest) GetGroupId() *TeamGroupId {
	if x != nil {
		return x.GroupId
	}
	return nil
}

// / Delete team group response
type DeleteTeamGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamGroupResponse) Reset() {
	*x = DeleteTeamGroupResponse{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamGroupResponse) ProtoMessage() {}

func (x *DeleteTeamGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteTeamGroupResponse) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{11}
}

// / Fetches all users linked with given team group
type GetGroupUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Team group id
	GroupId *TeamGroupId `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// / Pagination size. Defaults to 100 if empty
	PageSize *uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// / Optional pagination continuation token
	// / Contains an encoded cursor
	PageToken     *string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupUsersRequest) Reset() {
	*x = GetGroupUsersRequest{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupUsersRequest) ProtoMessage() {}

func (x *GetGroupUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupUsersRequest.ProtoReflect.Descriptor instead.
func (*GetGroupUsersRequest) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetGroupUsersRequest) GetGroupId() *TeamGroupId {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *GetGroupUsersRequest) GetPageSize() uint32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *GetGroupUsersRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type GetGroupUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Users []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	// Types that are valid to be assigned to NextPage:
	//
	//	*GetGroupUsersResponse_NoMorePages_
	//	*GetGroupUsersResponse_Token
	NextPage      isGetGroupUsersResponse_NextPage `protobuf_oneof:"next_page"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupUsersResponse) Reset() {
	*x = GetGroupUsersResponse{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupUsersResponse) ProtoMessage() {}

func (x *GetGroupUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupUsersResponse.ProtoReflect.Descriptor instead.
func (*GetGroupUsersResponse) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetGroupUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GetGroupUsersResponse) GetNextPage() isGetGroupUsersResponse_NextPage {
	if x != nil {
		return x.NextPage
	}
	return nil
}

func (x *GetGroupUsersResponse) GetNoMorePages() *GetGroupUsersResponse_NoMorePages {
	if x != nil {
		if x, ok := x.NextPage.(*GetGroupUsersResponse_NoMorePages_); ok {
			return x.NoMorePages
		}
	}
	return nil
}

func (x *GetGroupUsersResponse) GetToken() *GetGroupUsersResponse_NextPageToken {
	if x != nil {
		if x, ok := x.NextPage.(*GetGroupUsersResponse_Token); ok {
			return x.Token
		}
	}
	return nil
}

type isGetGroupUsersResponse_NextPage interface {
	isGetGroupUsersResponse_NextPage()
}

type GetGroupUsersResponse_NoMorePages_ struct {
	NoMorePages *GetGroupUsersResponse_NoMorePages `protobuf:"bytes,2,opt,name=no_more_pages,json=noMorePages,proto3,oneof"`
}

type GetGroupUsersResponse_Token struct {
	Token *GetGroupUsersResponse_NextPageToken `protobuf:"bytes,3,opt,name=token,proto3,oneof"`
}

func (*GetGroupUsersResponse_NoMorePages_) isGetGroupUsersResponse_NextPage() {}

func (*GetGroupUsersResponse_Token) isGetGroupUsersResponse_NextPage() {}

// / Add users to an existing team group
type AddUsersToTeamGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Team group id to add users to
	GroupId *TeamGroupId `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// / Users to add to group
	UserIds       []*UserId `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUsersToTeamGroupRequest) Reset() {
	*x = AddUsersToTeamGroupRequest{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUsersToTeamGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUsersToTeamGroupRequest) ProtoMessage() {}

func (x *AddUsersToTeamGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUsersToTeamGroupRequest.ProtoReflect.Descriptor instead.
func (*AddUsersToTeamGroupRequest) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{14}
}

func (x *AddUsersToTeamGroupRequest) GetGroupId() *TeamGroupId {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *AddUsersToTeamGroupRequest) GetUserIds() []*UserId {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// / Add users to an existing team group response
type AddUsersToTeamGroupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Team id to which given team group belongs
	TeamId        *TeamId `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUsersToTeamGroupResponse) Reset() {
	*x = AddUsersToTeamGroupResponse{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUsersToTeamGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUsersToTeamGroupResponse) ProtoMessage() {}

func (x *AddUsersToTeamGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUsersToTeamGroupResponse.ProtoReflect.Descriptor instead.
func (*AddUsersToTeamGroupResponse) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{15}
}

func (x *AddUsersToTeamGroupResponse) GetTeamId() *TeamId {
	if x != nil {
		return x.TeamId
	}
	return nil
}

// / Associate new users with groups in a team
// / Allows to associate any number of users with any number of groups belonging to a team
type AddUsersToTeamGroupsRequest struct {
	state           protoimpl.MessageState                             `protogen:"open.v1"`
	TeamId          *TeamId                                            `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	AddUsersToGroup []*AddUsersToTeamGroupsRequest_AddUsersToTeamGroup `protobuf:"bytes,2,rep,name=add_users_to_group,json=addUsersToGroup,proto3" json:"add_users_to_group,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddUsersToTeamGroupsRequest) Reset() {
	*x = AddUsersToTeamGroupsRequest{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUsersToTeamGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUsersToTeamGroupsRequest) ProtoMessage() {}

func (x *AddUsersToTeamGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUsersToTeamGroupsRequest.ProtoReflect.Descriptor instead.
func (*AddUsersToTeamGroupsRequest) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{16}
}

func (x *AddUsersToTeamGroupsRequest) GetTeamId() *TeamId {
	if x != nil {
		return x.TeamId
	}
	return nil
}

func (x *AddUsersToTeamGroupsRequest) GetAddUsersToGroup() []*AddUsersToTeamGroupsRequest_AddUsersToTeamGroup {
	if x != nil {
		return x.AddUsersToGroup
	}
	return nil
}

type AddUsersToTeamGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUsersToTeamGroupsResponse) Reset() {
	*x = AddUsersToTeamGroupsResponse{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUsersToTeamGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUsersToTeamGroupsResponse) ProtoMessage() {}

func (x *AddUsersToTeamGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUsersToTeamGroupsResponse.ProtoReflect.Descriptor instead.
func (*AddUsersToTeamGroupsResponse) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{17}
}

// / Remove users from an existing team group
type RemoveUsersFromTeamGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Team group id to remove users from
	GroupId *TeamGroupId `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// / Users to remove to group
	UserIds       []*UserId `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUsersFromTeamGroupRequest) Reset() {
	*x = RemoveUsersFromTeamGroupRequest{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUsersFromTeamGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUsersFromTeamGroupRequest) ProtoMessage() {}

func (x *RemoveUsersFromTeamGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUsersFromTeamGroupRequest.ProtoReflect.Descriptor instead.
func (*RemoveUsersFromTeamGroupRequest) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveUsersFromTeamGroupRequest) GetGroupId() *TeamGroupId {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *RemoveUsersFromTeamGroupRequest) GetUserIds() []*UserId {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type RemoveUsersFromTeamGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUsersFromTeamGroupResponse) Reset() {
	*x = RemoveUsersFromTeamGroupResponse{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUsersFromTeamGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUsersFromTeamGroupResponse) ProtoMessage() {}

func (x *RemoveUsersFromTeamGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUsersFromTeamGroupResponse.ProtoReflect.Descriptor instead.
func (*RemoveUsersFromTeamGroupResponse) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{19}
}

// / Remove users from groups in a team
// / Allows the removal of any number of users and any number of groups belonging to a team
type RemoveUsersFromTeamGroupsRequest struct {
	state                protoimpl.MessageState                                       `protogen:"open.v1"`
	TeamId               *TeamId                                                      `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	RemoveUsersFromGroup []*RemoveUsersFromTeamGroupsRequest_RemoveUsersFromTeamGroup `protobuf:"bytes,2,rep,name=remove_users_from_group,json=removeUsersFromGroup,proto3" json:"remove_users_from_group,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RemoveUsersFromTeamGroupsRequest) Reset() {
	*x = RemoveUsersFromTeamGroupsRequest{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUsersFromTeamGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUsersFromTeamGroupsRequest) ProtoMessage() {}

func (x *RemoveUsersFromTeamGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUsersFromTeamGroupsRequest.ProtoReflect.Descriptor instead.
func (*RemoveUsersFromTeamGroupsRequest) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveUsersFromTeamGroupsRequest) GetTeamId() *TeamId {
	if x != nil {
		return x.TeamId
	}
	return nil
}

func (x *RemoveUsersFromTeamGroupsRequest) GetRemoveUsersFromGroup() []*RemoveUsersFromTeamGroupsRequest_RemoveUsersFromTeamGroup {
	if x != nil {
		return x.RemoveUsersFromGroup
	}
	return nil
}

// / Remove users from existing groups
type RemoveUsersFromTeamGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUsersFromTeamGroupsResponse) Reset() {
	*x = RemoveUsersFromTeamGroupsResponse{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUsersFromTeamGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUsersFromTeamGroupsResponse) ProtoMessage() {}

func (x *RemoveUsersFromTeamGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUsersFromTeamGroupsResponse.ProtoReflect.Descriptor instead.
func (*RemoveUsersFromTeamGroupsResponse) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{21}
}

// / Set team group scope request
type SetTeamGroupScopeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Team group to set scope to
	GroupId *TeamGroupId `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// / team group scope filters
	ScopeFilters  *ScopeFilters `protobuf:"bytes,2,opt,name=scope_filters,json=scopeFilters,proto3" json:"scope_filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTeamGroupScopeRequest) Reset() {
	*x = SetTeamGroupScopeRequest{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTeamGroupScopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTeamGroupScopeRequest) ProtoMessage() {}

func (x *SetTeamGroupScopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTeamGroupScopeRequest.ProtoReflect.Descriptor instead.
func (*SetTeamGroupScopeRequest) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{22}
}

func (x *SetTeamGroupScopeRequest) GetGroupId() *TeamGroupId {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *SetTeamGroupScopeRequest) GetScopeFilters() *ScopeFilters {
	if x != nil {
		return x.ScopeFilters
	}
	return nil
}

// / Set team group scope response
type SetTeamGroupScopeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Created scope_id or 0 if already exists and was replaced.
	ScopeId       *ScopeId `protobuf:"bytes,1,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTeamGroupScopeResponse) Reset() {
	*x = SetTeamGroupScopeResponse{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTeamGroupScopeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTeamGroupScopeResponse) ProtoMessage() {}

func (x *SetTeamGroupScopeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTeamGroupScopeResponse.ProtoReflect.Descriptor instead.
func (*SetTeamGroupScopeResponse) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{23}
}

func (x *SetTeamGroupScopeResponse) GetScopeId() *ScopeId {
	if x != nil {
		return x.ScopeId
	}
	return nil
}

// / Get team group scope request
type GetTeamGroupScopeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Team group to set scope to
	GroupId       *TeamGroupId `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamGroupScopeRequest) Reset() {
	*x = GetTeamGroupScopeRequest{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamGroupScopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamGroupScopeRequest) ProtoMessage() {}

func (x *GetTeamGroupScopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamGroupScopeRequest.ProtoReflect.Descriptor instead.
func (*GetTeamGroupScopeRequest) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{24}
}

func (x *GetTeamGroupScopeRequest) GetGroupId() *TeamGroupId {
	if x != nil {
		return x.GroupId
	}
	return nil
}

// / Set team group scope response
type GetTeamGroupScopeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Scope if group has one set
	Scope         *Scope `protobuf:"bytes,1,opt,name=scope,proto3,oneof" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamGroupScopeResponse) Reset() {
	*x = GetTeamGroupScopeResponse{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamGroupScopeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamGroupScopeResponse) ProtoMessage() {}

func (x *GetTeamGroupScopeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamGroupScopeResponse.ProtoReflect.Descriptor instead.
func (*GetTeamGroupScopeResponse) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{25}
}

func (x *GetTeamGroupScopeResponse) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

// / Specifies new roles to assign to a group removing previous ones
type UpdateTeamGroupRequest_RoleUpdates struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Roles to associate with a team group
	RoleIds       []*RoleId `protobuf:"bytes,1,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeamGroupRequest_RoleUpdates) Reset() {
	*x = UpdateTeamGroupRequest_RoleUpdates{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamGroupRequest_RoleUpdates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamGroupRequest_RoleUpdates) ProtoMessage() {}

func (x *UpdateTeamGroupRequest_RoleUpdates) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamGroupRequest_RoleUpdates.ProtoReflect.Descriptor instead.
func (*UpdateTeamGroupRequest_RoleUpdates) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{8, 0}
}

func (x *UpdateTeamGroupRequest_RoleUpdates) GetRoleIds() []*RoleId {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

// / Specifies new users to assign to a group removing previous ones
type UpdateTeamGroupRequest_UserUpdates struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Users to associate with a team group
	UserIds       []*UserId `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeamGroupRequest_UserUpdates) Reset() {
	*x = UpdateTeamGroupRequest_UserUpdates{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamGroupRequest_UserUpdates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamGroupRequest_UserUpdates) ProtoMessage() {}

func (x *UpdateTeamGroupRequest_UserUpdates) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamGroupRequest_UserUpdates.ProtoReflect.Descriptor instead.
func (*UpdateTeamGroupRequest_UserUpdates) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{8, 1}
}

func (x *UpdateTeamGroupRequest_UserUpdates) GetUserIds() []*UserId {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetGroupUsersResponse_NoMorePages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupUsersResponse_NoMorePages) Reset() {
	*x = GetGroupUsersResponse_NoMorePages{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupUsersResponse_NoMorePages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupUsersResponse_NoMorePages) ProtoMessage() {}

func (x *GetGroupUsersResponse_NoMorePages) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupUsersResponse_NoMorePages.ProtoReflect.Descriptor instead.
func (*GetGroupUsersResponse_NoMorePages) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{13, 0}
}

type GetGroupUsersResponse_NextPageToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextPageToken string                 `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupUsersResponse_NextPageToken) Reset() {
	*x = GetGroupUsersResponse_NextPageToken{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupUsersResponse_NextPageToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupUsersResponse_NextPageToken) ProtoMessage() {}

func (x *GetGroupUsersResponse_NextPageToken) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupUsersResponse_NextPageToken.ProtoReflect.Descriptor instead.
func (*GetGroupUsersResponse_NextPageToken) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{13, 1}
}

func (x *GetGroupUsersResponse_NextPageToken) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type AddUsersToTeamGroupsRequest_AddUsersToTeamGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Team group id to add users to
	GroupId *TeamGroupId `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// / Users to add to group
	UserIds       []*UserId `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUsersToTeamGroupsRequest_AddUsersToTeamGroup) Reset() {
	*x = AddUsersToTeamGroupsRequest_AddUsersToTeamGroup{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUsersToTeamGroupsRequest_AddUsersToTeamGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUsersToTeamGroupsRequest_AddUsersToTeamGroup) ProtoMessage() {}

func (x *AddUsersToTeamGroupsRequest_AddUsersToTeamGroup) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUsersToTeamGroupsRequest_AddUsersToTeamGroup.ProtoReflect.Descriptor instead.
func (*AddUsersToTeamGroupsRequest_AddUsersToTeamGroup) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{16, 0}
}

func (x *AddUsersToTeamGroupsRequest_AddUsersToTeamGroup) GetGroupId() *TeamGroupId {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *AddUsersToTeamGroupsRequest_AddUsersToTeamGroup) GetUserIds() []*UserId {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type RemoveUsersFromTeamGroupsRequest_RemoveUsersFromTeamGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Team group id to remove users from
	GroupId *TeamGroupId `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// / Users to remove to group
	UserIds       []*UserId `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUsersFromTeamGroupsRequest_RemoveUsersFromTeamGroup) Reset() {
	*x = RemoveUsersFromTeamGroupsRequest_RemoveUsersFromTeamGroup{}
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUsersFromTeamGroupsRequest_RemoveUsersFromTeamGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUsersFromTeamGroupsRequest_RemoveUsersFromTeamGroup) ProtoMessage() {}

func (x *RemoveUsersFromTeamGroupsRequest_RemoveUsersFromTeamGroup) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUsersFromTeamGroupsRequest_RemoveUsersFromTeamGroup.ProtoReflect.Descriptor instead.
func (*RemoveUsersFromTeamGroupsRequest_RemoveUsersFromTeamGroup) Descriptor() ([]byte, []int) {
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP(), []int{20, 0}
}

func (x *RemoveUsersFromTeamGroupsRequest_RemoveUsersFromTeamGroup) GetGroupId() *TeamGroupId {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *RemoveUsersFromTeamGroupsRequest_RemoveUsersFromTeamGroup) GetUserIds() []*UserId {
	if x != nil {
		return x.UserIds
	}
	return nil
}

var File_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto protoreflect.FileDescriptor

const file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDesc = "" +
	"\n" +
	"@com/coralogix/permissions/v1/team_permissions_mgmt_service.proto\x12\x1ccom.coralogix.permissions.v1\x1a)com/coralogix/permissions/v1/common.proto\x1a3com/coralogix/permissions/v1/permissions_mgmt.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv3/options/annotations.proto\"\x9c\x03\n" +
	"\x13GetTeamGroupRequest\x12D\n" +
	"\bgroup_id\x18\x01 \x01(\v2).com.coralogix.permissions.v1.TeamGroupIdR\agroupId:\xbe\x02\x9aA\xba\x02\n" +
	"\xa4\x01*\x13GetTeamGroupRequest2\x8c\x01Request to retrieve a specific team group by its unique identifier. Used to fetch details about group membership, roles, and scope settings.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/\"\x8e\x03\n" +
	"\x14GetTeamGroupResponse\x12=\n" +
	"\x05group\x18\x01 \x01(\v2'.com.coralogix.permissions.v1.TeamGroupR\x05group:\xb6\x02\x9aA\xb2\x02\n" +
	"\x9c\x01*\x14GetTeamGroupResponse2\x83\x01Response containing the complete details of a requested team group, including its members, assigned roles, and scope configuration.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/\"\xde\x02\n" +
	"\x19GetTeamGroupByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name:\xac\x02\x9aA\xa8\x02\n" +
	"\x92\x01*\x19GetTeamGroupByNameRequest2uRequest to retrieve a team group using its name within the authenticated team's context. Alternative to lookup by ID.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/\"\xa2\x03\n" +
	"\x1aGetTeamGroupByNameResponse\x12=\n" +
	"\x05group\x18\x01 \x01(\v2'.com.coralogix.permissions.v1.TeamGroupR\x05group:\xc4\x02\x9aA\xc0\x02\n" +
	"\xaa\x01*\x1aGetTeamGroupByNameResponse2\x8b\x01Response containing the complete details of a team group that matches the requested name, including its members, roles, and scope settings.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/\"\xa2\x03\n" +
	"\x14GetTeamGroupsRequest\x12B\n" +
	"\ateam_id\x18\x01 \x01(\v2$.com.coralogix.permissions.v1.TeamIdH\x00R\x06teamId\x88\x01\x01:\xb9\x02\x9aA\xb5\x02\n" +
	"\x9f\x01*\x14GetTeamGroupsRequest2\x86\x01Request to retrieve all groups associated with a specific team. If team_id is not provided, fetches groups for the authenticated team.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/B\n" +
	"\n" +
	"\b_team_id\"\x8b\x03\n" +
	"\x15GetTeamGroupsResponse\x12?\n" +
	"\x06groups\x18\x01 \x03(\v2'.com.coralogix.permissions.v1.TeamGroupR\x06groups:\xb0\x02\x9aA\xac\x02\n" +
	"\x96\x01*\x15GetTeamGroupsResponse2}Response containing a list of all team groups and their complete details, including members, roles, and scope configurations.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/\"\xc9\a\n" +
	"\x16CreateTeamGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12B\n" +
	"\ateam_id\x18\x02 \x01(\v2$.com.coralogix.permissions.v1.TeamIdH\x00R\x06teamId\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12$\n" +
	"\vexternal_id\x18\x04 \x01(\tH\x02R\n" +
	"externalId\x88\x01\x01\x12?\n" +
	"\brole_ids\x18\x05 \x03(\v2$.com.coralogix.permissions.v1.RoleIdR\aroleIds\x12?\n" +
	"\buser_ids\x18\x06 \x03(\v2$.com.coralogix.permissions.v1.UserIdR\auserIds\x12T\n" +
	"\rscope_filters\x18\a \x01(\v2*.com.coralogix.permissions.v1.ScopeFiltersH\x03R\fscopeFilters\x88\x01\x01\x12.\n" +
	"\x11next_gen_scope_id\x18\b \x01(\tH\x04R\x0enextGenScopeId\x88\x01\x01\x12F\n" +
	"\n" +
	"group_type\x18\t \x01(\x0e2'.com.coralogix.permissions.v1.GroupTypeR\tgroupType:\xe5\x02\x9aA\xe1\x02\n" +
	"\xcb\x01*\x16CreateTeamGroupRequest2\xb0\x01Request to create a new team group with specified name, description, roles, users, and optional scope filters. Can be associated with a specific team or the authenticated team.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/B\n" +
	"\n" +
	"\b_team_idB\x0e\n" +
	"\f_descriptionB\x0e\n" +
	"\f_external_idB\x10\n" +
	"\x0e_scope_filtersB\x14\n" +
	"\x12_next_gen_scope_id\"\xe0\x02\n" +
	"\x17CreateTeamGroupResponse\x12D\n" +
	"\bgroup_id\x18\x01 \x01(\v2).com.coralogix.permissions.v1.TeamGroupIdR\agroupId:\xfe\x01\x9aA\xfa\x01\n" +
	"e*\x17CreateTeamGroupResponse2JResponse containing the unique identifier of the newly created team group.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/\"\x98\r\n" +
	"\x16UpdateTeamGroupRequest\x12D\n" +
	"\bgroup_id\x18\x01 \x01(\v2).com.coralogix.permissions.v1.TeamGroupIdR\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12$\n" +
	"\vexternal_id\x18\x04 \x01(\tH\x01R\n" +
	"externalId\x88\x01\x01\x12h\n" +
	"\frole_updates\x18\x05 \x01(\v2@.com.coralogix.permissions.v1.UpdateTeamGroupRequest.RoleUpdatesH\x02R\vroleUpdates\x88\x01\x01\x12h\n" +
	"\fuser_updates\x18\x06 \x01(\v2@.com.coralogix.permissions.v1.UpdateTeamGroupRequest.UserUpdatesH\x03R\vuserUpdates\x88\x01\x01\x12T\n" +
	"\rscope_filters\x18\a \x01(\v2*.com.coralogix.permissions.v1.ScopeFiltersH\x04R\fscopeFilters\x88\x01\x01\x12.\n" +
	"\x11next_gen_scope_id\x18\b \x01(\tH\x05R\x0enextGenScopeId\x88\x01\x01\x12K\n" +
	"\n" +
	"group_type\x18\t \x01(\x0e2'.com.coralogix.permissions.v1.GroupTypeH\x06R\tgroupType\x88\x01\x01\x1a\xc3\x02\n" +
	"\vRoleUpdates\x12?\n" +
	"\brole_ids\x18\x01 \x03(\v2$.com.coralogix.permissions.v1.RoleIdR\aroleIds:\xf2\x01\x9aA\xee\x01\n" +
	"Y*\vRoleUpdates2JThis data structure represents the information associated with an API key.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/\x1a\xc3\x02\n" +
	"\vUserUpdates\x12?\n" +
	"\buser_ids\x18\x01 \x03(\v2$.com.coralogix.permissions.v1.UserIdR\auserIds:\xf2\x01\x9aA\xee\x01\n" +
	"Y*\vUserUpdates2JThis data structure represents the information associated with an API key.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/:\xaa\x02\x9aA\xa6\x02\n" +
	"\x90\x01*\x16UpdateTeamGroupRequest2vRequest to modify an existing team group's details, including its name, description, roles, users, and scope settings.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/B\x0e\n" +
	"\f_descriptionB\x0e\n" +
	"\f_external_idB\x0f\n" +
	"\r_role_updatesB\x0f\n" +
	"\r_user_updatesB\x10\n" +
	"\x0e_scope_filtersB\x14\n" +
	"\x12_next_gen_scope_idB\r\n" +
	"\v_group_type\"\x9a\x02\n" +
	"\x17UpdateTeamGroupResponse:\xfe\x01\x9aA\xfa\x01\n" +
	"e*\x17UpdateTeamGroupResponse2JResponse confirming the successful update of a team group's configuration.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/\"\x81\x03\n" +
	"\x16DeleteTeamGroupRequest\x12D\n" +
	"\bgroup_id\x18\x01 \x01(\v2).com.coralogix.permissions.v1.TeamGroupIdR\agroupId:\xa0\x02\x9aA\x9c\x02\n" +
	"\x86\x01*\x16DeleteTeamGroupRequest2lRequest to remove a team group and all its associated role and user assignments using its unique identifier.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/\"\xae\x02\n" +
	"\x17DeleteTeamGroupResponse:\x92\x02\x9aA\x8e\x02\n" +
	"y*\x17DeleteTeamGroupResponse2^Response confirming the successful deletion of a team group and its associated configurations.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/\"\xcf\x03\n" +
	"\x14GetGroupUsersRequest\x12D\n" +
	"\bgroup_id\x18\x01 \x01(\v2).com.coralogix.permissions.v1.TeamGroupIdR\agroupId\x12 \n" +
	"\tpage_size\x18\x02 \x01(\rH\x00R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tH\x01R\tpageToken\x88\x01\x01:\x8d\x02\x9aA\x89\x02\n" +
	"t*\x14GetGroupUsersRequest2\\Request to retrieve all users assigned to a specific team group identified by its unique ID.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/B\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\xe4\b\n" +
	"\x15GetGroupUsersResponse\x128\n" +
	"\x05users\x18\x01 \x03(\v2\".com.coralogix.permissions.v1.UserR\x05users\x12e\n" +
	"\rno_more_pages\x18\x02 \x01(\v2?.com.coralogix.permissions.v1.GetGroupUsersResponse.NoMorePagesH\x00R\vnoMorePages\x12Y\n" +
	"\x05token\x18\x03 \x01(\v2A.com.coralogix.permissions.v1.GetGroupUsersResponse.NextPageTokenH\x00R\x05token\x1a\x82\x02\n" +
	"\vNoMorePages:\xf2\x01\x9aA\xee\x01\n" +
	"Y*\vNoMorePages2JThis data structure represents the information associated with an API key.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/\x1a\xae\x02\n" +
	"\rNextPageToken\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken:\xf4\x01\x9aA\xf0\x01\n" +
	"[*\rNextPageToken2JThis data structure represents the information associated with an API key.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/:\x8b\x02\x9aA\x87\x02\n" +
	"r*\x15GetGroupUsersResponse2YResponse containing the list of all users currently assigned to the requested team group.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/B\v\n" +
	"\tnext_page\"\xd2\x03\n" +
	"\x1aAddUsersToTeamGroupRequest\x12D\n" +
	"\bgroup_id\x18\x01 \x01(\v2).com.coralogix.permissions.v1.TeamGroupIdR\agroupId\x12?\n" +
	"\buser_ids\x18\x02 \x03(\v2$.com.coralogix.permissions.v1.UserIdR\auserIds:\xac\x02\x9aA\xa8\x02\n" +
	"\x92\x01*\x1aAddUsersToTeamGroupRequest2tRequest to assign additional users to an existing team group, granting them the group's roles and scope permissions.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/\"\xe8\x02\n" +
	"\x1bAddUsersToTeamGroupResponse\x12=\n" +
	"\ateam_id\x18\x01 \x01(\v2$.com.coralogix.permissions.v1.TeamIdR\x06teamId:\x89\x02\x9aA\x85\x02\n" +
	"p*\x1bAddUsersToTeamGroupResponse2QResponse confirming the successful addition of users to the specified team group.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/\"\xa5\a\n" +
	"\x1bAddUsersToTeamGroupsRequest\x12=\n" +
	"\ateam_id\x18\x01 \x01(\v2$.com.coralogix.permissions.v1.TeamIdR\x06teamId\x12z\n" +
	"\x12add_users_to_group\x18\x02 \x03(\v2M.com.coralogix.permissions.v1.AddUsersToTeamGroupsRequest.AddUsersToTeamGroupR\x0faddUsersToGroup\x1a\x99\x03\n" +
	"\x13AddUsersToTeamGroup\x12D\n" +
	"\bgroup_id\x18\x01 \x01(\v2).com.coralogix.permissions.v1.TeamGroupIdR\agroupId\x12?\n" +
	"\buser_ids\x18\x02 \x03(\v2$.com.coralogix.permissions.v1.UserIdR\auserIds:\xfa\x01\x9aA\xf6\x01\n" +
	"a*\x13AddUsersToTeamGroup2JThis data structure represents the information associated with an API key.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/:\xae\x02\x9aA\xaa\x02\n" +
	"\x94\x01*\x1bAddUsersToTeamGroupsRequest2uBulk request to assign users to multiple team groups simultaneously, efficiently managing group memberships at scale.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/\"\xac\x02\n" +
	"\x1cAddUsersToTeamGroupsResponse:\x8b\x02\x9aA\x87\x02\n" +
	"r*\x1cAddUsersToTeamGroupsResponse2RResponse confirming the successful bulk addition of users to multiple team groups.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/\"\xde\x03\n" +
	"\x1fRemoveUsersFromTeamGroupRequest\x12D\n" +
	"\bgroup_id\x18\x01 \x01(\v2).com.coralogix.permissions.v1.TeamGroupIdR\agroupId\x12?\n" +
	"\buser_ids\x18\x02 \x03(\v2$.com.coralogix.permissions.v1.UserIdR\auserIds:\xb3\x02\x9aA\xaf\x02\n" +
	"\x99\x01*\x1fRemoveUsersFromTeamGroupRequest2vRequest to remove specified users from a team group, revoking their access to the group's roles and scope permissions.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/\"\xb4\x02\n" +
	" RemoveUsersFromTeamGroupResponse:\x8f\x02\x9aA\x8b\x02\n" +
	"v* RemoveUsersFromTeamGroupResponse2RResponse confirming the successful removal of users from the specified team group.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/\"\xdc\a\n" +
	" RemoveUsersFromTeamGroupsRequest\x12=\n" +
	"\ateam_id\x18\x01 \x01(\v2$.com.coralogix.permissions.v1.TeamIdR\x06teamId\x12\x8e\x01\n" +
	"\x17remove_users_from_group\x18\x02 \x03(\v2W.com.coralogix.permissions.v1.RemoveUsersFromTeamGroupsRequest.RemoveUsersFromTeamGroupR\x14removeUsersFromGroup\x1a\xa3\x03\n" +
	"\x18RemoveUsersFromTeamGroup\x12D\n" +
	"\bgroup_id\x18\x01 \x01(\v2).com.coralogix.permissions.v1.TeamGroupIdR\agroupId\x12?\n" +
	"\buser_ids\x18\x02 \x03(\v2$.com.coralogix.permissions.v1.UserIdR\auserIds:\xff\x01\x9aA\xfb\x01\n" +
	"f*\x18RemoveUsersFromTeamGroup2JThis data structure represents the information associated with an API key.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/:\xc1\x02\x9aA\xbd\x02\n" +
	"\xa7\x01* RemoveUsersFromTeamGroupsRequest2\x82\x01Bulk request to remove users from multiple team groups simultaneously, efficiently managing group membership revocations at scale.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/\"\xb7\x02\n" +
	"!RemoveUsersFromTeamGroupsResponse:\x91\x02\x9aA\x8d\x02\n" +
	"x*!RemoveUsersFromTeamGroupsResponse2SResponse confirming the successful bulk removal of users from multiple team groups.*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/\"\xe0\x03\n" +
	"\x18SetTeamGroupScopeRequest\x12D\n" +
	"\bgroup_id\x18\x01 \x01(\v2).com.coralogix.permissions.v1.TeamGroupIdR\agroupId\x12O\n" +
	"\rscope_filters\x18\x02 \x01(\v2*.com.coralogix.permissions.v1.ScopeFiltersR\fscopeFilters:\xac\x02\x9aA\xa8\x02\n" +
	"\x92\x01*\x18SetTeamGroupScopeRequest2vRequest message for setting scope filters (subsystems and applications) for a team group to control access permissions*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/\"\xef\x02\n" +
	"\x19SetTeamGroupScopeResponse\x12@\n" +
	"\bscope_id\x18\x01 \x01(\v2%.com.coralogix.permissions.v1.ScopeIdR\ascopeId:\x8f\x02\x9aA\x8b\x02\n" +
	"v*\x19SetTeamGroupScopeResponse2YResponse message containing the ID of the newly created or updated scope for a team group*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/\"\xf0\x02\n" +
	"\x18GetTeamGroupScopeRequest\x12D\n" +
	"\bgroup_id\x18\x01 \x01(\v2).com.coralogix.permissions.v1.TeamGroupIdR\agroupId:\x8d\x02\x9aA\x89\x02\n" +
	"t*\x18GetTeamGroupScopeRequest2XRequest message for retrieving the current scope configuration for a specific team group*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/\"\x96\x03\n" +
	"\x19GetTeamGroupScopeResponse\x12>\n" +
	"\x05scope\x18\x01 \x01(\v2#.com.coralogix.permissions.v1.ScopeH\x00R\x05scope\x88\x01\x01:\xae\x02\x9aA\xaa\x02\n" +
	"\x94\x01*\x19GetTeamGroupScopeResponse2wResponse message containing the optional scope configuration (filters for subsystems and applications) for a team group*\x90\x01\n" +
	"\x1aFind out more about groups\x12rhttps://coralogix.com/docs/user-guides/account-management/user-management/assign-user-roles-and-scopes-via-groups/B\b\n" +
	"\x06_scope2\xc0!\n" +
	"\x1aTeamPermissionsMgmtService\x12\xac\x02\n" +
	"\fGetTeamGroup\x121.com.coralogix.permissions.v1.GetTeamGroupRequest\x1a2.com.coralogix.permissions.v1.GetTeamGroupResponse\"\xb4\x01\x9aA\x8a\x01\n" +
	"#Team Permissions Management Service\x12\x0eGet Team GroupJ\x14\n" +
	"\x03400\x12\r\n" +
	"\vBad RequestJ\x1d\n" +
	"\x03401\x12\x16\n" +
	"\x14Unauthorized requestJ\x1e\n" +
	"\x03500\x12\x17\n" +
	"\x15Internal server error\x82\xd3\xe4\x93\x02 \x12\x1e/v1/teams/groups/{group_id.id}\x12\xb8\x02\n" +
	"\x12GetTeamGroupByName\x127.com.coralogix.permissions.v1.GetTeamGroupByNameRequest\x1a8.com.coralogix.permissions.v1.GetTeamGroupByNameResponse\"\xae\x01\x9aA\x92\x01\n" +
	"#Team Permissions Management Service\x12\x16Get Team Group By NameJ\x14\n" +
	"\x03400\x12\r\n" +
	"\vBad RequestJ\x1d\n" +
	"\x03401\x12\x16\n" +
	"\x14Unauthorized requestJ\x1e\n" +
	"\x03500\x12\x17\n" +
	"\x15Internal server error\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/teams/groups\x12\xa7\x02\n" +
	"\rGetTeamGroups\x122.com.coralogix.permissions.v1.GetTeamGroupsRequest\x1a3.com.coralogix.permissions.v1.GetTeamGroupsResponse\"\xac\x01\x9aA\x8b\x01\n" +
	"#Team Permissions Management Service\x12\x0fGet Team GroupsJ\x14\n" +
	"\x03400\x12\r\n" +
	"\vBad RequestJ\x1d\n" +
	"\x03401\x12\x16\n" +
	"\x14Unauthorized requestJ\x1e\n" +
	"\x03500\x12\x17\n" +
	"\x15Internal server error\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/teams/groups/list\x12\xad\x02\n" +
	"\x0fCreateTeamGroup\x124.com.coralogix.permissions.v1.CreateTeamGroupRequest\x1a5.com.coralogix.permissions.v1.CreateTeamGroupResponse\"\xac\x01\x9aA\x8d\x01\n" +
	"#Team Permissions Management Service\x12\x11Create Team GroupJ\x14\n" +
	"\x03400\x12\r\n" +
	"\vBad RequestJ\x1d\n" +
	"\x03401\x12\x16\n" +
	"\x14Unauthorized requestJ\x1e\n" +
	"\x03500\x12\x17\n" +
	"\x15Internal server error\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/teams/groups\x12\xad\x02\n" +
	"\x0fUpdateTeamGroup\x124.com.coralogix.permissions.v1.UpdateTeamGroupRequest\x1a5.com.coralogix.permissions.v1.UpdateTeamGroupResponse\"\xac\x01\x9aA\x8d\x01\n" +
	"#Team Permissions Management Service\x12\x11Update Team GroupJ\x14\n" +
	"\x03400\x12\r\n" +
	"\vBad RequestJ\x1d\n" +
	"\x03401\x12\x16\n" +
	"\x14Unauthorized requestJ\x1e\n" +
	"\x03500\x12\x17\n" +
	"\x15Internal server error\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/v1/teams/groups\x12\xb8\x02\n" +
	"\x0fDeleteTeamGroup\x124.com.coralogix.permissions.v1.DeleteTeamGroupRequest\x1a5.com.coralogix.permissions.v1.DeleteTeamGroupResponse\"\xb7\x01\x9aA\x8d\x01\n" +
	"#Team Permissions Management Service\x12\x11Delete Team GroupJ\x14\n" +
	"\x03400\x12\r\n" +
	"\vBad RequestJ\x1d\n" +
	"\x03401\x12\x16\n" +
	"\x14Unauthorized requestJ\x1e\n" +
	"\x03500\x12\x17\n" +
	"\x15Internal server error\x82\xd3\xe4\x93\x02 *\x1e/v1/teams/groups/{group_id.id}\x12\xb6\x02\n" +
	"\rGetGroupUsers\x122.com.coralogix.permissions.v1.GetGroupUsersRequest\x1a3.com.coralogix.permissions.v1.GetGroupUsersResponse\"\xbb\x01\x9aA\x8b\x01\n" +
	"#Team Permissions Management Service\x12\x0fGet Group UsersJ\x14\n" +
	"\x03400\x12\r\n" +
	"\vBad RequestJ\x1d\n" +
	"\x03401\x12\x16\n" +
	"\x14Unauthorized requestJ\x1e\n" +
	"\x03500\x12\x17\n" +
	"\x15Internal server error\x82\xd3\xe4\x93\x02&\x12$/v1/teams/groups/{group_id.id}/users\x12\xd3\x02\n" +
	"\x13AddUsersToTeamGroup\x128.com.coralogix.permissions.v1.AddUsersToTeamGroupRequest\x1a9.com.coralogix.permissions.v1.AddUsersToTeamGroupResponse\"\xc6\x01\x9aA\x93\x01\n" +
	"#Team Permissions Management Service\x12\x17Add Users To Team GroupJ\x14\n" +
	"\x03400\x12\r\n" +
	"\vBad RequestJ\x1d\n" +
	"\x03401\x12\x16\n" +
	"\x14Unauthorized requestJ\x1e\n" +
	"\x03500\x12\x17\n" +
	"\x15Internal server error\x82\xd3\xe4\x93\x02):\x01*\"$/v1/teams/groups/{group_id.id}/users\x12\xc9\x02\n" +
	"\x14AddUsersToTeamGroups\x129.com.coralogix.permissions.v1.AddUsersToTeamGroupsRequest\x1a:.com.coralogix.permissions.v1.AddUsersToTeamGroupsResponse\"\xb9\x01\x9aA\x94\x01\n" +
	"#Team Permissions Management Service\x12\x18Add Users To Team GroupsJ\x14\n" +
	"\x03400\x12\r\n" +
	"\vBad RequestJ\x1d\n" +
	"\x03401\x12\x16\n" +
	"\x14Unauthorized requestJ\x1e\n" +
	"\x03500\x12\x17\n" +
	"\x15Internal server error\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/teams/groups/users\x12\xe4\x02\n" +
	"\x18RemoveUsersFromTeamGroup\x12=.com.coralogix.permissions.v1.RemoveUsersFromTeamGroupRequest\x1a>.com.coralogix.permissions.v1.RemoveUsersFromTeamGroupResponse\"\xc8\x01\x9aA\x98\x01\n" +
	"#Team Permissions Management Service\x12\x1cRemove Users From Team GroupJ\x14\n" +
	"\x03400\x12\r\n" +
	"\vBad RequestJ\x1d\n" +
	"\x03401\x12\x16\n" +
	"\x14Unauthorized requestJ\x1e\n" +
	"\x03500\x12\x17\n" +
	"\x15Internal server error\x82\xd3\xe4\x93\x02&*$/v1/teams/groups/{group_id.id}/users\x12\xda\x02\n" +
	"\x19RemoveUsersFromTeamGroups\x12>.com.coralogix.permissions.v1.RemoveUsersFromTeamGroupsRequest\x1a?.com.coralogix.permissions.v1.RemoveUsersFromTeamGroupsResponse\"\xbb\x01\x9aA\x99\x01\n" +
	"#Team Permissions Management Service\x12\x1dRemove Users From Team GroupsJ\x14\n" +
	"\x03400\x12\r\n" +
	"\vBad RequestJ\x1d\n" +
	"\x03401\x12\x16\n" +
	"\x14Unauthorized requestJ\x1e\n" +
	"\x03500\x12\x17\n" +
	"\x15Internal server error\x82\xd3\xe4\x93\x02\x18*\x16/v1/teams/groups/users\x12\xca\x02\n" +
	"\x11SetTeamGroupScope\x126.com.coralogix.permissions.v1.SetTeamGroupScopeRequest\x1a7.com.coralogix.permissions.v1.SetTeamGroupScopeResponse\"\xc3\x01\x9aA\x90\x01\n" +
	"#Team Permissions Management Service\x12\x14Set Team Group ScopeJ\x14\n" +
	"\x03400\x12\r\n" +
	"\vBad RequestJ\x1d\n" +
	"\x03401\x12\x16\n" +
	"\x14Unauthorized requestJ\x1e\n" +
	"\x03500\x12\x17\n" +
	"\x15Internal server error\x82\xd3\xe4\x93\x02):\x01*\"$/v1/teams/groups/{group_id.id}/scope\x12\xc7\x02\n" +
	"\x11GetTeamGroupScope\x126.com.coralogix.permissions.v1.GetTeamGroupScopeRequest\x1a7.com.coralogix.permissions.v1.GetTeamGroupScopeResponse\"\xc0\x01\x9aA\x90\x01\n" +
	"#Team Permissions Management Service\x12\x14Get Team Group ScopeJ\x14\n" +
	"\x03400\x12\r\n" +
	"\vBad RequestJ\x1d\n" +
	"\x03401\x12\x16\n" +
	"\x14Unauthorized requestJ\x1e\n" +
	"\x03500\x12\x17\n" +
	"\x15Internal server error\x82\xd3\xe4\x93\x02&\x12$/v1/teams/groups/{group_id.id}/scope\x1a=\x9aA:\n" +
	"#Team Permissions Management Service\x12\x13Manage Team Groups.b\x06proto3"

var (
	file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescOnce sync.Once
	file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescData []byte
)

func file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescGZIP() []byte {
	file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescOnce.Do(func() {
		file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDesc), len(file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDesc)))
	})
	return file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDescData
}

var file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_goTypes = []any{
	(*GetTeamGroupRequest)(nil),                                       // 0: com.coralogix.permissions.v1.GetTeamGroupRequest
	(*GetTeamGroupResponse)(nil),                                      // 1: com.coralogix.permissions.v1.GetTeamGroupResponse
	(*GetTeamGroupByNameRequest)(nil),                                 // 2: com.coralogix.permissions.v1.GetTeamGroupByNameRequest
	(*GetTeamGroupByNameResponse)(nil),                                // 3: com.coralogix.permissions.v1.GetTeamGroupByNameResponse
	(*GetTeamGroupsRequest)(nil),                                      // 4: com.coralogix.permissions.v1.GetTeamGroupsRequest
	(*GetTeamGroupsResponse)(nil),                                     // 5: com.coralogix.permissions.v1.GetTeamGroupsResponse
	(*CreateTeamGroupRequest)(nil),                                    // 6: com.coralogix.permissions.v1.CreateTeamGroupRequest
	(*CreateTeamGroupResponse)(nil),                                   // 7: com.coralogix.permissions.v1.CreateTeamGroupResponse
	(*UpdateTeamGroupRequest)(nil),                                    // 8: com.coralogix.permissions.v1.UpdateTeamGroupRequest
	(*UpdateTeamGroupResponse)(nil),                                   // 9: com.coralogix.permissions.v1.UpdateTeamGroupResponse
	(*DeleteTeamGroupRequest)(nil),                                    // 10: com.coralogix.permissions.v1.DeleteTeamGroupRequest
	(*DeleteTeamGroupResponse)(nil),                                   // 11: com.coralogix.permissions.v1.DeleteTeamGroupResponse
	(*GetGroupUsersRequest)(nil),                                      // 12: com.coralogix.permissions.v1.GetGroupUsersRequest
	(*GetGroupUsersResponse)(nil),                                     // 13: com.coralogix.permissions.v1.GetGroupUsersResponse
	(*AddUsersToTeamGroupRequest)(nil),                                // 14: com.coralogix.permissions.v1.AddUsersToTeamGroupRequest
	(*AddUsersToTeamGroupResponse)(nil),                               // 15: com.coralogix.permissions.v1.AddUsersToTeamGroupResponse
	(*AddUsersToTeamGroupsRequest)(nil),                               // 16: com.coralogix.permissions.v1.AddUsersToTeamGroupsRequest
	(*AddUsersToTeamGroupsResponse)(nil),                              // 17: com.coralogix.permissions.v1.AddUsersToTeamGroupsResponse
	(*RemoveUsersFromTeamGroupRequest)(nil),                           // 18: com.coralogix.permissions.v1.RemoveUsersFromTeamGroupRequest
	(*RemoveUsersFromTeamGroupResponse)(nil),                          // 19: com.coralogix.permissions.v1.RemoveUsersFromTeamGroupResponse
	(*RemoveUsersFromTeamGroupsRequest)(nil),                          // 20: com.coralogix.permissions.v1.RemoveUsersFromTeamGroupsRequest
	(*RemoveUsersFromTeamGroupsResponse)(nil),                         // 21: com.coralogix.permissions.v1.RemoveUsersFromTeamGroupsResponse
	(*SetTeamGroupScopeRequest)(nil),                                  // 22: com.coralogix.permissions.v1.SetTeamGroupScopeRequest
	(*SetTeamGroupScopeResponse)(nil),                                 // 23: com.coralogix.permissions.v1.SetTeamGroupScopeResponse
	(*GetTeamGroupScopeRequest)(nil),                                  // 24: com.coralogix.permissions.v1.GetTeamGroupScopeRequest
	(*GetTeamGroupScopeResponse)(nil),                                 // 25: com.coralogix.permissions.v1.GetTeamGroupScopeResponse
	(*UpdateTeamGroupRequest_RoleUpdates)(nil),                        // 26: com.coralogix.permissions.v1.UpdateTeamGroupRequest.RoleUpdates
	(*UpdateTeamGroupRequest_UserUpdates)(nil),                        // 27: com.coralogix.permissions.v1.UpdateTeamGroupRequest.UserUpdates
	(*GetGroupUsersResponse_NoMorePages)(nil),                         // 28: com.coralogix.permissions.v1.GetGroupUsersResponse.NoMorePages
	(*GetGroupUsersResponse_NextPageToken)(nil),                       // 29: com.coralogix.permissions.v1.GetGroupUsersResponse.NextPageToken
	(*AddUsersToTeamGroupsRequest_AddUsersToTeamGroup)(nil),           // 30: com.coralogix.permissions.v1.AddUsersToTeamGroupsRequest.AddUsersToTeamGroup
	(*RemoveUsersFromTeamGroupsRequest_RemoveUsersFromTeamGroup)(nil), // 31: com.coralogix.permissions.v1.RemoveUsersFromTeamGroupsRequest.RemoveUsersFromTeamGroup
	(*TeamGroupId)(nil),                                               // 32: com.coralogix.permissions.v1.TeamGroupId
	(*TeamGroup)(nil),                                                 // 33: com.coralogix.permissions.v1.TeamGroup
	(*TeamId)(nil),                                                    // 34: com.coralogix.permissions.v1.TeamId
	(*RoleId)(nil),                                                    // 35: com.coralogix.permissions.v1.RoleId
	(*UserId)(nil),                                                    // 36: com.coralogix.permissions.v1.UserId
	(*ScopeFilters)(nil),                                              // 37: com.coralogix.permissions.v1.ScopeFilters
	(GroupType)(0),                                                    // 38: com.coralogix.permissions.v1.GroupType
	(*User)(nil),                                                      // 39: com.coralogix.permissions.v1.User
	(*ScopeId)(nil),                                                   // 40: com.coralogix.permissions.v1.ScopeId
	(*Scope)(nil),                                                     // 41: com.coralogix.permissions.v1.Scope
}
var file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_depIdxs = []int32{
	32, // 0: com.coralogix.permissions.v1.GetTeamGroupRequest.group_id:type_name -> com.coralogix.permissions.v1.TeamGroupId
	33, // 1: com.coralogix.permissions.v1.GetTeamGroupResponse.group:type_name -> com.coralogix.permissions.v1.TeamGroup
	33, // 2: com.coralogix.permissions.v1.GetTeamGroupByNameResponse.group:type_name -> com.coralogix.permissions.v1.TeamGroup
	34, // 3: com.coralogix.permissions.v1.GetTeamGroupsRequest.team_id:type_name -> com.coralogix.permissions.v1.TeamId
	33, // 4: com.coralogix.permissions.v1.GetTeamGroupsResponse.groups:type_name -> com.coralogix.permissions.v1.TeamGroup
	34, // 5: com.coralogix.permissions.v1.CreateTeamGroupRequest.team_id:type_name -> com.coralogix.permissions.v1.TeamId
	35, // 6: com.coralogix.permissions.v1.CreateTeamGroupRequest.role_ids:type_name -> com.coralogix.permissions.v1.RoleId
	36, // 7: com.coralogix.permissions.v1.CreateTeamGroupRequest.user_ids:type_name -> com.coralogix.permissions.v1.UserId
	37, // 8: com.coralogix.permissions.v1.CreateTeamGroupRequest.scope_filters:type_name -> com.coralogix.permissions.v1.ScopeFilters
	38, // 9: com.coralogix.permissions.v1.CreateTeamGroupRequest.group_type:type_name -> com.coralogix.permissions.v1.GroupType
	32, // 10: com.coralogix.permissions.v1.CreateTeamGroupResponse.group_id:type_name -> com.coralogix.permissions.v1.TeamGroupId
	32, // 11: com.coralogix.permissions.v1.UpdateTeamGroupRequest.group_id:type_name -> com.coralogix.permissions.v1.TeamGroupId
	26, // 12: com.coralogix.permissions.v1.UpdateTeamGroupRequest.role_updates:type_name -> com.coralogix.permissions.v1.UpdateTeamGroupRequest.RoleUpdates
	27, // 13: com.coralogix.permissions.v1.UpdateTeamGroupRequest.user_updates:type_name -> com.coralogix.permissions.v1.UpdateTeamGroupRequest.UserUpdates
	37, // 14: com.coralogix.permissions.v1.UpdateTeamGroupRequest.scope_filters:type_name -> com.coralogix.permissions.v1.ScopeFilters
	38, // 15: com.coralogix.permissions.v1.UpdateTeamGroupRequest.group_type:type_name -> com.coralogix.permissions.v1.GroupType
	32, // 16: com.coralogix.permissions.v1.DeleteTeamGroupRequest.group_id:type_name -> com.coralogix.permissions.v1.TeamGroupId
	32, // 17: com.coralogix.permissions.v1.GetGroupUsersRequest.group_id:type_name -> com.coralogix.permissions.v1.TeamGroupId
	39, // 18: com.coralogix.permissions.v1.GetGroupUsersResponse.users:type_name -> com.coralogix.permissions.v1.User
	28, // 19: com.coralogix.permissions.v1.GetGroupUsersResponse.no_more_pages:type_name -> com.coralogix.permissions.v1.GetGroupUsersResponse.NoMorePages
	29, // 20: com.coralogix.permissions.v1.GetGroupUsersResponse.token:type_name -> com.coralogix.permissions.v1.GetGroupUsersResponse.NextPageToken
	32, // 21: com.coralogix.permissions.v1.AddUsersToTeamGroupRequest.group_id:type_name -> com.coralogix.permissions.v1.TeamGroupId
	36, // 22: com.coralogix.permissions.v1.AddUsersToTeamGroupRequest.user_ids:type_name -> com.coralogix.permissions.v1.UserId
	34, // 23: com.coralogix.permissions.v1.AddUsersToTeamGroupResponse.team_id:type_name -> com.coralogix.permissions.v1.TeamId
	34, // 24: com.coralogix.permissions.v1.AddUsersToTeamGroupsRequest.team_id:type_name -> com.coralogix.permissions.v1.TeamId
	30, // 25: com.coralogix.permissions.v1.AddUsersToTeamGroupsRequest.add_users_to_group:type_name -> com.coralogix.permissions.v1.AddUsersToTeamGroupsRequest.AddUsersToTeamGroup
	32, // 26: com.coralogix.permissions.v1.RemoveUsersFromTeamGroupRequest.group_id:type_name -> com.coralogix.permissions.v1.TeamGroupId
	36, // 27: com.coralogix.permissions.v1.RemoveUsersFromTeamGroupRequest.user_ids:type_name -> com.coralogix.permissions.v1.UserId
	34, // 28: com.coralogix.permissions.v1.RemoveUsersFromTeamGroupsRequest.team_id:type_name -> com.coralogix.permissions.v1.TeamId
	31, // 29: com.coralogix.permissions.v1.RemoveUsersFromTeamGroupsRequest.remove_users_from_group:type_name -> com.coralogix.permissions.v1.RemoveUsersFromTeamGroupsRequest.RemoveUsersFromTeamGroup
	32, // 30: com.coralogix.permissions.v1.SetTeamGroupScopeRequest.group_id:type_name -> com.coralogix.permissions.v1.TeamGroupId
	37, // 31: com.coralogix.permissions.v1.SetTeamGroupScopeRequest.scope_filters:type_name -> com.coralogix.permissions.v1.ScopeFilters
	40, // 32: com.coralogix.permissions.v1.SetTeamGroupScopeResponse.scope_id:type_name -> com.coralogix.permissions.v1.ScopeId
	32, // 33: com.coralogix.permissions.v1.GetTeamGroupScopeRequest.group_id:type_name -> com.coralogix.permissions.v1.TeamGroupId
	41, // 34: com.coralogix.permissions.v1.GetTeamGroupScopeResponse.scope:type_name -> com.coralogix.permissions.v1.Scope
	35, // 35: com.coralogix.permissions.v1.UpdateTeamGroupRequest.RoleUpdates.role_ids:type_name -> com.coralogix.permissions.v1.RoleId
	36, // 36: com.coralogix.permissions.v1.UpdateTeamGroupRequest.UserUpdates.user_ids:type_name -> com.coralogix.permissions.v1.UserId
	32, // 37: com.coralogix.permissions.v1.AddUsersToTeamGroupsRequest.AddUsersToTeamGroup.group_id:type_name -> com.coralogix.permissions.v1.TeamGroupId
	36, // 38: com.coralogix.permissions.v1.AddUsersToTeamGroupsRequest.AddUsersToTeamGroup.user_ids:type_name -> com.coralogix.permissions.v1.UserId
	32, // 39: com.coralogix.permissions.v1.RemoveUsersFromTeamGroupsRequest.RemoveUsersFromTeamGroup.group_id:type_name -> com.coralogix.permissions.v1.TeamGroupId
	36, // 40: com.coralogix.permissions.v1.RemoveUsersFromTeamGroupsRequest.RemoveUsersFromTeamGroup.user_ids:type_name -> com.coralogix.permissions.v1.UserId
	0,  // 41: com.coralogix.permissions.v1.TeamPermissionsMgmtService.GetTeamGroup:input_type -> com.coralogix.permissions.v1.GetTeamGroupRequest
	2,  // 42: com.coralogix.permissions.v1.TeamPermissionsMgmtService.GetTeamGroupByName:input_type -> com.coralogix.permissions.v1.GetTeamGroupByNameRequest
	4,  // 43: com.coralogix.permissions.v1.TeamPermissionsMgmtService.GetTeamGroups:input_type -> com.coralogix.permissions.v1.GetTeamGroupsRequest
	6,  // 44: com.coralogix.permissions.v1.TeamPermissionsMgmtService.CreateTeamGroup:input_type -> com.coralogix.permissions.v1.CreateTeamGroupRequest
	8,  // 45: com.coralogix.permissions.v1.TeamPermissionsMgmtService.UpdateTeamGroup:input_type -> com.coralogix.permissions.v1.UpdateTeamGroupRequest
	10, // 46: com.coralogix.permissions.v1.TeamPermissionsMgmtService.DeleteTeamGroup:input_type -> com.coralogix.permissions.v1.DeleteTeamGroupRequest
	12, // 47: com.coralogix.permissions.v1.TeamPermissionsMgmtService.GetGroupUsers:input_type -> com.coralogix.permissions.v1.GetGroupUsersRequest
	14, // 48: com.coralogix.permissions.v1.TeamPermissionsMgmtService.AddUsersToTeamGroup:input_type -> com.coralogix.permissions.v1.AddUsersToTeamGroupRequest
	16, // 49: com.coralogix.permissions.v1.TeamPermissionsMgmtService.AddUsersToTeamGroups:input_type -> com.coralogix.permissions.v1.AddUsersToTeamGroupsRequest
	18, // 50: com.coralogix.permissions.v1.TeamPermissionsMgmtService.RemoveUsersFromTeamGroup:input_type -> com.coralogix.permissions.v1.RemoveUsersFromTeamGroupRequest
	20, // 51: com.coralogix.permissions.v1.TeamPermissionsMgmtService.RemoveUsersFromTeamGroups:input_type -> com.coralogix.permissions.v1.RemoveUsersFromTeamGroupsRequest
	22, // 52: com.coralogix.permissions.v1.TeamPermissionsMgmtService.SetTeamGroupScope:input_type -> com.coralogix.permissions.v1.SetTeamGroupScopeRequest
	24, // 53: com.coralogix.permissions.v1.TeamPermissionsMgmtService.GetTeamGroupScope:input_type -> com.coralogix.permissions.v1.GetTeamGroupScopeRequest
	1,  // 54: com.coralogix.permissions.v1.TeamPermissionsMgmtService.GetTeamGroup:output_type -> com.coralogix.permissions.v1.GetTeamGroupResponse
	3,  // 55: com.coralogix.permissions.v1.TeamPermissionsMgmtService.GetTeamGroupByName:output_type -> com.coralogix.permissions.v1.GetTeamGroupByNameResponse
	5,  // 56: com.coralogix.permissions.v1.TeamPermissionsMgmtService.GetTeamGroups:output_type -> com.coralogix.permissions.v1.GetTeamGroupsResponse
	7,  // 57: com.coralogix.permissions.v1.TeamPermissionsMgmtService.CreateTeamGroup:output_type -> com.coralogix.permissions.v1.CreateTeamGroupResponse
	9,  // 58: com.coralogix.permissions.v1.TeamPermissionsMgmtService.UpdateTeamGroup:output_type -> com.coralogix.permissions.v1.UpdateTeamGroupResponse
	11, // 59: com.coralogix.permissions.v1.TeamPermissionsMgmtService.DeleteTeamGroup:output_type -> com.coralogix.permissions.v1.DeleteTeamGroupResponse
	13, // 60: com.coralogix.permissions.v1.TeamPermissionsMgmtService.GetGroupUsers:output_type -> com.coralogix.permissions.v1.GetGroupUsersResponse
	15, // 61: com.coralogix.permissions.v1.TeamPermissionsMgmtService.AddUsersToTeamGroup:output_type -> com.coralogix.permissions.v1.AddUsersToTeamGroupResponse
	17, // 62: com.coralogix.permissions.v1.TeamPermissionsMgmtService.AddUsersToTeamGroups:output_type -> com.coralogix.permissions.v1.AddUsersToTeamGroupsResponse
	19, // 63: com.coralogix.permissions.v1.TeamPermissionsMgmtService.RemoveUsersFromTeamGroup:output_type -> com.coralogix.permissions.v1.RemoveUsersFromTeamGroupResponse
	21, // 64: com.coralogix.permissions.v1.TeamPermissionsMgmtService.RemoveUsersFromTeamGroups:output_type -> com.coralogix.permissions.v1.RemoveUsersFromTeamGroupsResponse
	23, // 65: com.coralogix.permissions.v1.TeamPermissionsMgmtService.SetTeamGroupScope:output_type -> com.coralogix.permissions.v1.SetTeamGroupScopeResponse
	25, // 66: com.coralogix.permissions.v1.TeamPermissionsMgmtService.GetTeamGroupScope:output_type -> com.coralogix.permissions.v1.GetTeamGroupScopeResponse
	54, // [54:67] is the sub-list for method output_type
	41, // [41:54] is the sub-list for method input_type
	41, // [41:41] is the sub-list for extension type_name
	41, // [41:41] is the sub-list for extension extendee
	0,  // [0:41] is the sub-list for field type_name
}

func init() { file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_init() }
func file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_init() {
	if File_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto != nil {
		return
	}
	file_com_coralogix_permissions_v1_common_proto_init()
	file_com_coralogix_permissions_v1_permissions_mgmt_proto_init()
	file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[8].OneofWrappers = []any{}
	file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[12].OneofWrappers = []any{}
	file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[13].OneofWrappers = []any{
		(*GetGroupUsersResponse_NoMorePages_)(nil),
		(*GetGroupUsersResponse_Token)(nil),
	}
	file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes[25].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDesc), len(file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_goTypes,
		DependencyIndexes: file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_depIdxs,
		MessageInfos:      file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_msgTypes,
	}.Build()
	File_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto = out.File
	file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_goTypes = nil
	file_com_coralogix_permissions_v1_team_permissions_mgmt_service_proto_depIdxs = nil
}
