{
  "openapi": "3.1.0",
  "info": {
    "title": "",
    "version": "1.0.0"
  },
  "paths": {
    "/aaa/team-scopes/v1": {
      "get": {
        "description": "Returns a data access scope by ID.",
        "operationId": "ScopesService_GetTeamScopesByIds",
        "parameters": [
          {
            "description": "List of team scope identifiers to retrieve.",
            "in": "query",
            "name": "ids",
            "required": true,
            "schema": {
              "description": "List of team scope identifiers to retrieve.",
              "items": {
                "description": "List of team scope identifiers to retrieve.",
                "examples": [
                  "60c82be2-413f-4b8e-8201-7f5c51e2ef2b"
                ],
                "minLength": 0,
                "type": "string"
              },
              "minItems": 0,
              "type": "array"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetScopesResponse"
                }
              }
            },
            "description": ""
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Bad Request"
          },
          "401": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Unauthorized request"
          },
          "500": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Internal server error"
          }
        },
        "summary": "Get Team Scopes By Ids",
        "tags": [
          "Scopes Service"
        ]
      },
      "put": {
        "description": "Updates an existing data access scope.",
        "operationId": "ScopesService_UpdateScope",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "description": "This data structure represents a request to update a scope",
                "properties": {
                  "defaultExpression": {
                    "description": "The default expression.",
                    "examples": [
                      "<v1>true"
                    ],
                    "minLength": 0,
                    "type": "string"
                  },
                  "description": {
                    "description": "Human-readable description.",
                    "examples": [
                      "The best scope"
                    ],
                    "minLength": 0,
                    "type": "string",
                    "x-coralogix-presence": true
                  },
                  "displayName": {
                    "description": "The display name.",
                    "examples": [
                      "my-scope"
                    ],
                    "minLength": 0,
                    "type": "string"
                  },
                  "filters": {
                    "description": "List of filters.",
                    "items": {
                      "$ref": "#/components/schemas/scopes.v1.Filter"
                    },
                    "minItems": 0,
                    "type": "array"
                  },
                  "id": {
                    "description": "Unique identifier.",
                    "examples": [
                      "60c82be2-413f-4b8e-8201-7f5c51e2ef2b"
                    ],
                    "minLength": 0,
                    "type": "string"
                  }
                },
                "required": [
                  "id",
                  "displayName",
                  "filters",
                  "defaultExpression"
                ],
                "title": "Update Scope Request",
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateScopeResponse"
                }
              }
            },
            "description": ""
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Bad Request"
          },
          "401": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Unauthorized request"
          },
          "500": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Internal server error"
          }
        },
        "summary": "Update Scope",
        "tags": [
          "Scopes Service"
        ]
      },
      "post": {
        "description": "Creates a new data access scope.",
        "operationId": "ScopesService_CreateScope",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "description": "This data structure represents a request to create a scope",
                "properties": {
                  "defaultExpression": {
                    "description": "The default expression.",
                    "examples": [
                      "<v1>true"
                    ],
                    "minLength": 0,
                    "type": "string"
                  },
                  "description": {
                    "description": "Human-readable description.",
                    "examples": [
                      "The best scope"
                    ],
                    "minLength": 0,
                    "type": "string",
                    "x-coralogix-presence": true
                  },
                  "displayName": {
                    "description": "The display name.",
                    "examples": [
                      "my-scope"
                    ],
                    "minLength": 0,
                    "type": "string"
                  },
                  "filters": {
                    "description": "List of filters.",
                    "items": {
                      "$ref": "#/components/schemas/scopes.v1.Filter"
                    },
                    "minItems": 0,
                    "type": "array"
                  }
                },
                "required": [
                  "displayName",
                  "filters"
                ],
                "title": "Create Scope Request",
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CreateScopeResponse"
                }
              }
            },
            "description": ""
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Bad Request"
          },
          "401": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Unauthorized request"
          },
          "500": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Internal server error"
          }
        },
        "summary": "Create Scope",
        "tags": [
          "Scopes Service"
        ]
      }
    },
    "/aaa/team-scopes/v1/all/list": {
      "get": {
        "description": "Returns all data access scopes for the team.",
        "operationId": "ScopesService_GetTeamScopes",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetScopesResponse"
                }
              }
            },
            "description": ""
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Bad Request"
          },
          "401": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Unauthorized request"
          },
          "500": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Internal server error"
          }
        },
        "summary": "Get Team Scopes",
        "tags": [
          "Scopes Service"
        ]
      }
    },
    "/aaa/team-scopes/v1/{id}": {
      "delete": {
        "description": "Deletes the data access scope with the specified ID.",
        "operationId": "ScopesService_DeleteScope",
        "parameters": [
          {
            "description": "Unique identifier.",
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "description": "Unique identifier.",
              "examples": [
                "60c82be2-413f-4b8e-8201-7f5c51e2ef2b"
              ],
              "minLength": 0,
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeleteScopeResponse"
                }
              }
            },
            "description": ""
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Bad Request"
          },
          "401": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Unauthorized request"
          },
          "500": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Internal server error"
          }
        },
        "summary": "Delete Scope",
        "tags": [
          "Scopes Service"
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "CreateScopeResponse": {
        "title": "Create Scope Response",
        "required": [
          "scope"
        ],
        "type": "object",
        "properties": {
          "scope": {
            "$ref": "#/components/schemas/v1.Scope"
          }
        },
        "description": "This data structure represents a response to create a scope",
        "externalDocs": {
          "description": "Find out more about scopes",
          "url": "https://coralogix.com/docs/user-guides/account-management/user-management/scopes/"
        }
      },
      "DeleteScopeResponse": {
        "type": "object",
        "additionalProperties": false,
        "description": "Response returned after successfully deleting a data access scope.",
        "externalDocs": {
          "url": ""
        }
      },
      "Error": {
        "type": "object",
        "properties": {
          "code": {
            "maximum": 599,
            "minimum": 100,
            "type": "integer",
            "description": "HTTP status code of the error (for example 400, 404, 500).",
            "format": "int32"
          },
          "message": {
            "maxLength": 4096,
            "minLength": 0,
            "pattern": "^[\\s\\S]*$",
            "type": "string",
            "description": "Human-readable description of the error."
          }
        },
        "description": "Standard error response body returned for a failed request."
      },
      "FilterPathAndValues": {
        "title": "FilterPathAndValues",
        "required": [
          "path"
        ],
        "type": "object",
        "oneOf": [
          {
            "required": [
              "multipleValues"
            ],
            "type": "object"
          },
          {
            "required": [
              "filters"
            ],
            "type": "object"
          }
        ],
        "properties": {
          "filters": {
            "allOf": [
              {
                "$ref": "#/components/schemas/Filters"
              }
            ],
            "description": "The filters."
          },
          "multipleValues": {
            "$ref": "#/components/schemas/MultipleValues"
          },
          "path": {
            "minLength": 0,
            "type": "string",
            "examples": [
              "test"
            ]
          }
        },
        "description": "This data structure represents a filter path and values",
        "externalDocs": {
          "url": ""
        }
      },
      "Filters": {
        "title": "Filters",
        "required": [
          "pathAndValues"
        ],
        "type": "object",
        "properties": {
          "operator": {
            "allOf": [
              {
                "$ref": "#/components/schemas/v3.FilterOperator"
              }
            ],
            "examples": [
              "FILTER_OPERATOR_OR"
            ]
          },
          "pathAndValues": {
            "minItems": 0,
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/FilterPathAndValues"
            }
          }
        },
        "description": "This data structure represents a filter",
        "externalDocs": {
          "url": ""
        }
      },
      "GetScopesResponse": {
        "title": "Get Scopes Response",
        "required": [
          "scopes"
        ],
        "type": "object",
        "properties": {
          "scopes": {
            "minItems": 0,
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/v1.Scope"
            },
            "description": "List of scopes."
          }
        },
        "description": "This data structure represents a response to get scopes",
        "externalDocs": {
          "description": "Find out more about scopes",
          "url": "https://coralogix.com/docs/user-guides/account-management/user-management/scopes/"
        }
      },
      "MultipleValues": {
        "type": "object",
        "properties": {
          "matcher": {
            "$ref": "#/components/schemas/events.v3.FilterMatcher"
          },
          "values": {
            "minItems": 0,
            "type": "array",
            "items": {
              "minLength": 0,
              "type": "string"
            }
          }
        }
      },
      "UpdateScopeResponse": {
        "title": "Update Scope Response",
        "required": [
          "scope"
        ],
        "type": "object",
        "properties": {
          "scope": {
            "$ref": "#/components/schemas/v1.Scope"
          }
        },
        "description": "This data structure represents a response to update a scope",
        "externalDocs": {
          "description": "Find out more about scopes",
          "url": "https://coralogix.com/docs/user-guides/account-management/user-management/scopes/"
        }
      },
      "events.v3.FilterMatcher": {
        "enum": [
          "FILTER_MATCHER_TEXT_OR_UNSPECIFIED",
          "FILTER_MATCHER_REGEXP"
        ],
        "type": "string"
      },
      "scopes.v1.Filter": {
        "title": "Filter",
        "type": "object",
        "properties": {
          "entityType": {
            "$ref": "#/components/schemas/v1.EntityType"
          },
          "expression": {
            "minLength": 0,
            "type": "string",
            "description": "The expression.",
            "examples": [
              "<v1>true"
            ]
          }
        },
        "description": "This data structure represents a filter",
        "externalDocs": {
          "description": "Find out more about scopes",
          "url": "https://coralogix.com/docs/user-guides/account-management/user-management/scopes/"
        }
      },
      "v1.EntityType": {
        "enum": [
          "ENTITY_TYPE_UNSPECIFIED",
          "ENTITY_TYPE_LOGS",
          "ENTITY_TYPE_SPANS"
        ],
        "type": "string",
        "description": "Entity type."
      },
      "v1.Scope": {
        "title": "Scope",
        "type": "object",
        "properties": {
          "defaultExpression": {
            "minLength": 0,
            "type": "string",
            "description": "The default expression.",
            "examples": [
              "<v1>true"
            ]
          },
          "description": {
            "description": "Human-readable description.",
            "examples": [
              "The best scope"
            ],
            "minLength": 0,
            "type": "string",
            "x-coralogix-presence": true
          },
          "displayName": {
            "minLength": 0,
            "type": "string",
            "description": "The display name.",
            "examples": [
              "my-scope"
            ]
          },
          "filters": {
            "minItems": 0,
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/scopes.v1.Filter"
            },
            "description": "List of filters."
          },
          "id": {
            "minLength": 0,
            "type": "string",
            "description": "Unique identifier.",
            "examples": [
              "60c82be2-413f-4b8e-8201-7f5c51e2ef2b"
            ]
          },
          "teamId": {
            "type": "integer",
            "description": "Team identifier.",
            "format": "int32",
            "examples": [
              1234
            ]
          }
        },
        "description": "This data structure represents a scope",
        "externalDocs": {
          "description": "Find out more about scopes",
          "url": "https://coralogix.com/docs/user-guides/account-management/user-management/scopes/"
        }
      },
      "v3.FilterOperator": {
        "enum": [
          "FILTER_OPERATOR_AND_OR_UNSPECIFIED",
          "FILTER_OPERATOR_OR"
        ],
        "type": "string",
        "description": "Filter operator."
      }
    }
  }
}