// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: com/coralogixapis/slo/v1/slo.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SloTimeFrame int32

const (
	SloTimeFrame_SLO_TIME_FRAME_UNSPECIFIED SloTimeFrame = 0
	SloTimeFrame_SLO_TIME_FRAME_7_DAYS      SloTimeFrame = 1
	SloTimeFrame_SLO_TIME_FRAME_14_DAYS     SloTimeFrame = 2
	SloTimeFrame_SLO_TIME_FRAME_21_DAYS     SloTimeFrame = 3
	SloTimeFrame_SLO_TIME_FRAME_28_DAYS     SloTimeFrame = 4
	SloTimeFrame_SLO_TIME_FRAME_90_DAYS     SloTimeFrame = 5
)

// Enum value maps for SloTimeFrame.
var (
	SloTimeFrame_name = map[int32]string{
		0: "SLO_TIME_FRAME_UNSPECIFIED",
		1: "SLO_TIME_FRAME_7_DAYS",
		2: "SLO_TIME_FRAME_14_DAYS",
		3: "SLO_TIME_FRAME_21_DAYS",
		4: "SLO_TIME_FRAME_28_DAYS",
		5: "SLO_TIME_FRAME_90_DAYS",
	}
	SloTimeFrame_value = map[string]int32{
		"SLO_TIME_FRAME_UNSPECIFIED": 0,
		"SLO_TIME_FRAME_7_DAYS":      1,
		"SLO_TIME_FRAME_14_DAYS":     2,
		"SLO_TIME_FRAME_21_DAYS":     3,
		"SLO_TIME_FRAME_28_DAYS":     4,
		"SLO_TIME_FRAME_90_DAYS":     5,
	}
)

func (x SloTimeFrame) Enum() *SloTimeFrame {
	p := new(SloTimeFrame)
	*p = x
	return p
}

func (x SloTimeFrame) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SloTimeFrame) Descriptor() protoreflect.EnumDescriptor {
	return file_com_coralogixapis_slo_v1_slo_proto_enumTypes[0].Descriptor()
}

func (SloTimeFrame) Type() protoreflect.EnumType {
	return &file_com_coralogixapis_slo_v1_slo_proto_enumTypes[0]
}

func (x SloTimeFrame) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SloTimeFrame.Descriptor instead.
func (SloTimeFrame) EnumDescriptor() ([]byte, []int) {
	return file_com_coralogixapis_slo_v1_slo_proto_rawDescGZIP(), []int{0}
}

type SloConstantFilterField int32

const (
	SloConstantFilterField_SLO_CONST_FILTER_FIELD_UNSPECIFIED SloConstantFilterField = 0
	SloConstantFilterField_SLO_CONST_FILTER_FIELD_USER_NAME   SloConstantFilterField = 1
)

// Enum value maps for SloConstantFilterField.
var (
	SloConstantFilterField_name = map[int32]string{
		0: "SLO_CONST_FILTER_FIELD_UNSPECIFIED",
		1: "SLO_CONST_FILTER_FIELD_USER_NAME",
	}
	SloConstantFilterField_value = map[string]int32{
		"SLO_CONST_FILTER_FIELD_UNSPECIFIED": 0,
		"SLO_CONST_FILTER_FIELD_USER_NAME":   1,
	}
)

func (x SloConstantFilterField) Enum() *SloConstantFilterField {
	p := new(SloConstantFilterField)
	*p = x
	return p
}

func (x SloConstantFilterField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SloConstantFilterField) Descriptor() protoreflect.EnumDescriptor {
	return file_com_coralogixapis_slo_v1_slo_proto_enumTypes[1].Descriptor()
}

func (SloConstantFilterField) Type() protoreflect.EnumType {
	return &file_com_coralogixapis_slo_v1_slo_proto_enumTypes[1]
}

func (x SloConstantFilterField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SloConstantFilterField.Descriptor instead.
func (SloConstantFilterField) EnumDescriptor() ([]byte, []int) {
	return file_com_coralogixapis_slo_v1_slo_proto_rawDescGZIP(), []int{1}
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_com_coralogixapis_slo_v1_slo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogixapis_slo_v1_slo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_com_coralogixapis_slo_v1_slo_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type MetricSli struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodEvents    *Metric                `protobuf:"bytes,1,opt,name=good_events,json=goodEvents,proto3" json:"good_events,omitempty"`
	TotalEvents   *Metric                `protobuf:"bytes,2,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	GroupByLabels []string               `protobuf:"bytes,3,rep,name=group_by_labels,json=groupByLabels,proto3" json:"group_by_labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSli) Reset() {
	*x = MetricSli{}
	mi := &file_com_coralogixapis_slo_v1_slo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSli) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSli) ProtoMessage() {}

func (x *MetricSli) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogixapis_slo_v1_slo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSli.ProtoReflect.Descriptor instead.
func (*MetricSli) Descriptor() ([]byte, []int) {
	return file_com_coralogixapis_slo_v1_slo_proto_rawDescGZIP(), []int{1}
}

func (x *MetricSli) GetGoodEvents() *Metric {
	if x != nil {
		return x.GoodEvents
	}
	return nil
}

func (x *MetricSli) GetTotalEvents() *Metric {
	if x != nil {
		return x.TotalEvents
	}
	return nil
}

func (x *MetricSli) GetGroupByLabels() []string {
	if x != nil {
		return x.GroupByLabels
	}
	return nil
}

type Slo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Creator     string                 `protobuf:"bytes,4,opt,name=creator,proto3" json:"creator,omitempty"`
	Labels      map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Sli:
	//
	//	*Slo_MetricSli
	Sli isSlo_Sli `protobuf_oneof:"sli"`
	// Types that are valid to be assigned to Window:
	//
	//	*Slo_SloTimeFrame
	Window                    isSlo_Window           `protobuf_oneof:"window"`
	TargetThresholdPercentage int32                  `protobuf:"varint,8,opt,name=target_threshold_percentage,json=targetThresholdPercentage,proto3" json:"target_threshold_percentage,omitempty"`
	CreateTime                *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime                *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Slo) Reset() {
	*x = Slo{}
	mi := &file_com_coralogixapis_slo_v1_slo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slo) ProtoMessage() {}

func (x *Slo) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogixapis_slo_v1_slo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slo.ProtoReflect.Descriptor instead.
func (*Slo) Descriptor() ([]byte, []int) {
	return file_com_coralogixapis_slo_v1_slo_proto_rawDescGZIP(), []int{2}
}

func (x *Slo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Slo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Slo) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Slo) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *Slo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Slo) GetSli() isSlo_Sli {
	if x != nil {
		return x.Sli
	}
	return nil
}

func (x *Slo) GetMetricSli() *MetricSli {
	if x != nil {
		if x, ok := x.Sli.(*Slo_MetricSli); ok {
			return x.MetricSli
		}
	}
	return nil
}

func (x *Slo) GetWindow() isSlo_Window {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *Slo) GetSloTimeFrame() SloTimeFrame {
	if x != nil {
		if x, ok := x.Window.(*Slo_SloTimeFrame); ok {
			return x.SloTimeFrame
		}
	}
	return SloTimeFrame_SLO_TIME_FRAME_UNSPECIFIED
}

func (x *Slo) GetTargetThresholdPercentage() int32 {
	if x != nil {
		return x.TargetThresholdPercentage
	}
	return 0
}

func (x *Slo) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Slo) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type isSlo_Sli interface {
	isSlo_Sli()
}

type Slo_MetricSli struct {
	MetricSli *MetricSli `protobuf:"bytes,6,opt,name=metric_sli,json=metricSli,proto3,oneof"`
}

func (*Slo_MetricSli) isSlo_Sli() {}

type isSlo_Window interface {
	isSlo_Window()
}

type Slo_SloTimeFrame struct {
	SloTimeFrame SloTimeFrame `protobuf:"varint,7,opt,name=slo_time_frame,json=sloTimeFrame,proto3,enum=com.coralogixapis.slo.v1.SloTimeFrame,oneof"` //    google.protobuf.Duration duration = 11;
}

func (*Slo_SloTimeFrame) isSlo_Window() {}

type SloFilterField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Field:
	//
	//	*SloFilterField_ConstFilter
	//	*SloFilterField_LabelName
	Field         isSloFilterField_Field `protobuf_oneof:"field"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SloFilterField) Reset() {
	*x = SloFilterField{}
	mi := &file_com_coralogixapis_slo_v1_slo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SloFilterField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SloFilterField) ProtoMessage() {}

func (x *SloFilterField) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogixapis_slo_v1_slo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SloFilterField.ProtoReflect.Descriptor instead.
func (*SloFilterField) Descriptor() ([]byte, []int) {
	return file_com_coralogixapis_slo_v1_slo_proto_rawDescGZIP(), []int{3}
}

func (x *SloFilterField) GetField() isSloFilterField_Field {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *SloFilterField) GetConstFilter() SloConstantFilterField {
	if x != nil {
		if x, ok := x.Field.(*SloFilterField_ConstFilter); ok {
			return x.ConstFilter
		}
	}
	return SloConstantFilterField_SLO_CONST_FILTER_FIELD_UNSPECIFIED
}

func (x *SloFilterField) GetLabelName() string {
	if x != nil {
		if x, ok := x.Field.(*SloFilterField_LabelName); ok {
			return x.LabelName
		}
	}
	return ""
}

type isSloFilterField_Field interface {
	isSloFilterField_Field()
}

type SloFilterField_ConstFilter struct {
	ConstFilter SloConstantFilterField `protobuf:"varint,1,opt,name=const_filter,json=constFilter,proto3,enum=com.coralogixapis.slo.v1.SloConstantFilterField,oneof"`
}

type SloFilterField_LabelName struct {
	LabelName string `protobuf:"bytes,2,opt,name=label_name,json=labelName,proto3,oneof"`
}

func (*SloFilterField_ConstFilter) isSloFilterField_Field() {}

func (*SloFilterField_LabelName) isSloFilterField_Field() {}

type IsFilterPredicate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Is            []string               `protobuf:"bytes,1,rep,name=is,proto3" json:"is,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFilterPredicate) Reset() {
	*x = IsFilterPredicate{}
	mi := &file_com_coralogixapis_slo_v1_slo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFilterPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFilterPredicate) ProtoMessage() {}

func (x *IsFilterPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogixapis_slo_v1_slo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFilterPredicate.ProtoReflect.Descriptor instead.
func (*IsFilterPredicate) Descriptor() ([]byte, []int) {
	return file_com_coralogixapis_slo_v1_slo_proto_rawDescGZIP(), []int{4}
}

func (x *IsFilterPredicate) GetIs() []string {
	if x != nil {
		return x.Is
	}
	return nil
}

type SloFilterPredicate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Predicate:
	//
	//	*SloFilterPredicate_Is
	Predicate     isSloFilterPredicate_Predicate `protobuf_oneof:"predicate"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SloFilterPredicate) Reset() {
	*x = SloFilterPredicate{}
	mi := &file_com_coralogixapis_slo_v1_slo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SloFilterPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SloFilterPredicate) ProtoMessage() {}

func (x *SloFilterPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogixapis_slo_v1_slo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SloFilterPredicate.ProtoReflect.Descriptor instead.
func (*SloFilterPredicate) Descriptor() ([]byte, []int) {
	return file_com_coralogixapis_slo_v1_slo_proto_rawDescGZIP(), []int{5}
}

func (x *SloFilterPredicate) GetPredicate() isSloFilterPredicate_Predicate {
	if x != nil {
		return x.Predicate
	}
	return nil
}

func (x *SloFilterPredicate) GetIs() *IsFilterPredicate {
	if x != nil {
		if x, ok := x.Predicate.(*SloFilterPredicate_Is); ok {
			return x.Is
		}
	}
	return nil
}

type isSloFilterPredicate_Predicate interface {
	isSloFilterPredicate_Predicate()
}

type SloFilterPredicate_Is struct {
	Is *IsFilterPredicate `protobuf:"bytes,1,opt,name=is,proto3,oneof"`
}

func (*SloFilterPredicate_Is) isSloFilterPredicate_Predicate() {}

type SloFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         *SloFilterField        `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Predicate     *SloFilterPredicate    `protobuf:"bytes,2,opt,name=predicate,proto3" json:"predicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SloFilter) Reset() {
	*x = SloFilter{}
	mi := &file_com_coralogixapis_slo_v1_slo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SloFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SloFilter) ProtoMessage() {}

func (x *SloFilter) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogixapis_slo_v1_slo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SloFilter.ProtoReflect.Descriptor instead.
func (*SloFilter) Descriptor() ([]byte, []int) {
	return file_com_coralogixapis_slo_v1_slo_proto_rawDescGZIP(), []int{6}
}

func (x *SloFilter) GetField() *SloFilterField {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *SloFilter) GetPredicate() *SloFilterPredicate {
	if x != nil {
		return x.Predicate
	}
	return nil
}

type SloFilters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*SloFilter           `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SloFilters) Reset() {
	*x = SloFilters{}
	mi := &file_com_coralogixapis_slo_v1_slo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SloFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SloFilters) ProtoMessage() {}

func (x *SloFilters) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogixapis_slo_v1_slo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SloFilters.ProtoReflect.Descriptor instead.
func (*SloFilters) Descriptor() ([]byte, []int) {
	return file_com_coralogixapis_slo_v1_slo_proto_rawDescGZIP(), []int{7}
}

func (x *SloFilters) GetFilters() []*SloFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

var File_com_coralogixapis_slo_v1_slo_proto protoreflect.FileDescriptor

const file_com_coralogixapis_slo_v1_slo_proto_rawDesc = "" +
	"\n" +
	"\"com/coralogixapis/slo/v1/slo.proto\x12\x18com.coralogixapis.slo.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1e\n" +
	"\x06Metric\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"\xbb\x01\n" +
	"\tMetricSli\x12A\n" +
	"\vgood_events\x18\x01 \x01(\v2 .com.coralogixapis.slo.v1.MetricR\n" +
	"goodEvents\x12C\n" +
	"\ftotal_events\x18\x02 \x01(\v2 .com.coralogixapis.slo.v1.MetricR\vtotalEvents\x12&\n" +
	"\x0fgroup_by_labels\x18\x03 \x03(\tR\rgroupByLabels\"\xd9\x04\n" +
	"\x03Slo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x02R\vdescription\x88\x01\x01\x12\x18\n" +
	"\acreator\x18\x04 \x01(\tR\acreator\x12A\n" +
	"\x06labels\x18\x05 \x03(\v2).com.coralogixapis.slo.v1.Slo.LabelsEntryR\x06labels\x12D\n" +
	"\n" +
	"metric_sli\x18\x06 \x01(\v2#.com.coralogixapis.slo.v1.MetricSliH\x00R\tmetricSli\x12N\n" +
	"\x0eslo_time_frame\x18\a \x01(\x0e2&.com.coralogixapis.slo.v1.SloTimeFrameH\x01R\fsloTimeFrame\x12>\n" +
	"\x1btarget_threshold_percentage\x18\b \x01(\x05R\x19targetThresholdPercentage\x12;\n" +
	"\vcreate_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x05\n" +
	"\x03sliB\b\n" +
	"\x06windowB\x0e\n" +
	"\f_description\"\x91\x01\n" +
	"\x0eSloFilterField\x12U\n" +
	"\fconst_filter\x18\x01 \x01(\x0e20.com.coralogixapis.slo.v1.SloConstantFilterFieldH\x00R\vconstFilter\x12\x1f\n" +
	"\n" +
	"label_name\x18\x02 \x01(\tH\x00R\tlabelNameB\a\n" +
	"\x05field\"#\n" +
	"\x11IsFilterPredicate\x12\x0e\n" +
	"\x02is\x18\x01 \x03(\tR\x02is\"`\n" +
	"\x12SloFilterPredicate\x12=\n" +
	"\x02is\x18\x01 \x01(\v2+.com.coralogixapis.slo.v1.IsFilterPredicateH\x00R\x02isB\v\n" +
	"\tpredicate\"\x97\x01\n" +
	"\tSloFilter\x12>\n" +
	"\x05field\x18\x01 \x01(\v2(.com.coralogixapis.slo.v1.SloFilterFieldR\x05field\x12J\n" +
	"\tpredicate\x18\x02 \x01(\v2,.com.coralogixapis.slo.v1.SloFilterPredicateR\tpredicate\"K\n" +
	"\n" +
	"SloFilters\x12=\n" +
	"\afilters\x18\x01 \x03(\v2#.com.coralogixapis.slo.v1.SloFilterR\afilters*\xb9\x01\n" +
	"\fSloTimeFrame\x12\x1e\n" +
	"\x1aSLO_TIME_FRAME_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SLO_TIME_FRAME_7_DAYS\x10\x01\x12\x1a\n" +
	"\x16SLO_TIME_FRAME_14_DAYS\x10\x02\x12\x1a\n" +
	"\x16SLO_TIME_FRAME_21_DAYS\x10\x03\x12\x1a\n" +
	"\x16SLO_TIME_FRAME_28_DAYS\x10\x04\x12\x1a\n" +
	"\x16SLO_TIME_FRAME_90_DAYS\x10\x05*f\n" +
	"\x16SloConstantFilterField\x12&\n" +
	"\"SLO_CONST_FILTER_FIELD_UNSPECIFIED\x10\x00\x12$\n" +
	" SLO_CONST_FILTER_FIELD_USER_NAME\x10\x01B\x1aZ\x18com/coralogixapis/slo/v1b\x06proto3"

var (
	file_com_coralogixapis_slo_v1_slo_proto_rawDescOnce sync.Once
	file_com_coralogixapis_slo_v1_slo_proto_rawDescData []byte
)

func file_com_coralogixapis_slo_v1_slo_proto_rawDescGZIP() []byte {
	file_com_coralogixapis_slo_v1_slo_proto_rawDescOnce.Do(func() {
		file_com_coralogixapis_slo_v1_slo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_coralogixapis_slo_v1_slo_proto_rawDesc), len(file_com_coralogixapis_slo_v1_slo_proto_rawDesc)))
	})
	return file_com_coralogixapis_slo_v1_slo_proto_rawDescData
}

var file_com_coralogixapis_slo_v1_slo_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_com_coralogixapis_slo_v1_slo_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_com_coralogixapis_slo_v1_slo_proto_goTypes = []any{
	(SloTimeFrame)(0),             // 0: com.coralogixapis.slo.v1.SloTimeFrame
	(SloConstantFilterField)(0),   // 1: com.coralogixapis.slo.v1.SloConstantFilterField
	(*Metric)(nil),                // 2: com.coralogixapis.slo.v1.Metric
	(*MetricSli)(nil),             // 3: com.coralogixapis.slo.v1.MetricSli
	(*Slo)(nil),                   // 4: com.coralogixapis.slo.v1.Slo
	(*SloFilterField)(nil),        // 5: com.coralogixapis.slo.v1.SloFilterField
	(*IsFilterPredicate)(nil),     // 6: com.coralogixapis.slo.v1.IsFilterPredicate
	(*SloFilterPredicate)(nil),    // 7: com.coralogixapis.slo.v1.SloFilterPredicate
	(*SloFilter)(nil),             // 8: com.coralogixapis.slo.v1.SloFilter
	(*SloFilters)(nil),            // 9: com.coralogixapis.slo.v1.SloFilters
	nil,                           // 10: com.coralogixapis.slo.v1.Slo.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_com_coralogixapis_slo_v1_slo_proto_depIdxs = []int32{
	2,  // 0: com.coralogixapis.slo.v1.MetricSli.good_events:type_name -> com.coralogixapis.slo.v1.Metric
	2,  // 1: com.coralogixapis.slo.v1.MetricSli.total_events:type_name -> com.coralogixapis.slo.v1.Metric
	10, // 2: com.coralogixapis.slo.v1.Slo.labels:type_name -> com.coralogixapis.slo.v1.Slo.LabelsEntry
	3,  // 3: com.coralogixapis.slo.v1.Slo.metric_sli:type_name -> com.coralogixapis.slo.v1.MetricSli
	0,  // 4: com.coralogixapis.slo.v1.Slo.slo_time_frame:type_name -> com.coralogixapis.slo.v1.SloTimeFrame
	11, // 5: com.coralogixapis.slo.v1.Slo.create_time:type_name -> google.protobuf.Timestamp
	11, // 6: com.coralogixapis.slo.v1.Slo.update_time:type_name -> google.protobuf.Timestamp
	1,  // 7: com.coralogixapis.slo.v1.SloFilterField.const_filter:type_name -> com.coralogixapis.slo.v1.SloConstantFilterField
	6,  // 8: com.coralogixapis.slo.v1.SloFilterPredicate.is:type_name -> com.coralogixapis.slo.v1.IsFilterPredicate
	5,  // 9: com.coralogixapis.slo.v1.SloFilter.field:type_name -> com.coralogixapis.slo.v1.SloFilterField
	7,  // 10: com.coralogixapis.slo.v1.SloFilter.predicate:type_name -> com.coralogixapis.slo.v1.SloFilterPredicate
	8,  // 11: com.coralogixapis.slo.v1.SloFilters.filters:type_name -> com.coralogixapis.slo.v1.SloFilter
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_com_coralogixapis_slo_v1_slo_proto_init() }
func file_com_coralogixapis_slo_v1_slo_proto_init() {
	if File_com_coralogixapis_slo_v1_slo_proto != nil {
		return
	}
	file_com_coralogixapis_slo_v1_slo_proto_msgTypes[2].OneofWrappers = []any{
		(*Slo_MetricSli)(nil),
		(*Slo_SloTimeFrame)(nil),
	}
	file_com_coralogixapis_slo_v1_slo_proto_msgTypes[3].OneofWrappers = []any{
		(*SloFilterField_ConstFilter)(nil),
		(*SloFilterField_LabelName)(nil),
	}
	file_com_coralogixapis_slo_v1_slo_proto_msgTypes[5].OneofWrappers = []any{
		(*SloFilterPredicate_Is)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_coralogixapis_slo_v1_slo_proto_rawDesc), len(file_com_coralogixapis_slo_v1_slo_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_coralogixapis_slo_v1_slo_proto_goTypes,
		DependencyIndexes: file_com_coralogixapis_slo_v1_slo_proto_depIdxs,
		EnumInfos:         file_com_coralogixapis_slo_v1_slo_proto_enumTypes,
		MessageInfos:      file_com_coralogixapis_slo_v1_slo_proto_msgTypes,
	}.Build()
	File_com_coralogixapis_slo_v1_slo_proto = out.File
	file_com_coralogixapis_slo_v1_slo_proto_goTypes = nil
	file_com_coralogixapis_slo_v1_slo_proto_depIdxs = nil
}
