// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: com/coralogix/dashboards/v1/application/user_settings_service.proto

package application

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UserSettingsService_UpdateUserDataSourceVisibility_FullMethodName = "/com.coralogix.dashboards.v1.application.UserSettingsService/UpdateUserDataSourceVisibility"
	UserSettingsService_SearchUserSettings_FullMethodName             = "/com.coralogix.dashboards.v1.application.UserSettingsService/SearchUserSettings"
)

// UserSettingsServiceClient is the client API for UserSettingsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserSettingsServiceClient interface {
	UpdateUserDataSourceVisibility(ctx context.Context, in *UpdateUserDataSourceVisibilityRequest, opts ...grpc.CallOption) (*UpdateUserDataSourceVisibilityResponse, error)
	SearchUserSettings(ctx context.Context, in *SearchUserSettingsRequest, opts ...grpc.CallOption) (*SearchUserSettingsResponse, error)
}

type userSettingsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserSettingsServiceClient(cc grpc.ClientConnInterface) UserSettingsServiceClient {
	return &userSettingsServiceClient{cc}
}

func (c *userSettingsServiceClient) UpdateUserDataSourceVisibility(ctx context.Context, in *UpdateUserDataSourceVisibilityRequest, opts ...grpc.CallOption) (*UpdateUserDataSourceVisibilityResponse, error) {
	out := new(UpdateUserDataSourceVisibilityResponse)
	err := c.cc.Invoke(ctx, UserSettingsService_UpdateUserDataSourceVisibility_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSettingsServiceClient) SearchUserSettings(ctx context.Context, in *SearchUserSettingsRequest, opts ...grpc.CallOption) (*SearchUserSettingsResponse, error) {
	out := new(SearchUserSettingsResponse)
	err := c.cc.Invoke(ctx, UserSettingsService_SearchUserSettings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSettingsServiceServer is the server API for UserSettingsService service.
// All implementations must embed UnimplementedUserSettingsServiceServer
// for forward compatibility
type UserSettingsServiceServer interface {
	UpdateUserDataSourceVisibility(context.Context, *UpdateUserDataSourceVisibilityRequest) (*UpdateUserDataSourceVisibilityResponse, error)
	SearchUserSettings(context.Context, *SearchUserSettingsRequest) (*SearchUserSettingsResponse, error)
	mustEmbedUnimplementedUserSettingsServiceServer()
}

// UnimplementedUserSettingsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserSettingsServiceServer struct {
}

func (UnimplementedUserSettingsServiceServer) UpdateUserDataSourceVisibility(context.Context, *UpdateUserDataSourceVisibilityRequest) (*UpdateUserDataSourceVisibilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserDataSourceVisibility not implemented")
}
func (UnimplementedUserSettingsServiceServer) SearchUserSettings(context.Context, *SearchUserSettingsRequest) (*SearchUserSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUserSettings not implemented")
}
func (UnimplementedUserSettingsServiceServer) mustEmbedUnimplementedUserSettingsServiceServer() {}

// UnsafeUserSettingsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserSettingsServiceServer will
// result in compilation errors.
type UnsafeUserSettingsServiceServer interface {
	mustEmbedUnimplementedUserSettingsServiceServer()
}

func RegisterUserSettingsServiceServer(s grpc.ServiceRegistrar, srv UserSettingsServiceServer) {
	s.RegisterService(&UserSettingsService_ServiceDesc, srv)
}

func _UserSettingsService_UpdateUserDataSourceVisibility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserDataSourceVisibilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSettingsServiceServer).UpdateUserDataSourceVisibility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserSettingsService_UpdateUserDataSourceVisibility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSettingsServiceServer).UpdateUserDataSourceVisibility(ctx, req.(*UpdateUserDataSourceVisibilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSettingsService_SearchUserSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUserSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSettingsServiceServer).SearchUserSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserSettingsService_SearchUserSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSettingsServiceServer).SearchUserSettings(ctx, req.(*SearchUserSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserSettingsService_ServiceDesc is the grpc.ServiceDesc for UserSettingsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserSettingsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.coralogix.dashboards.v1.application.UserSettingsService",
	HandlerType: (*UserSettingsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateUserDataSourceVisibility",
			Handler:    _UserSettingsService_UpdateUserDataSourceVisibility_Handler,
		},
		{
			MethodName: "SearchUserSettings",
			Handler:    _UserSettingsService_SearchUserSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "com/coralogix/dashboards/v1/application/user_settings_service.proto",
}
