// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.1
//   protoc               v3.21.12
// source: com/coralogix/alerts/v2/alert.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { BoolValue, StringValue } from "../../../../google/protobuf/wrappers";
import { AlertActiveWhen } from "../v1/alert_active_when";
import { AlertFilters } from "../v1/alert_filters";
import { MetaLabel } from "../v1/alert_meta_label";
import { AlertSeverity, alertSeverityFromJSON, alertSeverityToJSON } from "../v1/alert_severity";
import { DateMessage } from "../v1/date_time";
import { TracingAlert } from "../v1/tracing_alert";
import { AlertCondition } from "./alert_condition";
import { AlertIncidentSettings } from "./alert_incident_settings";
import { AlertNotificationGroups, ShowInInsight } from "./alert_notification_group";

export const protobufPackage = "com.coralogix.alerts.v2";

export interface Alert {
  id: string | undefined;
  name: string | undefined;
  description: string | undefined;
  isActive: boolean | undefined;
  severity: AlertSeverity;
  expiration: DateMessage | undefined;
  condition: AlertCondition | undefined;
  showInInsight?: ShowInInsight | undefined;
  notificationGroups: AlertNotificationGroups[];
  incidentSettings?: AlertIncidentSettings | undefined;
  filters: AlertFilters | undefined;
  activeWhen: AlertActiveWhen | undefined;
  notificationPayloadFilters: string[];
  metaLabels: MetaLabel[];
  metaLabelsStrings: string[];
  tracingAlert: TracingAlert | undefined;
  uniqueIdentifier: string | undefined;
}

function createBaseAlert(): Alert {
  return {
    id: undefined,
    name: undefined,
    description: undefined,
    isActive: undefined,
    severity: 0,
    expiration: undefined,
    condition: undefined,
    showInInsight: undefined,
    notificationGroups: [],
    incidentSettings: undefined,
    filters: undefined,
    activeWhen: undefined,
    notificationPayloadFilters: [],
    metaLabels: [],
    metaLabelsStrings: [],
    tracingAlert: undefined,
    uniqueIdentifier: undefined,
  };
}

export const Alert = {
  encode(message: Alert, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== undefined) {
      StringValue.encode({ value: message.id! }, writer.uint32(10).fork()).ldelim();
    }
    if (message.name !== undefined) {
      StringValue.encode({ value: message.name! }, writer.uint32(18).fork()).ldelim();
    }
    if (message.description !== undefined) {
      StringValue.encode({ value: message.description! }, writer.uint32(26).fork()).ldelim();
    }
    if (message.isActive !== undefined) {
      BoolValue.encode({ value: message.isActive! }, writer.uint32(34).fork()).ldelim();
    }
    if (message.severity !== 0) {
      writer.uint32(40).int32(message.severity);
    }
    if (message.expiration !== undefined) {
      DateMessage.encode(message.expiration, writer.uint32(50).fork()).ldelim();
    }
    if (message.condition !== undefined) {
      AlertCondition.encode(message.condition, writer.uint32(58).fork()).ldelim();
    }
    if (message.showInInsight !== undefined) {
      ShowInInsight.encode(message.showInInsight, writer.uint32(66).fork()).ldelim();
    }
    for (const v of message.notificationGroups) {
      AlertNotificationGroups.encode(v!, writer.uint32(74).fork()).ldelim();
    }
    if (message.incidentSettings !== undefined) {
      AlertIncidentSettings.encode(message.incidentSettings, writer.uint32(138).fork()).ldelim();
    }
    if (message.filters !== undefined) {
      AlertFilters.encode(message.filters, writer.uint32(82).fork()).ldelim();
    }
    if (message.activeWhen !== undefined) {
      AlertActiveWhen.encode(message.activeWhen, writer.uint32(90).fork()).ldelim();
    }
    for (const v of message.notificationPayloadFilters) {
      StringValue.encode({ value: v!! }, writer.uint32(98).fork()).ldelim();
    }
    for (const v of message.metaLabels) {
      MetaLabel.encode(v!, writer.uint32(106).fork()).ldelim();
    }
    for (const v of message.metaLabelsStrings) {
      StringValue.encode({ value: v!! }, writer.uint32(114).fork()).ldelim();
    }
    if (message.tracingAlert !== undefined) {
      TracingAlert.encode(message.tracingAlert, writer.uint32(122).fork()).ldelim();
    }
    if (message.uniqueIdentifier !== undefined) {
      StringValue.encode({ value: message.uniqueIdentifier! }, writer.uint32(130).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Alert {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAlert();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.id = StringValue.decode(reader, reader.uint32()).value;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.name = StringValue.decode(reader, reader.uint32()).value;
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.description = StringValue.decode(reader, reader.uint32()).value;
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.isActive = BoolValue.decode(reader, reader.uint32()).value;
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.severity = reader.int32() as any;
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.expiration = DateMessage.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.condition = AlertCondition.decode(reader, reader.uint32());
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.showInInsight = ShowInInsight.decode(reader, reader.uint32());
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.notificationGroups.push(AlertNotificationGroups.decode(reader, reader.uint32()));
          continue;
        case 17:
          if (tag !== 138) {
            break;
          }

          message.incidentSettings = AlertIncidentSettings.decode(reader, reader.uint32());
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.filters = AlertFilters.decode(reader, reader.uint32());
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.activeWhen = AlertActiveWhen.decode(reader, reader.uint32());
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.notificationPayloadFilters.push(StringValue.decode(reader, reader.uint32()).value);
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.metaLabels.push(MetaLabel.decode(reader, reader.uint32()));
          continue;
        case 14:
          if (tag !== 114) {
            break;
          }

          message.metaLabelsStrings.push(StringValue.decode(reader, reader.uint32()).value);
          continue;
        case 15:
          if (tag !== 122) {
            break;
          }

          message.tracingAlert = TracingAlert.decode(reader, reader.uint32());
          continue;
        case 16:
          if (tag !== 130) {
            break;
          }

          message.uniqueIdentifier = StringValue.decode(reader, reader.uint32()).value;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Alert {
    return {
      id: isSet(object.id) ? String(object.id) : undefined,
      name: isSet(object.name) ? String(object.name) : undefined,
      description: isSet(object.description) ? String(object.description) : undefined,
      isActive: isSet(object.isActive) ? Boolean(object.isActive) : undefined,
      severity: isSet(object.severity) ? alertSeverityFromJSON(object.severity) : 0,
      expiration: isSet(object.expiration) ? DateMessage.fromJSON(object.expiration) : undefined,
      condition: isSet(object.condition) ? AlertCondition.fromJSON(object.condition) : undefined,
      showInInsight: isSet(object.showInInsight) ? ShowInInsight.fromJSON(object.showInInsight) : undefined,
      notificationGroups: globalThis.Array.isArray(object?.notificationGroups)
        ? object.notificationGroups.map((e: any) => AlertNotificationGroups.fromJSON(e))
        : [],
      incidentSettings: isSet(object.incidentSettings)
        ? AlertIncidentSettings.fromJSON(object.incidentSettings)
        : undefined,
      filters: isSet(object.filters) ? AlertFilters.fromJSON(object.filters) : undefined,
      activeWhen: isSet(object.activeWhen) ? AlertActiveWhen.fromJSON(object.activeWhen) : undefined,
      notificationPayloadFilters: globalThis.Array.isArray(object?.notificationPayloadFilters)
        ? object.notificationPayloadFilters.map((e: any) => String(e))
        : [],
      metaLabels: globalThis.Array.isArray(object?.metaLabels)
        ? object.metaLabels.map((e: any) => MetaLabel.fromJSON(e))
        : [],
      metaLabelsStrings: globalThis.Array.isArray(object?.metaLabelsStrings)
        ? object.metaLabelsStrings.map((e: any) => String(e))
        : [],
      tracingAlert: isSet(object.tracingAlert) ? TracingAlert.fromJSON(object.tracingAlert) : undefined,
      uniqueIdentifier: isSet(object.uniqueIdentifier) ? String(object.uniqueIdentifier) : undefined,
    };
  },

  toJSON(message: Alert): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = message.id;
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.description !== undefined) {
      obj.description = message.description;
    }
    if (message.isActive !== undefined) {
      obj.isActive = message.isActive;
    }
    if (message.severity !== 0) {
      obj.severity = alertSeverityToJSON(message.severity);
    }
    if (message.expiration !== undefined) {
      obj.expiration = DateMessage.toJSON(message.expiration);
    }
    if (message.condition !== undefined) {
      obj.condition = AlertCondition.toJSON(message.condition);
    }
    if (message.showInInsight !== undefined) {
      obj.showInInsight = ShowInInsight.toJSON(message.showInInsight);
    }
    if (message.notificationGroups?.length) {
      obj.notificationGroups = message.notificationGroups.map((e) => AlertNotificationGroups.toJSON(e));
    }
    if (message.incidentSettings !== undefined) {
      obj.incidentSettings = AlertIncidentSettings.toJSON(message.incidentSettings);
    }
    if (message.filters !== undefined) {
      obj.filters = AlertFilters.toJSON(message.filters);
    }
    if (message.activeWhen !== undefined) {
      obj.activeWhen = AlertActiveWhen.toJSON(message.activeWhen);
    }
    if (message.notificationPayloadFilters?.length) {
      obj.notificationPayloadFilters = message.notificationPayloadFilters;
    }
    if (message.metaLabels?.length) {
      obj.metaLabels = message.metaLabels.map((e) => MetaLabel.toJSON(e));
    }
    if (message.metaLabelsStrings?.length) {
      obj.metaLabelsStrings = message.metaLabelsStrings;
    }
    if (message.tracingAlert !== undefined) {
      obj.tracingAlert = TracingAlert.toJSON(message.tracingAlert);
    }
    if (message.uniqueIdentifier !== undefined) {
      obj.uniqueIdentifier = message.uniqueIdentifier;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Alert>, I>>(base?: I): Alert {
    return Alert.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Alert>, I>>(object: I): Alert {
    const message = createBaseAlert();
    message.id = object.id ?? undefined;
    message.name = object.name ?? undefined;
    message.description = object.description ?? undefined;
    message.isActive = object.isActive ?? undefined;
    message.severity = object.severity ?? 0;
    message.expiration = (object.expiration !== undefined && object.expiration !== null)
      ? DateMessage.fromPartial(object.expiration)
      : undefined;
    message.condition = (object.condition !== undefined && object.condition !== null)
      ? AlertCondition.fromPartial(object.condition)
      : undefined;
    message.showInInsight = (object.showInInsight !== undefined && object.showInInsight !== null)
      ? ShowInInsight.fromPartial(object.showInInsight)
      : undefined;
    message.notificationGroups = object.notificationGroups?.map((e) => AlertNotificationGroups.fromPartial(e)) || [];
    message.incidentSettings = (object.incidentSettings !== undefined && object.incidentSettings !== null)
      ? AlertIncidentSettings.fromPartial(object.incidentSettings)
      : undefined;
    message.filters = (object.filters !== undefined && object.filters !== null)
      ? AlertFilters.fromPartial(object.filters)
      : undefined;
    message.activeWhen = (object.activeWhen !== undefined && object.activeWhen !== null)
      ? AlertActiveWhen.fromPartial(object.activeWhen)
      : undefined;
    message.notificationPayloadFilters = object.notificationPayloadFilters?.map((e) => e) || [];
    message.metaLabels = object.metaLabels?.map((e) => MetaLabel.fromPartial(e)) || [];
    message.metaLabelsStrings = object.metaLabelsStrings?.map((e) => e) || [];
    message.tracingAlert = (object.tracingAlert !== undefined && object.tracingAlert !== null)
      ? TracingAlert.fromPartial(object.tracingAlert)
      : undefined;
    message.uniqueIdentifier = object.uniqueIdentifier ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
