# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/coralogix/quota/v1/bulk_test_log_policies_response.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.coralogix.quota.v1 import test_policies_result_pb2 as com_dot_coralogix_dot_quota_dot_v1_dot_test__policies__result__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<com/coralogix/quota/v1/bulk_test_log_policies_response.proto\x12\x16\x63om.coralogix.quota.v1\x1a\x31\x63om/coralogix/quota/v1/test_policies_result.proto\"l\n\x1b\x42ulkTestLogPoliciesResponse\x12M\n\x19test_policies_bulk_result\x18\x01 \x03(\x0b\x32*.com.coralogix.quota.v1.TestPoliciesResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.coralogix.quota.v1.bulk_test_log_policies_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BULKTESTLOGPOLICIESRESPONSE']._serialized_start=139
  _globals['_BULKTESTLOGPOLICIESRESPONSE']._serialized_end=247
# @@protoc_insertion_point(module_scope)
