# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/coralogix/quota/v1/tag_rule.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from com.coralogix.quota.v1 import enums_pb2 as com_dot_coralogix_dot_quota_dot_v1_dot_enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%com/coralogix/quota/v1/tag_rule.proto\x12\x16\x63om.coralogix.quota.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a\"com/coralogix/quota/v1/enums.proto\"\xa4\x01\n\x07TagRule\x12\x38\n\x0crule_type_id\x18\x01 \x01(\x0e\x32\".com.coralogix.quota.v1.RuleTypeId\x12.\n\x08tag_name\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12/\n\ttag_value\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.coralogix.quota.v1.tag_rule_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAGRULE']._serialized_start=134
  _globals['_TAGRULE']._serialized_end=298
# @@protoc_insertion_point(module_scope)
