// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.1
//   protoc               v3.21.12
// source: com/coralogixapis/dashboards/v1/services/dashboard_folders_service.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { StringValue } from "../../../../../google/protobuf/wrappers";
import { DashboardFolder } from "../common/folder";

export const protobufPackage = "com.coralogixapis.dashboards.v1.services";

export interface CreateDashboardFolderRequest {
  requestId: string | undefined;
  folder: DashboardFolder | undefined;
}

export interface CreateDashboardFolderResponse {
}

export interface ReplaceDashboardFolderRequest {
  requestId: string | undefined;
  folder: DashboardFolder | undefined;
}

export interface ReplaceDashboardFolderResponse {
}

export interface DeleteDashboardFolderRequest {
  requestId: string | undefined;
  folderId: string | undefined;
}

export interface DeleteDashboardFolderResponse {
}

export interface ListDashboardFoldersRequest {
}

export interface ListDashboardFoldersResponse {
  folder: DashboardFolder[];
}

function createBaseCreateDashboardFolderRequest(): CreateDashboardFolderRequest {
  return { requestId: undefined, folder: undefined };
}

export const CreateDashboardFolderRequest = {
  encode(message: CreateDashboardFolderRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.requestId !== undefined) {
      StringValue.encode({ value: message.requestId! }, writer.uint32(10).fork()).ldelim();
    }
    if (message.folder !== undefined) {
      DashboardFolder.encode(message.folder, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CreateDashboardFolderRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateDashboardFolderRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.requestId = StringValue.decode(reader, reader.uint32()).value;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.folder = DashboardFolder.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateDashboardFolderRequest {
    return {
      requestId: isSet(object.requestId) ? String(object.requestId) : undefined,
      folder: isSet(object.folder) ? DashboardFolder.fromJSON(object.folder) : undefined,
    };
  },

  toJSON(message: CreateDashboardFolderRequest): unknown {
    const obj: any = {};
    if (message.requestId !== undefined) {
      obj.requestId = message.requestId;
    }
    if (message.folder !== undefined) {
      obj.folder = DashboardFolder.toJSON(message.folder);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateDashboardFolderRequest>, I>>(base?: I): CreateDashboardFolderRequest {
    return CreateDashboardFolderRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateDashboardFolderRequest>, I>>(object: I): CreateDashboardFolderRequest {
    const message = createBaseCreateDashboardFolderRequest();
    message.requestId = object.requestId ?? undefined;
    message.folder = (object.folder !== undefined && object.folder !== null)
      ? DashboardFolder.fromPartial(object.folder)
      : undefined;
    return message;
  },
};

function createBaseCreateDashboardFolderResponse(): CreateDashboardFolderResponse {
  return {};
}

export const CreateDashboardFolderResponse = {
  encode(_: CreateDashboardFolderResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CreateDashboardFolderResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateDashboardFolderResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CreateDashboardFolderResponse {
    return {};
  },

  toJSON(_: CreateDashboardFolderResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateDashboardFolderResponse>, I>>(base?: I): CreateDashboardFolderResponse {
    return CreateDashboardFolderResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateDashboardFolderResponse>, I>>(_: I): CreateDashboardFolderResponse {
    const message = createBaseCreateDashboardFolderResponse();
    return message;
  },
};

function createBaseReplaceDashboardFolderRequest(): ReplaceDashboardFolderRequest {
  return { requestId: undefined, folder: undefined };
}

export const ReplaceDashboardFolderRequest = {
  encode(message: ReplaceDashboardFolderRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.requestId !== undefined) {
      StringValue.encode({ value: message.requestId! }, writer.uint32(10).fork()).ldelim();
    }
    if (message.folder !== undefined) {
      DashboardFolder.encode(message.folder, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ReplaceDashboardFolderRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReplaceDashboardFolderRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.requestId = StringValue.decode(reader, reader.uint32()).value;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.folder = DashboardFolder.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReplaceDashboardFolderRequest {
    return {
      requestId: isSet(object.requestId) ? String(object.requestId) : undefined,
      folder: isSet(object.folder) ? DashboardFolder.fromJSON(object.folder) : undefined,
    };
  },

  toJSON(message: ReplaceDashboardFolderRequest): unknown {
    const obj: any = {};
    if (message.requestId !== undefined) {
      obj.requestId = message.requestId;
    }
    if (message.folder !== undefined) {
      obj.folder = DashboardFolder.toJSON(message.folder);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReplaceDashboardFolderRequest>, I>>(base?: I): ReplaceDashboardFolderRequest {
    return ReplaceDashboardFolderRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReplaceDashboardFolderRequest>, I>>(
    object: I,
  ): ReplaceDashboardFolderRequest {
    const message = createBaseReplaceDashboardFolderRequest();
    message.requestId = object.requestId ?? undefined;
    message.folder = (object.folder !== undefined && object.folder !== null)
      ? DashboardFolder.fromPartial(object.folder)
      : undefined;
    return message;
  },
};

function createBaseReplaceDashboardFolderResponse(): ReplaceDashboardFolderResponse {
  return {};
}

export const ReplaceDashboardFolderResponse = {
  encode(_: ReplaceDashboardFolderResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ReplaceDashboardFolderResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReplaceDashboardFolderResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ReplaceDashboardFolderResponse {
    return {};
  },

  toJSON(_: ReplaceDashboardFolderResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ReplaceDashboardFolderResponse>, I>>(base?: I): ReplaceDashboardFolderResponse {
    return ReplaceDashboardFolderResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReplaceDashboardFolderResponse>, I>>(_: I): ReplaceDashboardFolderResponse {
    const message = createBaseReplaceDashboardFolderResponse();
    return message;
  },
};

function createBaseDeleteDashboardFolderRequest(): DeleteDashboardFolderRequest {
  return { requestId: undefined, folderId: undefined };
}

export const DeleteDashboardFolderRequest = {
  encode(message: DeleteDashboardFolderRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.requestId !== undefined) {
      StringValue.encode({ value: message.requestId! }, writer.uint32(10).fork()).ldelim();
    }
    if (message.folderId !== undefined) {
      StringValue.encode({ value: message.folderId! }, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DeleteDashboardFolderRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteDashboardFolderRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.requestId = StringValue.decode(reader, reader.uint32()).value;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.folderId = StringValue.decode(reader, reader.uint32()).value;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteDashboardFolderRequest {
    return {
      requestId: isSet(object.requestId) ? String(object.requestId) : undefined,
      folderId: isSet(object.folderId) ? String(object.folderId) : undefined,
    };
  },

  toJSON(message: DeleteDashboardFolderRequest): unknown {
    const obj: any = {};
    if (message.requestId !== undefined) {
      obj.requestId = message.requestId;
    }
    if (message.folderId !== undefined) {
      obj.folderId = message.folderId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteDashboardFolderRequest>, I>>(base?: I): DeleteDashboardFolderRequest {
    return DeleteDashboardFolderRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteDashboardFolderRequest>, I>>(object: I): DeleteDashboardFolderRequest {
    const message = createBaseDeleteDashboardFolderRequest();
    message.requestId = object.requestId ?? undefined;
    message.folderId = object.folderId ?? undefined;
    return message;
  },
};

function createBaseDeleteDashboardFolderResponse(): DeleteDashboardFolderResponse {
  return {};
}

export const DeleteDashboardFolderResponse = {
  encode(_: DeleteDashboardFolderResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DeleteDashboardFolderResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteDashboardFolderResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): DeleteDashboardFolderResponse {
    return {};
  },

  toJSON(_: DeleteDashboardFolderResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteDashboardFolderResponse>, I>>(base?: I): DeleteDashboardFolderResponse {
    return DeleteDashboardFolderResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteDashboardFolderResponse>, I>>(_: I): DeleteDashboardFolderResponse {
    const message = createBaseDeleteDashboardFolderResponse();
    return message;
  },
};

function createBaseListDashboardFoldersRequest(): ListDashboardFoldersRequest {
  return {};
}

export const ListDashboardFoldersRequest = {
  encode(_: ListDashboardFoldersRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ListDashboardFoldersRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListDashboardFoldersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ListDashboardFoldersRequest {
    return {};
  },

  toJSON(_: ListDashboardFoldersRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ListDashboardFoldersRequest>, I>>(base?: I): ListDashboardFoldersRequest {
    return ListDashboardFoldersRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListDashboardFoldersRequest>, I>>(_: I): ListDashboardFoldersRequest {
    const message = createBaseListDashboardFoldersRequest();
    return message;
  },
};

function createBaseListDashboardFoldersResponse(): ListDashboardFoldersResponse {
  return { folder: [] };
}

export const ListDashboardFoldersResponse = {
  encode(message: ListDashboardFoldersResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.folder) {
      DashboardFolder.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ListDashboardFoldersResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListDashboardFoldersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.folder.push(DashboardFolder.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListDashboardFoldersResponse {
    return {
      folder: globalThis.Array.isArray(object?.folder)
        ? object.folder.map((e: any) => DashboardFolder.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListDashboardFoldersResponse): unknown {
    const obj: any = {};
    if (message.folder?.length) {
      obj.folder = message.folder.map((e) => DashboardFolder.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListDashboardFoldersResponse>, I>>(base?: I): ListDashboardFoldersResponse {
    return ListDashboardFoldersResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListDashboardFoldersResponse>, I>>(object: I): ListDashboardFoldersResponse {
    const message = createBaseListDashboardFoldersResponse();
    message.folder = object.folder?.map((e) => DashboardFolder.fromPartial(e)) || [];
    return message;
  },
};

export interface DashboardFoldersService {
  ListDashboardFolders(request: ListDashboardFoldersRequest): Promise<ListDashboardFoldersResponse>;
  CreateDashboardFolder(request: CreateDashboardFolderRequest): Promise<CreateDashboardFolderResponse>;
  ReplaceDashboardFolder(request: ReplaceDashboardFolderRequest): Promise<ReplaceDashboardFolderResponse>;
  DeleteDashboardFolder(request: DeleteDashboardFolderRequest): Promise<DeleteDashboardFolderResponse>;
}

export const DashboardFoldersServiceServiceName = "com.coralogixapis.dashboards.v1.services.DashboardFoldersService";
export class DashboardFoldersServiceClientImpl implements DashboardFoldersService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || DashboardFoldersServiceServiceName;
    this.rpc = rpc;
    this.ListDashboardFolders = this.ListDashboardFolders.bind(this);
    this.CreateDashboardFolder = this.CreateDashboardFolder.bind(this);
    this.ReplaceDashboardFolder = this.ReplaceDashboardFolder.bind(this);
    this.DeleteDashboardFolder = this.DeleteDashboardFolder.bind(this);
  }
  ListDashboardFolders(request: ListDashboardFoldersRequest): Promise<ListDashboardFoldersResponse> {
    const data = ListDashboardFoldersRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListDashboardFolders", data);
    return promise.then((data) => ListDashboardFoldersResponse.decode(_m0.Reader.create(data)));
  }

  CreateDashboardFolder(request: CreateDashboardFolderRequest): Promise<CreateDashboardFolderResponse> {
    const data = CreateDashboardFolderRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateDashboardFolder", data);
    return promise.then((data) => CreateDashboardFolderResponse.decode(_m0.Reader.create(data)));
  }

  ReplaceDashboardFolder(request: ReplaceDashboardFolderRequest): Promise<ReplaceDashboardFolderResponse> {
    const data = ReplaceDashboardFolderRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ReplaceDashboardFolder", data);
    return promise.then((data) => ReplaceDashboardFolderResponse.decode(_m0.Reader.create(data)));
  }

  DeleteDashboardFolder(request: DeleteDashboardFolderRequest): Promise<DeleteDashboardFolderResponse> {
    const data = DeleteDashboardFolderRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "DeleteDashboardFolder", data);
    return promise.then((data) => DeleteDashboardFolderResponse.decode(_m0.Reader.create(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
