# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/coralogix/datausage/v2/data_usage.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+com/coralogix/datausage/v2/data_usage.proto\x12\x1a\x63om.coralogix.datausage.v2\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"0\n\x04Team\x12(\n\x02id\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\"g\n\tDateRange\x12-\n\tfrom_date\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07to_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\".\n\x10GenericDimension\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\xc6\x02\n\tDimension\x12\x34\n\x06pillar\x18\x01 \x01(\x0e\x32\".com.coralogix.datausage.v2.PillarH\x00\x12I\n\x11generic_dimension\x18\x02 \x01(\x0b\x32,.com.coralogix.datausage.v2.GenericDimensionH\x00\x12\x37\n\x04tier\x18\x03 \x01(\x0e\x32#.com.coralogix.datausage.v2.TcoTierB\x02\x18\x01H\x00\x12\x38\n\x08severity\x18\x04 \x01(\x0e\x32$.com.coralogix.datausage.v2.SeverityH\x00\x12\x38\n\x08priority\x18\x05 \x01(\x0e\x32$.com.coralogix.datausage.v2.PriorityH\x00\x42\x0b\n\tdimension*j\n\x06Pillar\x12\x16\n\x12PILLAR_UNSPECIFIED\x10\x00\x12\x12\n\x0ePILLAR_METRICS\x10\x01\x12\x0f\n\x0bPILLAR_LOGS\x10\x02\x12\x10\n\x0cPILLAR_SPANS\x10\x03\x12\x11\n\rPILLAR_BINARY\x10\x04*w\n\x07TcoTier\x12\x18\n\x14TCO_TIER_UNSPECIFIED\x10\x00\x12\x10\n\x0cTCO_TIER_LOW\x10\x01\x12\x13\n\x0fTCO_TIER_MEDIUM\x10\x02\x12\x11\n\rTCO_TIER_HIGH\x10\x03\x12\x14\n\x10TCO_TIER_BLOCKED\x10\x04\x1a\x02\x18\x01*t\n\x08Priority\x12\x18\n\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n\x0cPRIORITY_LOW\x10\x01\x12\x13\n\x0fPRIORITY_MEDIUM\x10\x02\x12\x11\n\rPRIORITY_HIGH\x10\x03\x12\x14\n\x10PRIORITY_BLOCKED\x10\x04*\xa2\x01\n\x08Severity\x12\x18\n\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x12\n\x0eSEVERITY_DEBUG\x10\x01\x12\x14\n\x10SEVERITY_VERBOSE\x10\x02\x12\x11\n\rSEVERITY_INFO\x10\x03\x12\x14\n\x10SEVERITY_WARNING\x10\x04\x12\x12\n\x0eSEVERITY_ERROR\x10\x05\x12\x15\n\x11SEVERITY_CRITICAL\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.coralogix.datausage.v2.data_usage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TCOTIER']._loaded_options = None
  _globals['_TCOTIER']._serialized_options = b'\030\001'
  _globals['_DIMENSION'].fields_by_name['tier']._loaded_options = None
  _globals['_DIMENSION'].fields_by_name['tier']._serialized_options = b'\030\001'
  _globals['_PILLAR']._serialized_start=672
  _globals['_PILLAR']._serialized_end=778
  _globals['_TCOTIER']._serialized_start=780
  _globals['_TCOTIER']._serialized_end=899
  _globals['_PRIORITY']._serialized_start=901
  _globals['_PRIORITY']._serialized_end=1017
  _globals['_SEVERITY']._serialized_start=1020
  _globals['_SEVERITY']._serialized_end=1182
  _globals['_TEAM']._serialized_start=140
  _globals['_TEAM']._serialized_end=188
  _globals['_DATERANGE']._serialized_start=190
  _globals['_DATERANGE']._serialized_end=293
  _globals['_GENERICDIMENSION']._serialized_start=295
  _globals['_GENERICDIMENSION']._serialized_end=341
  _globals['_DIMENSION']._serialized_start=344
  _globals['_DIMENSION']._serialized_end=670
# @@protoc_insertion_point(module_scope)
