[workspace]
resolver = "2"
members = [
    "actions",
    "alerts",
    "aaa",
    "logs",
    "metrics",
    "dashboards",
    "integrations",
    "dataprime",
    "infra-monitoring",
    "recording-rules",
    "dataplans",
]
