[workspace]
resolver = "2"
members = [
    "actions",
    "alerts",
    "aaa",
    "logs",
    "metrics",
    "dashboards",
    "dataprime",
    "integrations",
    "infra-monitoring", "recording-rule-group-sets",
]
