[workspace]
resolver = "2"
members = [
    "aaa",
    "actions",
    "alerts",
    "dashboard-folders",
    "dashboards",
    "dataplans",
    "enrichments",
    "incidents",
    "infra-monitoring",
    "integrations",
    "logs",
    "metrics",
    "notifications",
    "recording-rules",
]
