[package]
name = "extensions"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "*"
cx-sdk = { path = "../../cx-sdk" }
serde_json = "*"
time = "0.3.36"

tokio = { version = "*", features = ["full"] }
tonic = "*"
uuid = "*"
