from com.coralogix.dataprime.v1 import unauthenticated_internal_query_request_pb2 as _unauthenticated_internal_query_request_pb2
from com.coralogix.dataprime.v1 import unauthenticated_internal_query_response_pb2 as _unauthenticated_internal_query_response_pb2
from com.coralogix.dataprime.v1 import audit_log_pb2 as _audit_log_pb2
from google.protobuf import descriptor_pb2 as _descriptor_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
