openapi: 3.0.0
info:
  title: Pet Service V3
  version: 1.0.0
paths: {}
components:
  schemas:
    Pet:
      oneOf:
        - $ref: '#/components/schemas/PetDogAdoptedWrapper'
        - $ref: '#/components/schemas/PetDogAvailableWrapper'
        - $ref: '#/components/schemas/PetCatAdoptedWrapper'
        - $ref: '#/components/schemas/PetCatAvailableWrapper'

    PetDogAdoptedWrapper:
      type: object
      required: [pet_dog_adopted]
      properties:
        pet_dog_adopted:
          $ref: '#/components/schemas/PetDogAdopted'

    PetDogAvailableWrapper:
      type: object
      required: [pet_dog_available]
      properties:
        pet_dog_available:
          $ref: '#/components/schemas/PetDogAvailable'

    PetCatAdoptedWrapper:
      type: object
      required: [pet_cat_adopted]
      properties:
        pet_cat_adopted:
          $ref: '#/components/schemas/PetCatAdopted'

    PetCatAvailableWrapper:
      type: object
      required: [pet_cat_available]
      properties:
        pet_cat_available:
          $ref: '#/components/schemas/PetCatAvailable'

    PetDogAdopted:
      type: object
      properties:
        name:
          type: string
        dog:
          $ref: '#/components/schemas/Dog'
        adopted:
          $ref: '#/components/schemas/Adopted'

    PetDogAvailable:
      type: object
      properties:
        name:
          type: string
        dog:
          $ref: '#/components/schemas/Dog'
        available:
          $ref: '#/components/schemas/Available'

    PetCatAdopted:
      type: object
      properties:
        name:
          type: string
        cat:
          $ref: '#/components/schemas/Cat'
        adopted:
          $ref: '#/components/schemas/Adopted'

    PetCatAvailable:
      type: object
      properties:
        name:
          type: string
        cat:
          $ref: '#/components/schemas/Cat'
        available:
          $ref: '#/components/schemas/Available'

    Dog:
      type: object
      properties:
        breed:
          type: string
    Cat:
      type: object
      properties:
        color:
          type: string
    Adopted:
      type: object
      properties:
        ownerName:
          type: string
    Available:
      type: object
      properties:
        ready:
          type: boolean
