openapi: 3.0.0
info:
  title: Pet Service V5
  version: 1.0.0
paths: {}
components:
  schemas:
    Pet:
      allOf:
        - $ref: '#/components/schemas/PetCommon'
        - oneOf:
            - $ref: '#/components/schemas/PetType'
            - $ref: '#/components/schemas/PetStatus'
    PetCommon:
      type: object
      properties:
        name:
          type: string
    PetType:
      oneOf:
        - $ref: '#/components/schemas/PetTypeDog'
        - $ref: '#/components/schemas/PetTypeCat'
    PetTypeDog:
      type: object
      properties:
        dog:
          $ref: '#/components/schemas/Dog'
    PetTypeCat:
      type: object
      properties:
        cat:
          $ref: '#/components/schemas/Cat'
    PetStatus:
      oneOf:
        - $ref: '#/components/schemas/PetStatusAdopted'
        - $ref: '#/components/schemas/PetStatusAvailable'
    PetStatusAdopted:
      type: object
      properties:
        adopted:
          $ref: '#/components/schemas/Adopted'
    PetStatusAvailable:
      type: object
      properties:
        available:
          $ref: '#/components/schemas/Available'
    Dog:
      type: object
      properties:
        breed:
          type: string
    Cat:
      type: object
      properties:
        color:
          type: string
    Adopted:
      type: object
      properties:
        ownerName:
          type: string
    Available:
      type: object
      properties:
        ready:
          type: boolean
