/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type ScopesServiceAPI interface {

	/*
	ScopesServiceCreateScope Create Scope

	No description available

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiScopesServiceCreateScopeRequest
	*/
	ScopesServiceCreateScope(ctx context.Context) ApiScopesServiceCreateScopeRequest

	// ScopesServiceCreateScopeExecute executes the request
	//  @return ComCoralogixapisScopesV1CreateScopeResponse
	ScopesServiceCreateScopeExecute(r ApiScopesServiceCreateScopeRequest) (*ComCoralogixapisScopesV1CreateScopeResponse, *http.Response, error)

	/*
	ScopesServiceDeleteScope Delete Scope

	No description available

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return ApiScopesServiceDeleteScopeRequest
	*/
	ScopesServiceDeleteScope(ctx context.Context, id string) ApiScopesServiceDeleteScopeRequest

	// ScopesServiceDeleteScopeExecute executes the request
	//  @return map[string]interface{}
	ScopesServiceDeleteScopeExecute(r ApiScopesServiceDeleteScopeRequest) (map[string]interface{}, *http.Response, error)

	/*
	ScopesServiceGetTeamScopes Get Team Scopes

	No description available

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiScopesServiceGetTeamScopesRequest
	*/
	ScopesServiceGetTeamScopes(ctx context.Context) ApiScopesServiceGetTeamScopesRequest

	// ScopesServiceGetTeamScopesExecute executes the request
	//  @return ComCoralogixapisScopesV1GetScopesResponse
	ScopesServiceGetTeamScopesExecute(r ApiScopesServiceGetTeamScopesRequest) (*ComCoralogixapisScopesV1GetScopesResponse, *http.Response, error)

	/*
	ScopesServiceGetTeamScopesByIds Get Team Scopes By Ids

	No description available

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiScopesServiceGetTeamScopesByIdsRequest
	*/
	ScopesServiceGetTeamScopesByIds(ctx context.Context) ApiScopesServiceGetTeamScopesByIdsRequest

	// ScopesServiceGetTeamScopesByIdsExecute executes the request
	//  @return ComCoralogixapisScopesV1GetScopesResponse
	ScopesServiceGetTeamScopesByIdsExecute(r ApiScopesServiceGetTeamScopesByIdsRequest) (*ComCoralogixapisScopesV1GetScopesResponse, *http.Response, error)

	/*
	ScopesServiceUpdateScope Update Scope

	No description available

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiScopesServiceUpdateScopeRequest
	*/
	ScopesServiceUpdateScope(ctx context.Context) ApiScopesServiceUpdateScopeRequest

	// ScopesServiceUpdateScopeExecute executes the request
	//  @return ComCoralogixapisScopesV1UpdateScopeResponse
	ScopesServiceUpdateScopeExecute(r ApiScopesServiceUpdateScopeRequest) (*ComCoralogixapisScopesV1UpdateScopeResponse, *http.Response, error)
}

// ScopesServiceAPIService ScopesServiceAPI service
type ScopesServiceAPIService service

type ApiScopesServiceCreateScopeRequest struct {
	ctx context.Context
	ApiService ScopesServiceAPI
	createScopeRequest *CreateScopeRequest
}

func (r ApiScopesServiceCreateScopeRequest) CreateScopeRequest(createScopeRequest CreateScopeRequest) ApiScopesServiceCreateScopeRequest {
	r.createScopeRequest = &createScopeRequest
	return r
}

func (r ApiScopesServiceCreateScopeRequest) Execute() (*ComCoralogixapisScopesV1CreateScopeResponse, *http.Response, error) {
	return r.ApiService.ScopesServiceCreateScopeExecute(r)
}

/*
ScopesServiceCreateScope Create Scope

No description available

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiScopesServiceCreateScopeRequest
*/
func (a *ScopesServiceAPIService) ScopesServiceCreateScope(ctx context.Context) ApiScopesServiceCreateScopeRequest {
	return ApiScopesServiceCreateScopeRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ComCoralogixapisScopesV1CreateScopeResponse
func (a *ScopesServiceAPIService) ScopesServiceCreateScopeExecute(r ApiScopesServiceCreateScopeRequest) (*ComCoralogixapisScopesV1CreateScopeResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ComCoralogixapisScopesV1CreateScopeResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ScopesServiceAPIService.ScopesServiceCreateScope")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/scopes"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createScopeRequest
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiScopesServiceDeleteScopeRequest struct {
	ctx context.Context
	ApiService ScopesServiceAPI
	id string
}

func (r ApiScopesServiceDeleteScopeRequest) Execute() (map[string]interface{}, *http.Response, error) {
	return r.ApiService.ScopesServiceDeleteScopeExecute(r)
}

/*
ScopesServiceDeleteScope Delete Scope

No description available

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return ApiScopesServiceDeleteScopeRequest
*/
func (a *ScopesServiceAPIService) ScopesServiceDeleteScope(ctx context.Context, id string) ApiScopesServiceDeleteScopeRequest {
	return ApiScopesServiceDeleteScopeRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return map[string]interface{}
func (a *ScopesServiceAPIService) ScopesServiceDeleteScopeExecute(r ApiScopesServiceDeleteScopeRequest) (map[string]interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  map[string]interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ScopesServiceAPIService.ScopesServiceDeleteScope")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/scopes/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiScopesServiceGetTeamScopesRequest struct {
	ctx context.Context
	ApiService ScopesServiceAPI
}

func (r ApiScopesServiceGetTeamScopesRequest) Execute() (*ComCoralogixapisScopesV1GetScopesResponse, *http.Response, error) {
	return r.ApiService.ScopesServiceGetTeamScopesExecute(r)
}

/*
ScopesServiceGetTeamScopes Get Team Scopes

No description available

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiScopesServiceGetTeamScopesRequest
*/
func (a *ScopesServiceAPIService) ScopesServiceGetTeamScopes(ctx context.Context) ApiScopesServiceGetTeamScopesRequest {
	return ApiScopesServiceGetTeamScopesRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ComCoralogixapisScopesV1GetScopesResponse
func (a *ScopesServiceAPIService) ScopesServiceGetTeamScopesExecute(r ApiScopesServiceGetTeamScopesRequest) (*ComCoralogixapisScopesV1GetScopesResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ComCoralogixapisScopesV1GetScopesResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ScopesServiceAPIService.ScopesServiceGetTeamScopes")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/scopes/list"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiScopesServiceGetTeamScopesByIdsRequest struct {
	ctx context.Context
	ApiService ScopesServiceAPI
}

func (r ApiScopesServiceGetTeamScopesByIdsRequest) Execute() (*ComCoralogixapisScopesV1GetScopesResponse, *http.Response, error) {
	return r.ApiService.ScopesServiceGetTeamScopesByIdsExecute(r)
}

/*
ScopesServiceGetTeamScopesByIds Get Team Scopes By Ids

No description available

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiScopesServiceGetTeamScopesByIdsRequest
*/
func (a *ScopesServiceAPIService) ScopesServiceGetTeamScopesByIds(ctx context.Context) ApiScopesServiceGetTeamScopesByIdsRequest {
	return ApiScopesServiceGetTeamScopesByIdsRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ComCoralogixapisScopesV1GetScopesResponse
func (a *ScopesServiceAPIService) ScopesServiceGetTeamScopesByIdsExecute(r ApiScopesServiceGetTeamScopesByIdsRequest) (*ComCoralogixapisScopesV1GetScopesResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ComCoralogixapisScopesV1GetScopesResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ScopesServiceAPIService.ScopesServiceGetTeamScopesByIds")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/scopes"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiScopesServiceUpdateScopeRequest struct {
	ctx context.Context
	ApiService ScopesServiceAPI
	updateScopeRequest *UpdateScopeRequest
}

func (r ApiScopesServiceUpdateScopeRequest) UpdateScopeRequest(updateScopeRequest UpdateScopeRequest) ApiScopesServiceUpdateScopeRequest {
	r.updateScopeRequest = &updateScopeRequest
	return r
}

func (r ApiScopesServiceUpdateScopeRequest) Execute() (*ComCoralogixapisScopesV1UpdateScopeResponse, *http.Response, error) {
	return r.ApiService.ScopesServiceUpdateScopeExecute(r)
}

/*
ScopesServiceUpdateScope Update Scope

No description available

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiScopesServiceUpdateScopeRequest
*/
func (a *ScopesServiceAPIService) ScopesServiceUpdateScope(ctx context.Context) ApiScopesServiceUpdateScopeRequest {
	return ApiScopesServiceUpdateScopeRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ComCoralogixapisScopesV1UpdateScopeResponse
func (a *ScopesServiceAPIService) ScopesServiceUpdateScopeExecute(r ApiScopesServiceUpdateScopeRequest) (*ComCoralogixapisScopesV1UpdateScopeResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ComCoralogixapisScopesV1UpdateScopeResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ScopesServiceAPIService.ScopesServiceUpdateScope")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/scopes"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.updateScopeRequest
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
