/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ComCoralogixapisDashboardsV1CommonLogsAggregation - struct for ComCoralogixapisDashboardsV1CommonLogsAggregation
type ComCoralogixapisDashboardsV1CommonLogsAggregation struct {
	ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf *ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf
	ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1 *ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1
	ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2 *ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2
	ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3 *ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3
	ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4 *ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4
	ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5 *ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5
	ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6 *ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6
}

// ComCoralogixapisDashboardsV1CommonLogsAggregationOneOfAsComCoralogixapisDashboardsV1CommonLogsAggregation is a convenience function that returns ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf wrapped in ComCoralogixapisDashboardsV1CommonLogsAggregation
func ComCoralogixapisDashboardsV1CommonLogsAggregationOneOfAsComCoralogixapisDashboardsV1CommonLogsAggregation(v *ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf) ComCoralogixapisDashboardsV1CommonLogsAggregation {
	return ComCoralogixapisDashboardsV1CommonLogsAggregation{
		ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf: v,
	}
}

// ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1AsComCoralogixapisDashboardsV1CommonLogsAggregation is a convenience function that returns ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1 wrapped in ComCoralogixapisDashboardsV1CommonLogsAggregation
func ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1AsComCoralogixapisDashboardsV1CommonLogsAggregation(v *ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1) ComCoralogixapisDashboardsV1CommonLogsAggregation {
	return ComCoralogixapisDashboardsV1CommonLogsAggregation{
		ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1: v,
	}
}

// ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2AsComCoralogixapisDashboardsV1CommonLogsAggregation is a convenience function that returns ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2 wrapped in ComCoralogixapisDashboardsV1CommonLogsAggregation
func ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2AsComCoralogixapisDashboardsV1CommonLogsAggregation(v *ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2) ComCoralogixapisDashboardsV1CommonLogsAggregation {
	return ComCoralogixapisDashboardsV1CommonLogsAggregation{
		ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2: v,
	}
}

// ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3AsComCoralogixapisDashboardsV1CommonLogsAggregation is a convenience function that returns ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3 wrapped in ComCoralogixapisDashboardsV1CommonLogsAggregation
func ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3AsComCoralogixapisDashboardsV1CommonLogsAggregation(v *ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3) ComCoralogixapisDashboardsV1CommonLogsAggregation {
	return ComCoralogixapisDashboardsV1CommonLogsAggregation{
		ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3: v,
	}
}

// ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4AsComCoralogixapisDashboardsV1CommonLogsAggregation is a convenience function that returns ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4 wrapped in ComCoralogixapisDashboardsV1CommonLogsAggregation
func ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4AsComCoralogixapisDashboardsV1CommonLogsAggregation(v *ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4) ComCoralogixapisDashboardsV1CommonLogsAggregation {
	return ComCoralogixapisDashboardsV1CommonLogsAggregation{
		ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4: v,
	}
}

// ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5AsComCoralogixapisDashboardsV1CommonLogsAggregation is a convenience function that returns ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5 wrapped in ComCoralogixapisDashboardsV1CommonLogsAggregation
func ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5AsComCoralogixapisDashboardsV1CommonLogsAggregation(v *ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5) ComCoralogixapisDashboardsV1CommonLogsAggregation {
	return ComCoralogixapisDashboardsV1CommonLogsAggregation{
		ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5: v,
	}
}

// ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6AsComCoralogixapisDashboardsV1CommonLogsAggregation is a convenience function that returns ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6 wrapped in ComCoralogixapisDashboardsV1CommonLogsAggregation
func ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6AsComCoralogixapisDashboardsV1CommonLogsAggregation(v *ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6) ComCoralogixapisDashboardsV1CommonLogsAggregation {
	return ComCoralogixapisDashboardsV1CommonLogsAggregation{
		ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ComCoralogixapisDashboardsV1CommonLogsAggregation) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf
	err = newStrictDecoder(data).Decode(&dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf)
	if err == nil {
		jsonComCoralogixapisDashboardsV1CommonLogsAggregationOneOf, _ := json.Marshal(dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf)
		if string(jsonComCoralogixapisDashboardsV1CommonLogsAggregationOneOf) == "{}" { // empty struct
			dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf = nil
		} else {
			if err = validator.Validate(dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf); err != nil {
				dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf = nil
	}

	// try to unmarshal data into ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1
	err = newStrictDecoder(data).Decode(&dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1)
	if err == nil {
		jsonComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1, _ := json.Marshal(dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1)
		if string(jsonComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1) == "{}" { // empty struct
			dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1 = nil
		} else {
			if err = validator.Validate(dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1); err != nil {
				dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1 = nil
	}

	// try to unmarshal data into ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2
	err = newStrictDecoder(data).Decode(&dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2)
	if err == nil {
		jsonComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2, _ := json.Marshal(dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2)
		if string(jsonComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2) == "{}" { // empty struct
			dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2 = nil
		} else {
			if err = validator.Validate(dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2); err != nil {
				dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2 = nil
	}

	// try to unmarshal data into ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3
	err = newStrictDecoder(data).Decode(&dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3)
	if err == nil {
		jsonComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3, _ := json.Marshal(dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3)
		if string(jsonComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3) == "{}" { // empty struct
			dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3 = nil
		} else {
			if err = validator.Validate(dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3); err != nil {
				dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3 = nil
	}

	// try to unmarshal data into ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4
	err = newStrictDecoder(data).Decode(&dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4)
	if err == nil {
		jsonComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4, _ := json.Marshal(dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4)
		if string(jsonComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4) == "{}" { // empty struct
			dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4 = nil
		} else {
			if err = validator.Validate(dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4); err != nil {
				dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4 = nil
	}

	// try to unmarshal data into ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5
	err = newStrictDecoder(data).Decode(&dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5)
	if err == nil {
		jsonComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5, _ := json.Marshal(dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5)
		if string(jsonComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5) == "{}" { // empty struct
			dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5 = nil
		} else {
			if err = validator.Validate(dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5); err != nil {
				dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5 = nil
	}

	// try to unmarshal data into ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6
	err = newStrictDecoder(data).Decode(&dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6)
	if err == nil {
		jsonComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6, _ := json.Marshal(dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6)
		if string(jsonComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6) == "{}" { // empty struct
			dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6 = nil
		} else {
			if err = validator.Validate(dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6); err != nil {
				dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf = nil
		dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1 = nil
		dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2 = nil
		dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3 = nil
		dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4 = nil
		dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5 = nil
		dst.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ComCoralogixapisDashboardsV1CommonLogsAggregation)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ComCoralogixapisDashboardsV1CommonLogsAggregation)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ComCoralogixapisDashboardsV1CommonLogsAggregation) MarshalJSON() ([]byte, error) {
	if src.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf != nil {
		return json.Marshal(&src.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf)
	}

	if src.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1 != nil {
		return json.Marshal(&src.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1)
	}

	if src.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2 != nil {
		return json.Marshal(&src.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2)
	}

	if src.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3 != nil {
		return json.Marshal(&src.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3)
	}

	if src.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4 != nil {
		return json.Marshal(&src.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4)
	}

	if src.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5 != nil {
		return json.Marshal(&src.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5)
	}

	if src.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6 != nil {
		return json.Marshal(&src.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ComCoralogixapisDashboardsV1CommonLogsAggregation) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf != nil {
		return obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf
	}

	if obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1 != nil {
		return obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1
	}

	if obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2 != nil {
		return obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2
	}

	if obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3 != nil {
		return obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3
	}

	if obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4 != nil {
		return obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4
	}

	if obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5 != nil {
		return obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5
	}

	if obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6 != nil {
		return obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ComCoralogixapisDashboardsV1CommonLogsAggregation) GetActualInstanceValue() (interface{}) {
	if obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf != nil {
		return *obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf
	}

	if obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1 != nil {
		return *obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf1
	}

	if obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2 != nil {
		return *obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf2
	}

	if obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3 != nil {
		return *obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf3
	}

	if obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4 != nil {
		return *obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf4
	}

	if obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5 != nil {
		return *obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf5
	}

	if obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6 != nil {
		return *obj.ComCoralogixapisDashboardsV1CommonLogsAggregationOneOf6
	}

	// all schemas are nil
	return nil
}

type NullableComCoralogixapisDashboardsV1CommonLogsAggregation struct {
	value *ComCoralogixapisDashboardsV1CommonLogsAggregation
	isSet bool
}

func (v NullableComCoralogixapisDashboardsV1CommonLogsAggregation) Get() *ComCoralogixapisDashboardsV1CommonLogsAggregation {
	return v.value
}

func (v *NullableComCoralogixapisDashboardsV1CommonLogsAggregation) Set(val *ComCoralogixapisDashboardsV1CommonLogsAggregation) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixapisDashboardsV1CommonLogsAggregation) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixapisDashboardsV1CommonLogsAggregation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixapisDashboardsV1CommonLogsAggregation(val *ComCoralogixapisDashboardsV1CommonLogsAggregation) *NullableComCoralogixapisDashboardsV1CommonLogsAggregation {
	return &NullableComCoralogixapisDashboardsV1CommonLogsAggregation{value: val, isSet: true}
}

func (v NullableComCoralogixapisDashboardsV1CommonLogsAggregation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixapisDashboardsV1CommonLogsAggregation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


