/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery - struct for ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery
type ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery struct {
	ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf *ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf
	ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1 *ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1
	ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2 *ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2
	ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3 *ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3
}

// ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOfAsComCoralogixapisDashboardsV1AstWidgetsHexagonQuery is a convenience function that returns ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf wrapped in ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery
func ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOfAsComCoralogixapisDashboardsV1AstWidgetsHexagonQuery(v *ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf) ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery {
	return ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery{
		ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf: v,
	}
}

// ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1AsComCoralogixapisDashboardsV1AstWidgetsHexagonQuery is a convenience function that returns ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1 wrapped in ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery
func ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1AsComCoralogixapisDashboardsV1AstWidgetsHexagonQuery(v *ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1) ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery {
	return ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery{
		ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1: v,
	}
}

// ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2AsComCoralogixapisDashboardsV1AstWidgetsHexagonQuery is a convenience function that returns ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2 wrapped in ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery
func ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2AsComCoralogixapisDashboardsV1AstWidgetsHexagonQuery(v *ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2) ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery {
	return ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery{
		ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2: v,
	}
}

// ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3AsComCoralogixapisDashboardsV1AstWidgetsHexagonQuery is a convenience function that returns ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3 wrapped in ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery
func ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3AsComCoralogixapisDashboardsV1AstWidgetsHexagonQuery(v *ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3) ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery {
	return ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery{
		ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf
	err = newStrictDecoder(data).Decode(&dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf)
	if err == nil {
		jsonComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf, _ := json.Marshal(dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf)
		if string(jsonComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf) == "{}" { // empty struct
			dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf = nil
		} else {
			if err = validator.Validate(dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf); err != nil {
				dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf = nil
	}

	// try to unmarshal data into ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1
	err = newStrictDecoder(data).Decode(&dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1)
	if err == nil {
		jsonComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1, _ := json.Marshal(dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1)
		if string(jsonComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1) == "{}" { // empty struct
			dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1 = nil
		} else {
			if err = validator.Validate(dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1); err != nil {
				dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1 = nil
	}

	// try to unmarshal data into ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2
	err = newStrictDecoder(data).Decode(&dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2)
	if err == nil {
		jsonComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2, _ := json.Marshal(dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2)
		if string(jsonComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2) == "{}" { // empty struct
			dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2 = nil
		} else {
			if err = validator.Validate(dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2); err != nil {
				dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2 = nil
	}

	// try to unmarshal data into ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3
	err = newStrictDecoder(data).Decode(&dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3)
	if err == nil {
		jsonComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3, _ := json.Marshal(dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3)
		if string(jsonComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3) == "{}" { // empty struct
			dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3 = nil
		} else {
			if err = validator.Validate(dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3); err != nil {
				dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf = nil
		dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1 = nil
		dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2 = nil
		dst.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery) MarshalJSON() ([]byte, error) {
	if src.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf != nil {
		return json.Marshal(&src.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf)
	}

	if src.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1 != nil {
		return json.Marshal(&src.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1)
	}

	if src.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2 != nil {
		return json.Marshal(&src.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2)
	}

	if src.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3 != nil {
		return json.Marshal(&src.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf != nil {
		return obj.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf
	}

	if obj.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1 != nil {
		return obj.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1
	}

	if obj.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2 != nil {
		return obj.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2
	}

	if obj.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3 != nil {
		return obj.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery) GetActualInstanceValue() (interface{}) {
	if obj.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf != nil {
		return *obj.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf
	}

	if obj.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1 != nil {
		return *obj.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf1
	}

	if obj.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2 != nil {
		return *obj.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf2
	}

	if obj.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3 != nil {
		return *obj.ComCoralogixapisDashboardsV1AstWidgetsHexagonQueryOneOf3
	}

	// all schemas are nil
	return nil
}

type NullableComCoralogixapisDashboardsV1AstWidgetsHexagonQuery struct {
	value *ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery
	isSet bool
}

func (v NullableComCoralogixapisDashboardsV1AstWidgetsHexagonQuery) Get() *ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery {
	return v.value
}

func (v *NullableComCoralogixapisDashboardsV1AstWidgetsHexagonQuery) Set(val *ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixapisDashboardsV1AstWidgetsHexagonQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixapisDashboardsV1AstWidgetsHexagonQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixapisDashboardsV1AstWidgetsHexagonQuery(val *ComCoralogixapisDashboardsV1AstWidgetsHexagonQuery) *NullableComCoralogixapisDashboardsV1AstWidgetsHexagonQuery {
	return &NullableComCoralogixapisDashboardsV1AstWidgetsHexagonQuery{value: val, isSet: true}
}

func (v NullableComCoralogixapisDashboardsV1AstWidgetsHexagonQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixapisDashboardsV1AstWidgetsHexagonQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


