/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
)

// checks if the ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet{}

// ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet struct for ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet
type ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet struct {
	Groups []ComCoralogixapisMetricsRuleManagerV1InRuleGroup `json:"groups,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet instantiates a new ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet() *ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet {
	this := ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet{}
	return &this
}

// NewComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSetWithDefaults instantiates a new ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSetWithDefaults() *ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet {
	this := ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet{}
	return &this
}

// GetGroups returns the Groups field value if set, zero value otherwise.
func (o *ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet) GetGroups() []ComCoralogixapisMetricsRuleManagerV1InRuleGroup {
	if o == nil || IsNil(o.Groups) {
		var ret []ComCoralogixapisMetricsRuleManagerV1InRuleGroup
		return ret
	}
	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet) GetGroupsOk() ([]ComCoralogixapisMetricsRuleManagerV1InRuleGroup, bool) {
	if o == nil || IsNil(o.Groups) {
		return nil, false
	}
	return o.Groups, true
}

// HasGroups returns a boolean if a field has been set.
func (o *ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet) HasGroups() bool {
	if o != nil && !IsNil(o.Groups) {
		return true
	}

	return false
}

// SetGroups gets a reference to the given []ComCoralogixapisMetricsRuleManagerV1InRuleGroup and assigns it to the Groups field.
func (o *ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet) SetGroups(v []ComCoralogixapisMetricsRuleManagerV1InRuleGroup) {
	o.Groups = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet) SetName(v string) {
	o.Name = &v
}

func (o ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Groups) {
		toSerialize["groups"] = o.Groups
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet struct {
	value *ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet
	isSet bool
}

func (v NullableComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet) Get() *ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet {
	return v.value
}

func (v *NullableComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet) Set(val *ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet(val *ComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet) *NullableComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet {
	return &NullableComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet{value: val, isSet: true}
}

func (v NullableComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixapisMetricsRuleManagerV1CreateRuleGroupSet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


