/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
)

// checks if the ComCoralogixapisAlertsV3PriorityCount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComCoralogixapisAlertsV3PriorityCount{}

// ComCoralogixapisAlertsV3PriorityCount Count for a specific alert priority
type ComCoralogixapisAlertsV3PriorityCount struct {
	// The count for this alert priority
	Count *int64 `json:"count,omitempty"`
	// The alert priority
	Priority *string `json:"priority,omitempty"`
}

// NewComCoralogixapisAlertsV3PriorityCount instantiates a new ComCoralogixapisAlertsV3PriorityCount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComCoralogixapisAlertsV3PriorityCount() *ComCoralogixapisAlertsV3PriorityCount {
	this := ComCoralogixapisAlertsV3PriorityCount{}
	return &this
}

// NewComCoralogixapisAlertsV3PriorityCountWithDefaults instantiates a new ComCoralogixapisAlertsV3PriorityCount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComCoralogixapisAlertsV3PriorityCountWithDefaults() *ComCoralogixapisAlertsV3PriorityCount {
	this := ComCoralogixapisAlertsV3PriorityCount{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *ComCoralogixapisAlertsV3PriorityCount) GetCount() int64 {
	if o == nil || IsNil(o.Count) {
		var ret int64
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV3PriorityCount) GetCountOk() (*int64, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *ComCoralogixapisAlertsV3PriorityCount) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int64 and assigns it to the Count field.
func (o *ComCoralogixapisAlertsV3PriorityCount) SetCount(v int64) {
	o.Count = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *ComCoralogixapisAlertsV3PriorityCount) GetPriority() string {
	if o == nil || IsNil(o.Priority) {
		var ret string
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV3PriorityCount) GetPriorityOk() (*string, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *ComCoralogixapisAlertsV3PriorityCount) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given string and assigns it to the Priority field.
func (o *ComCoralogixapisAlertsV3PriorityCount) SetPriority(v string) {
	o.Priority = &v
}

func (o ComCoralogixapisAlertsV3PriorityCount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComCoralogixapisAlertsV3PriorityCount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	return toSerialize, nil
}

type NullableComCoralogixapisAlertsV3PriorityCount struct {
	value *ComCoralogixapisAlertsV3PriorityCount
	isSet bool
}

func (v NullableComCoralogixapisAlertsV3PriorityCount) Get() *ComCoralogixapisAlertsV3PriorityCount {
	return v.value
}

func (v *NullableComCoralogixapisAlertsV3PriorityCount) Set(val *ComCoralogixapisAlertsV3PriorityCount) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixapisAlertsV3PriorityCount) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixapisAlertsV3PriorityCount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixapisAlertsV3PriorityCount(val *ComCoralogixapisAlertsV3PriorityCount) *NullableComCoralogixapisAlertsV3PriorityCount {
	return &NullableComCoralogixapisAlertsV3PriorityCount{value: val, isSet: true}
}

func (v NullableComCoralogixapisAlertsV3PriorityCount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixapisAlertsV3PriorityCount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


