/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
)

// checks if the ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry{}

// ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry struct for ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry
type ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry struct {
	Key *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewComCoralogixIntegrationsV1IntegrationStatusDetailsEntry instantiates a new ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComCoralogixIntegrationsV1IntegrationStatusDetailsEntry() *ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry {
	this := ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry{}
	return &this
}

// NewComCoralogixIntegrationsV1IntegrationStatusDetailsEntryWithDefaults instantiates a new ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComCoralogixIntegrationsV1IntegrationStatusDetailsEntryWithDefaults() *ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry {
	this := ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry) SetKey(v string) {
	o.Key = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry) SetValue(v string) {
	o.Value = &v
}

func (o ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableComCoralogixIntegrationsV1IntegrationStatusDetailsEntry struct {
	value *ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry
	isSet bool
}

func (v NullableComCoralogixIntegrationsV1IntegrationStatusDetailsEntry) Get() *ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry {
	return v.value
}

func (v *NullableComCoralogixIntegrationsV1IntegrationStatusDetailsEntry) Set(val *ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixIntegrationsV1IntegrationStatusDetailsEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixIntegrationsV1IntegrationStatusDetailsEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixIntegrationsV1IntegrationStatusDetailsEntry(val *ComCoralogixIntegrationsV1IntegrationStatusDetailsEntry) *NullableComCoralogixIntegrationsV1IntegrationStatusDetailsEntry {
	return &NullableComCoralogixIntegrationsV1IntegrationStatusDetailsEntry{value: val, isSet: true}
}

func (v NullableComCoralogixIntegrationsV1IntegrationStatusDetailsEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixIntegrationsV1IntegrationStatusDetailsEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


