/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
)

// checks if the ComCoralogixapisAlertsV4SearchDetailsInterval type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComCoralogixapisAlertsV4SearchDetailsInterval{}

// ComCoralogixapisAlertsV4SearchDetailsInterval struct for ComCoralogixapisAlertsV4SearchDetailsInterval
type ComCoralogixapisAlertsV4SearchDetailsInterval struct {
	DurationMs *string `json:"durationMs,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewComCoralogixapisAlertsV4SearchDetailsInterval instantiates a new ComCoralogixapisAlertsV4SearchDetailsInterval object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComCoralogixapisAlertsV4SearchDetailsInterval() *ComCoralogixapisAlertsV4SearchDetailsInterval {
	this := ComCoralogixapisAlertsV4SearchDetailsInterval{}
	return &this
}

// NewComCoralogixapisAlertsV4SearchDetailsIntervalWithDefaults instantiates a new ComCoralogixapisAlertsV4SearchDetailsInterval object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComCoralogixapisAlertsV4SearchDetailsIntervalWithDefaults() *ComCoralogixapisAlertsV4SearchDetailsInterval {
	this := ComCoralogixapisAlertsV4SearchDetailsInterval{}
	return &this
}

// GetDurationMs returns the DurationMs field value if set, zero value otherwise.
func (o *ComCoralogixapisAlertsV4SearchDetailsInterval) GetDurationMs() string {
	if o == nil || IsNil(o.DurationMs) {
		var ret string
		return ret
	}
	return *o.DurationMs
}

// GetDurationMsOk returns a tuple with the DurationMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV4SearchDetailsInterval) GetDurationMsOk() (*string, bool) {
	if o == nil || IsNil(o.DurationMs) {
		return nil, false
	}
	return o.DurationMs, true
}

// HasDurationMs returns a boolean if a field has been set.
func (o *ComCoralogixapisAlertsV4SearchDetailsInterval) HasDurationMs() bool {
	if o != nil && !IsNil(o.DurationMs) {
		return true
	}

	return false
}

// SetDurationMs gets a reference to the given string and assigns it to the DurationMs field.
func (o *ComCoralogixapisAlertsV4SearchDetailsInterval) SetDurationMs(v string) {
	o.DurationMs = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ComCoralogixapisAlertsV4SearchDetailsInterval) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV4SearchDetailsInterval) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ComCoralogixapisAlertsV4SearchDetailsInterval) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ComCoralogixapisAlertsV4SearchDetailsInterval) SetName(v string) {
	o.Name = &v
}

func (o ComCoralogixapisAlertsV4SearchDetailsInterval) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComCoralogixapisAlertsV4SearchDetailsInterval) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DurationMs) {
		toSerialize["durationMs"] = o.DurationMs
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableComCoralogixapisAlertsV4SearchDetailsInterval struct {
	value *ComCoralogixapisAlertsV4SearchDetailsInterval
	isSet bool
}

func (v NullableComCoralogixapisAlertsV4SearchDetailsInterval) Get() *ComCoralogixapisAlertsV4SearchDetailsInterval {
	return v.value
}

func (v *NullableComCoralogixapisAlertsV4SearchDetailsInterval) Set(val *ComCoralogixapisAlertsV4SearchDetailsInterval) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixapisAlertsV4SearchDetailsInterval) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixapisAlertsV4SearchDetailsInterval) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixapisAlertsV4SearchDetailsInterval(val *ComCoralogixapisAlertsV4SearchDetailsInterval) *NullableComCoralogixapisAlertsV4SearchDetailsInterval {
	return &NullableComCoralogixapisAlertsV4SearchDetailsInterval{value: val, isSet: true}
}

func (v NullableComCoralogixapisAlertsV4SearchDetailsInterval) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixapisAlertsV4SearchDetailsInterval) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


