/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
)

// checks if the ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1{}

// ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1 struct for ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1
type ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1 struct {
	Description *string `json:"description,omitempty"`
	Name *string `json:"name,omitempty"`
	ParentRoleName *string `json:"parentRoleName,omitempty"`
	Permissions []string `json:"permissions,omitempty"`
	TeamId *int64 `json:"teamId,omitempty"`
}

// NewComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1 instantiates a new ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1() *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1 {
	this := ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1{}
	return &this
}

// NewComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1WithDefaults instantiates a new ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1WithDefaults() *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1 {
	this := ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) SetName(v string) {
	o.Name = &v
}

// GetParentRoleName returns the ParentRoleName field value if set, zero value otherwise.
func (o *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) GetParentRoleName() string {
	if o == nil || IsNil(o.ParentRoleName) {
		var ret string
		return ret
	}
	return *o.ParentRoleName
}

// GetParentRoleNameOk returns a tuple with the ParentRoleName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) GetParentRoleNameOk() (*string, bool) {
	if o == nil || IsNil(o.ParentRoleName) {
		return nil, false
	}
	return o.ParentRoleName, true
}

// HasParentRoleName returns a boolean if a field has been set.
func (o *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) HasParentRoleName() bool {
	if o != nil && !IsNil(o.ParentRoleName) {
		return true
	}

	return false
}

// SetParentRoleName gets a reference to the given string and assigns it to the ParentRoleName field.
func (o *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) SetParentRoleName(v string) {
	o.ParentRoleName = &v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) GetPermissions() []string {
	if o == nil || IsNil(o.Permissions) {
		var ret []string
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) GetPermissionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given []string and assigns it to the Permissions field.
func (o *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) SetPermissions(v []string) {
	o.Permissions = v
}

// GetTeamId returns the TeamId field value if set, zero value otherwise.
func (o *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) GetTeamId() int64 {
	if o == nil || IsNil(o.TeamId) {
		var ret int64
		return ret
	}
	return *o.TeamId
}

// GetTeamIdOk returns a tuple with the TeamId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) GetTeamIdOk() (*int64, bool) {
	if o == nil || IsNil(o.TeamId) {
		return nil, false
	}
	return o.TeamId, true
}

// HasTeamId returns a boolean if a field has been set.
func (o *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) HasTeamId() bool {
	if o != nil && !IsNil(o.TeamId) {
		return true
	}

	return false
}

// SetTeamId gets a reference to the given int64 and assigns it to the TeamId field.
func (o *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) SetTeamId(v int64) {
	o.TeamId = &v
}

func (o ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ParentRoleName) {
		toSerialize["parentRoleName"] = o.ParentRoleName
	}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	if !IsNil(o.TeamId) {
		toSerialize["teamId"] = o.TeamId
	}
	return toSerialize, nil
}

type NullableComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1 struct {
	value *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1
	isSet bool
}

func (v NullableComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) Get() *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1 {
	return v.value
}

func (v *NullableComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) Set(val *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1(val *ComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) *NullableComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1 {
	return &NullableComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1{value: val, isSet: true}
}

func (v NullableComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixapisAaaRbacV2CreateRoleRequestOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


