/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
)

// checks if the ComCoralogixDatausageV2GetSpansCountResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComCoralogixDatausageV2GetSpansCountResponse{}

// ComCoralogixDatausageV2GetSpansCountResponse This data structure is used to return spans count.
type ComCoralogixDatausageV2GetSpansCountResponse struct {
	SpansCount []ComCoralogixDatausageV2SpansCount `json:"spansCount,omitempty"`
}

// NewComCoralogixDatausageV2GetSpansCountResponse instantiates a new ComCoralogixDatausageV2GetSpansCountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComCoralogixDatausageV2GetSpansCountResponse() *ComCoralogixDatausageV2GetSpansCountResponse {
	this := ComCoralogixDatausageV2GetSpansCountResponse{}
	return &this
}

// NewComCoralogixDatausageV2GetSpansCountResponseWithDefaults instantiates a new ComCoralogixDatausageV2GetSpansCountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComCoralogixDatausageV2GetSpansCountResponseWithDefaults() *ComCoralogixDatausageV2GetSpansCountResponse {
	this := ComCoralogixDatausageV2GetSpansCountResponse{}
	return &this
}

// GetSpansCount returns the SpansCount field value if set, zero value otherwise.
func (o *ComCoralogixDatausageV2GetSpansCountResponse) GetSpansCount() []ComCoralogixDatausageV2SpansCount {
	if o == nil || IsNil(o.SpansCount) {
		var ret []ComCoralogixDatausageV2SpansCount
		return ret
	}
	return o.SpansCount
}

// GetSpansCountOk returns a tuple with the SpansCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixDatausageV2GetSpansCountResponse) GetSpansCountOk() ([]ComCoralogixDatausageV2SpansCount, bool) {
	if o == nil || IsNil(o.SpansCount) {
		return nil, false
	}
	return o.SpansCount, true
}

// HasSpansCount returns a boolean if a field has been set.
func (o *ComCoralogixDatausageV2GetSpansCountResponse) HasSpansCount() bool {
	if o != nil && !IsNil(o.SpansCount) {
		return true
	}

	return false
}

// SetSpansCount gets a reference to the given []ComCoralogixDatausageV2SpansCount and assigns it to the SpansCount field.
func (o *ComCoralogixDatausageV2GetSpansCountResponse) SetSpansCount(v []ComCoralogixDatausageV2SpansCount) {
	o.SpansCount = v
}

func (o ComCoralogixDatausageV2GetSpansCountResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComCoralogixDatausageV2GetSpansCountResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SpansCount) {
		toSerialize["spansCount"] = o.SpansCount
	}
	return toSerialize, nil
}

type NullableComCoralogixDatausageV2GetSpansCountResponse struct {
	value *ComCoralogixDatausageV2GetSpansCountResponse
	isSet bool
}

func (v NullableComCoralogixDatausageV2GetSpansCountResponse) Get() *ComCoralogixDatausageV2GetSpansCountResponse {
	return v.value
}

func (v *NullableComCoralogixDatausageV2GetSpansCountResponse) Set(val *ComCoralogixDatausageV2GetSpansCountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixDatausageV2GetSpansCountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixDatausageV2GetSpansCountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixDatausageV2GetSpansCountResponse(val *ComCoralogixDatausageV2GetSpansCountResponse) *NullableComCoralogixDatausageV2GetSpansCountResponse {
	return &NullableComCoralogixDatausageV2GetSpansCountResponse{value: val, isSet: true}
}

func (v NullableComCoralogixDatausageV2GetSpansCountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixDatausageV2GetSpansCountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


