/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComCoralogixapisAlertsV3Priority type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComCoralogixapisAlertsV3Priority{}

// ComCoralogixapisAlertsV3Priority Defines the priority of an alert definition
type ComCoralogixapisAlertsV3Priority struct {
	// String representation of the priority
	Name string `json:"name"`
	// The priority of the alert definition
	Value string `json:"value"`
}

type _ComCoralogixapisAlertsV3Priority ComCoralogixapisAlertsV3Priority

// NewComCoralogixapisAlertsV3Priority instantiates a new ComCoralogixapisAlertsV3Priority object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComCoralogixapisAlertsV3Priority(name string, value string) *ComCoralogixapisAlertsV3Priority {
	this := ComCoralogixapisAlertsV3Priority{}
	this.Name = name
	this.Value = value
	return &this
}

// NewComCoralogixapisAlertsV3PriorityWithDefaults instantiates a new ComCoralogixapisAlertsV3Priority object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComCoralogixapisAlertsV3PriorityWithDefaults() *ComCoralogixapisAlertsV3Priority {
	this := ComCoralogixapisAlertsV3Priority{}
	return &this
}

// GetName returns the Name field value
func (o *ComCoralogixapisAlertsV3Priority) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV3Priority) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ComCoralogixapisAlertsV3Priority) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *ComCoralogixapisAlertsV3Priority) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV3Priority) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ComCoralogixapisAlertsV3Priority) SetValue(v string) {
	o.Value = v
}

func (o ComCoralogixapisAlertsV3Priority) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComCoralogixapisAlertsV3Priority) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *ComCoralogixapisAlertsV3Priority) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComCoralogixapisAlertsV3Priority := _ComCoralogixapisAlertsV3Priority{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComCoralogixapisAlertsV3Priority)

	if err != nil {
		return err
	}

	*o = ComCoralogixapisAlertsV3Priority(varComCoralogixapisAlertsV3Priority)

	return err
}

type NullableComCoralogixapisAlertsV3Priority struct {
	value *ComCoralogixapisAlertsV3Priority
	isSet bool
}

func (v NullableComCoralogixapisAlertsV3Priority) Get() *ComCoralogixapisAlertsV3Priority {
	return v.value
}

func (v *NullableComCoralogixapisAlertsV3Priority) Set(val *ComCoralogixapisAlertsV3Priority) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixapisAlertsV3Priority) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixapisAlertsV3Priority) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixapisAlertsV3Priority(val *ComCoralogixapisAlertsV3Priority) *NullableComCoralogixapisAlertsV3Priority {
	return &NullableComCoralogixapisAlertsV3Priority{value: val, isSet: true}
}

func (v NullableComCoralogixapisAlertsV3Priority) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixapisAlertsV3Priority) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


