/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
)

// checks if the ComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse{}

// ComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse struct for ComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse
type ComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse struct {
	Permutations []ComCoralogixapisEvents2metricsV2LabelsPermutationsCardinalityDay `json:"permutations,omitempty"`
}

// NewComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse instantiates a new ComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse() *ComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse {
	this := ComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse{}
	return &this
}

// NewComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponseWithDefaults instantiates a new ComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponseWithDefaults() *ComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse {
	this := ComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse{}
	return &this
}

// GetPermutations returns the Permutations field value if set, zero value otherwise.
func (o *ComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse) GetPermutations() []ComCoralogixapisEvents2metricsV2LabelsPermutationsCardinalityDay {
	if o == nil || IsNil(o.Permutations) {
		var ret []ComCoralogixapisEvents2metricsV2LabelsPermutationsCardinalityDay
		return ret
	}
	return o.Permutations
}

// GetPermutationsOk returns a tuple with the Permutations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse) GetPermutationsOk() ([]ComCoralogixapisEvents2metricsV2LabelsPermutationsCardinalityDay, bool) {
	if o == nil || IsNil(o.Permutations) {
		return nil, false
	}
	return o.Permutations, true
}

// HasPermutations returns a boolean if a field has been set.
func (o *ComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse) HasPermutations() bool {
	if o != nil && !IsNil(o.Permutations) {
		return true
	}

	return false
}

// SetPermutations gets a reference to the given []ComCoralogixapisEvents2metricsV2LabelsPermutationsCardinalityDay and assigns it to the Permutations field.
func (o *ComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse) SetPermutations(v []ComCoralogixapisEvents2metricsV2LabelsPermutationsCardinalityDay) {
	o.Permutations = v
}

func (o ComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Permutations) {
		toSerialize["permutations"] = o.Permutations
	}
	return toSerialize, nil
}

type NullableComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse struct {
	value *ComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse
	isSet bool
}

func (v NullableComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse) Get() *ComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse {
	return v.value
}

func (v *NullableComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse) Set(val *ComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse(val *ComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse) *NullableComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse {
	return &NullableComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse{value: val, isSet: true}
}

func (v NullableComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixapisEvents2metricsV2ListLabelsCardinalityResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


