/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
)

// checks if the ComCoralogixapisDashboardsV1CommonSpanObservationField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComCoralogixapisDashboardsV1CommonSpanObservationField{}

// ComCoralogixapisDashboardsV1CommonSpanObservationField struct for ComCoralogixapisDashboardsV1CommonSpanObservationField
type ComCoralogixapisDashboardsV1CommonSpanObservationField struct {
	Keypath []string `json:"keypath,omitempty"`
	RelationType *string `json:"relationType,omitempty"`
	Scope *string `json:"scope,omitempty"`
}

// NewComCoralogixapisDashboardsV1CommonSpanObservationField instantiates a new ComCoralogixapisDashboardsV1CommonSpanObservationField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComCoralogixapisDashboardsV1CommonSpanObservationField() *ComCoralogixapisDashboardsV1CommonSpanObservationField {
	this := ComCoralogixapisDashboardsV1CommonSpanObservationField{}
	return &this
}

// NewComCoralogixapisDashboardsV1CommonSpanObservationFieldWithDefaults instantiates a new ComCoralogixapisDashboardsV1CommonSpanObservationField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComCoralogixapisDashboardsV1CommonSpanObservationFieldWithDefaults() *ComCoralogixapisDashboardsV1CommonSpanObservationField {
	this := ComCoralogixapisDashboardsV1CommonSpanObservationField{}
	return &this
}

// GetKeypath returns the Keypath field value if set, zero value otherwise.
func (o *ComCoralogixapisDashboardsV1CommonSpanObservationField) GetKeypath() []string {
	if o == nil || IsNil(o.Keypath) {
		var ret []string
		return ret
	}
	return o.Keypath
}

// GetKeypathOk returns a tuple with the Keypath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisDashboardsV1CommonSpanObservationField) GetKeypathOk() ([]string, bool) {
	if o == nil || IsNil(o.Keypath) {
		return nil, false
	}
	return o.Keypath, true
}

// HasKeypath returns a boolean if a field has been set.
func (o *ComCoralogixapisDashboardsV1CommonSpanObservationField) HasKeypath() bool {
	if o != nil && !IsNil(o.Keypath) {
		return true
	}

	return false
}

// SetKeypath gets a reference to the given []string and assigns it to the Keypath field.
func (o *ComCoralogixapisDashboardsV1CommonSpanObservationField) SetKeypath(v []string) {
	o.Keypath = v
}

// GetRelationType returns the RelationType field value if set, zero value otherwise.
func (o *ComCoralogixapisDashboardsV1CommonSpanObservationField) GetRelationType() string {
	if o == nil || IsNil(o.RelationType) {
		var ret string
		return ret
	}
	return *o.RelationType
}

// GetRelationTypeOk returns a tuple with the RelationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisDashboardsV1CommonSpanObservationField) GetRelationTypeOk() (*string, bool) {
	if o == nil || IsNil(o.RelationType) {
		return nil, false
	}
	return o.RelationType, true
}

// HasRelationType returns a boolean if a field has been set.
func (o *ComCoralogixapisDashboardsV1CommonSpanObservationField) HasRelationType() bool {
	if o != nil && !IsNil(o.RelationType) {
		return true
	}

	return false
}

// SetRelationType gets a reference to the given string and assigns it to the RelationType field.
func (o *ComCoralogixapisDashboardsV1CommonSpanObservationField) SetRelationType(v string) {
	o.RelationType = &v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *ComCoralogixapisDashboardsV1CommonSpanObservationField) GetScope() string {
	if o == nil || IsNil(o.Scope) {
		var ret string
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisDashboardsV1CommonSpanObservationField) GetScopeOk() (*string, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *ComCoralogixapisDashboardsV1CommonSpanObservationField) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given string and assigns it to the Scope field.
func (o *ComCoralogixapisDashboardsV1CommonSpanObservationField) SetScope(v string) {
	o.Scope = &v
}

func (o ComCoralogixapisDashboardsV1CommonSpanObservationField) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComCoralogixapisDashboardsV1CommonSpanObservationField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Keypath) {
		toSerialize["keypath"] = o.Keypath
	}
	if !IsNil(o.RelationType) {
		toSerialize["relationType"] = o.RelationType
	}
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	return toSerialize, nil
}

type NullableComCoralogixapisDashboardsV1CommonSpanObservationField struct {
	value *ComCoralogixapisDashboardsV1CommonSpanObservationField
	isSet bool
}

func (v NullableComCoralogixapisDashboardsV1CommonSpanObservationField) Get() *ComCoralogixapisDashboardsV1CommonSpanObservationField {
	return v.value
}

func (v *NullableComCoralogixapisDashboardsV1CommonSpanObservationField) Set(val *ComCoralogixapisDashboardsV1CommonSpanObservationField) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixapisDashboardsV1CommonSpanObservationField) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixapisDashboardsV1CommonSpanObservationField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixapisDashboardsV1CommonSpanObservationField(val *ComCoralogixapisDashboardsV1CommonSpanObservationField) *NullableComCoralogixapisDashboardsV1CommonSpanObservationField {
	return &NullableComCoralogixapisDashboardsV1CommonSpanObservationField{value: val, isSet: true}
}

func (v NullableComCoralogixapisDashboardsV1CommonSpanObservationField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixapisDashboardsV1CommonSpanObservationField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


