/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
)

// checks if the ComCoralogixPermissionsV1OrganizationId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComCoralogixPermissionsV1OrganizationId{}

// ComCoralogixPermissionsV1OrganizationId struct for ComCoralogixPermissionsV1OrganizationId
type ComCoralogixPermissionsV1OrganizationId struct {
	Id *string `json:"id,omitempty"`
}

// NewComCoralogixPermissionsV1OrganizationId instantiates a new ComCoralogixPermissionsV1OrganizationId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComCoralogixPermissionsV1OrganizationId() *ComCoralogixPermissionsV1OrganizationId {
	this := ComCoralogixPermissionsV1OrganizationId{}
	return &this
}

// NewComCoralogixPermissionsV1OrganizationIdWithDefaults instantiates a new ComCoralogixPermissionsV1OrganizationId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComCoralogixPermissionsV1OrganizationIdWithDefaults() *ComCoralogixPermissionsV1OrganizationId {
	this := ComCoralogixPermissionsV1OrganizationId{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ComCoralogixPermissionsV1OrganizationId) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixPermissionsV1OrganizationId) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ComCoralogixPermissionsV1OrganizationId) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ComCoralogixPermissionsV1OrganizationId) SetId(v string) {
	o.Id = &v
}

func (o ComCoralogixPermissionsV1OrganizationId) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComCoralogixPermissionsV1OrganizationId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableComCoralogixPermissionsV1OrganizationId struct {
	value *ComCoralogixPermissionsV1OrganizationId
	isSet bool
}

func (v NullableComCoralogixPermissionsV1OrganizationId) Get() *ComCoralogixPermissionsV1OrganizationId {
	return v.value
}

func (v *NullableComCoralogixPermissionsV1OrganizationId) Set(val *ComCoralogixPermissionsV1OrganizationId) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixPermissionsV1OrganizationId) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixPermissionsV1OrganizationId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixPermissionsV1OrganizationId(val *ComCoralogixPermissionsV1OrganizationId) *NullableComCoralogixPermissionsV1OrganizationId {
	return &NullableComCoralogixPermissionsV1OrganizationId{value: val, isSet: true}
}

func (v NullableComCoralogixPermissionsV1OrganizationId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixPermissionsV1OrganizationId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


