/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
)

// checks if the ComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse{}

// ComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse struct for ComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse
type ComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse struct {
	Mappings []ComCoralogixGlobalMappingV1LabelMapping `json:"mappings,omitempty"`
}

// NewComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse instantiates a new ComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse() *ComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse {
	this := ComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse{}
	return &this
}

// NewComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponseWithDefaults instantiates a new ComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponseWithDefaults() *ComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse {
	this := ComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse{}
	return &this
}

// GetMappings returns the Mappings field value if set, zero value otherwise.
func (o *ComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse) GetMappings() []ComCoralogixGlobalMappingV1LabelMapping {
	if o == nil || IsNil(o.Mappings) {
		var ret []ComCoralogixGlobalMappingV1LabelMapping
		return ret
	}
	return o.Mappings
}

// GetMappingsOk returns a tuple with the Mappings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse) GetMappingsOk() ([]ComCoralogixGlobalMappingV1LabelMapping, bool) {
	if o == nil || IsNil(o.Mappings) {
		return nil, false
	}
	return o.Mappings, true
}

// HasMappings returns a boolean if a field has been set.
func (o *ComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse) HasMappings() bool {
	if o != nil && !IsNil(o.Mappings) {
		return true
	}

	return false
}

// SetMappings gets a reference to the given []ComCoralogixGlobalMappingV1LabelMapping and assigns it to the Mappings field.
func (o *ComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse) SetMappings(v []ComCoralogixGlobalMappingV1LabelMapping) {
	o.Mappings = v
}

func (o ComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Mappings) {
		toSerialize["mappings"] = o.Mappings
	}
	return toSerialize, nil
}

type NullableComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse struct {
	value *ComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse
	isSet bool
}

func (v NullableComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse) Get() *ComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse {
	return v.value
}

func (v *NullableComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse) Set(val *ComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse(val *ComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse) *NullableComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse {
	return &NullableComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse{value: val, isSet: true}
}

func (v NullableComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixGlobalMappingV1UpsertCustomLabelMappingsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


