/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComCoralogixapisAlertsV3MetricAnomalyCondition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComCoralogixapisAlertsV3MetricAnomalyCondition{}

// ComCoralogixapisAlertsV3MetricAnomalyCondition struct for ComCoralogixapisAlertsV3MetricAnomalyCondition
type ComCoralogixapisAlertsV3MetricAnomalyCondition struct {
	// The type of condition for the alert.
	ConditionType string `json:"conditionType"`
	// The percentage of the metric that must exceed the threshold to trigger the alert
	ForOverPct *int64 `json:"forOverPct,omitempty"`
	// The percentage of non-null values required to trigger the alert
	MinNonNullValuesPct int64 `json:"minNonNullValuesPct"`
	OfTheLast ComCoralogixapisAlertsV3MetricTimeWindow `json:"ofTheLast"`
	// The threshold value for the alert condition
	Threshold float64 `json:"threshold"`
}

type _ComCoralogixapisAlertsV3MetricAnomalyCondition ComCoralogixapisAlertsV3MetricAnomalyCondition

// NewComCoralogixapisAlertsV3MetricAnomalyCondition instantiates a new ComCoralogixapisAlertsV3MetricAnomalyCondition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComCoralogixapisAlertsV3MetricAnomalyCondition(conditionType string, minNonNullValuesPct int64, ofTheLast ComCoralogixapisAlertsV3MetricTimeWindow, threshold float64) *ComCoralogixapisAlertsV3MetricAnomalyCondition {
	this := ComCoralogixapisAlertsV3MetricAnomalyCondition{}
	this.ConditionType = conditionType
	this.MinNonNullValuesPct = minNonNullValuesPct
	this.OfTheLast = ofTheLast
	this.Threshold = threshold
	return &this
}

// NewComCoralogixapisAlertsV3MetricAnomalyConditionWithDefaults instantiates a new ComCoralogixapisAlertsV3MetricAnomalyCondition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComCoralogixapisAlertsV3MetricAnomalyConditionWithDefaults() *ComCoralogixapisAlertsV3MetricAnomalyCondition {
	this := ComCoralogixapisAlertsV3MetricAnomalyCondition{}
	return &this
}

// GetConditionType returns the ConditionType field value
func (o *ComCoralogixapisAlertsV3MetricAnomalyCondition) GetConditionType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConditionType
}

// GetConditionTypeOk returns a tuple with the ConditionType field value
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV3MetricAnomalyCondition) GetConditionTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConditionType, true
}

// SetConditionType sets field value
func (o *ComCoralogixapisAlertsV3MetricAnomalyCondition) SetConditionType(v string) {
	o.ConditionType = v
}

// GetForOverPct returns the ForOverPct field value if set, zero value otherwise.
func (o *ComCoralogixapisAlertsV3MetricAnomalyCondition) GetForOverPct() int64 {
	if o == nil || IsNil(o.ForOverPct) {
		var ret int64
		return ret
	}
	return *o.ForOverPct
}

// GetForOverPctOk returns a tuple with the ForOverPct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV3MetricAnomalyCondition) GetForOverPctOk() (*int64, bool) {
	if o == nil || IsNil(o.ForOverPct) {
		return nil, false
	}
	return o.ForOverPct, true
}

// HasForOverPct returns a boolean if a field has been set.
func (o *ComCoralogixapisAlertsV3MetricAnomalyCondition) HasForOverPct() bool {
	if o != nil && !IsNil(o.ForOverPct) {
		return true
	}

	return false
}

// SetForOverPct gets a reference to the given int64 and assigns it to the ForOverPct field.
func (o *ComCoralogixapisAlertsV3MetricAnomalyCondition) SetForOverPct(v int64) {
	o.ForOverPct = &v
}

// GetMinNonNullValuesPct returns the MinNonNullValuesPct field value
func (o *ComCoralogixapisAlertsV3MetricAnomalyCondition) GetMinNonNullValuesPct() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MinNonNullValuesPct
}

// GetMinNonNullValuesPctOk returns a tuple with the MinNonNullValuesPct field value
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV3MetricAnomalyCondition) GetMinNonNullValuesPctOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinNonNullValuesPct, true
}

// SetMinNonNullValuesPct sets field value
func (o *ComCoralogixapisAlertsV3MetricAnomalyCondition) SetMinNonNullValuesPct(v int64) {
	o.MinNonNullValuesPct = v
}

// GetOfTheLast returns the OfTheLast field value
func (o *ComCoralogixapisAlertsV3MetricAnomalyCondition) GetOfTheLast() ComCoralogixapisAlertsV3MetricTimeWindow {
	if o == nil {
		var ret ComCoralogixapisAlertsV3MetricTimeWindow
		return ret
	}

	return o.OfTheLast
}

// GetOfTheLastOk returns a tuple with the OfTheLast field value
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV3MetricAnomalyCondition) GetOfTheLastOk() (*ComCoralogixapisAlertsV3MetricTimeWindow, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OfTheLast, true
}

// SetOfTheLast sets field value
func (o *ComCoralogixapisAlertsV3MetricAnomalyCondition) SetOfTheLast(v ComCoralogixapisAlertsV3MetricTimeWindow) {
	o.OfTheLast = v
}

// GetThreshold returns the Threshold field value
func (o *ComCoralogixapisAlertsV3MetricAnomalyCondition) GetThreshold() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV3MetricAnomalyCondition) GetThresholdOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Threshold, true
}

// SetThreshold sets field value
func (o *ComCoralogixapisAlertsV3MetricAnomalyCondition) SetThreshold(v float64) {
	o.Threshold = v
}

func (o ComCoralogixapisAlertsV3MetricAnomalyCondition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComCoralogixapisAlertsV3MetricAnomalyCondition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["conditionType"] = o.ConditionType
	if !IsNil(o.ForOverPct) {
		toSerialize["forOverPct"] = o.ForOverPct
	}
	toSerialize["minNonNullValuesPct"] = o.MinNonNullValuesPct
	toSerialize["ofTheLast"] = o.OfTheLast
	toSerialize["threshold"] = o.Threshold
	return toSerialize, nil
}

func (o *ComCoralogixapisAlertsV3MetricAnomalyCondition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"conditionType",
		"minNonNullValuesPct",
		"ofTheLast",
		"threshold",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComCoralogixapisAlertsV3MetricAnomalyCondition := _ComCoralogixapisAlertsV3MetricAnomalyCondition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComCoralogixapisAlertsV3MetricAnomalyCondition)

	if err != nil {
		return err
	}

	*o = ComCoralogixapisAlertsV3MetricAnomalyCondition(varComCoralogixapisAlertsV3MetricAnomalyCondition)

	return err
}

type NullableComCoralogixapisAlertsV3MetricAnomalyCondition struct {
	value *ComCoralogixapisAlertsV3MetricAnomalyCondition
	isSet bool
}

func (v NullableComCoralogixapisAlertsV3MetricAnomalyCondition) Get() *ComCoralogixapisAlertsV3MetricAnomalyCondition {
	return v.value
}

func (v *NullableComCoralogixapisAlertsV3MetricAnomalyCondition) Set(val *ComCoralogixapisAlertsV3MetricAnomalyCondition) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixapisAlertsV3MetricAnomalyCondition) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixapisAlertsV3MetricAnomalyCondition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixapisAlertsV3MetricAnomalyCondition(val *ComCoralogixapisAlertsV3MetricAnomalyCondition) *NullableComCoralogixapisAlertsV3MetricAnomalyCondition {
	return &NullableComCoralogixapisAlertsV3MetricAnomalyCondition{value: val, isSet: true}
}

func (v NullableComCoralogixapisAlertsV3MetricAnomalyCondition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixapisAlertsV3MetricAnomalyCondition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


