/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ComCoralogixapisAlertsV3EventTimeRelativeMoreThan - struct for ComCoralogixapisAlertsV3EventTimeRelativeMoreThan
type ComCoralogixapisAlertsV3EventTimeRelativeMoreThan struct {
	ComCoralogixapisAlertsV3EventRatioLessThanOneOf *ComCoralogixapisAlertsV3EventRatioLessThanOneOf
	ComCoralogixapisAlertsV3EventRatioLessThanOneOf1 *ComCoralogixapisAlertsV3EventRatioLessThanOneOf1
}

// ComCoralogixapisAlertsV3EventRatioLessThanOneOfAsComCoralogixapisAlertsV3EventTimeRelativeMoreThan is a convenience function that returns ComCoralogixapisAlertsV3EventRatioLessThanOneOf wrapped in ComCoralogixapisAlertsV3EventTimeRelativeMoreThan
func ComCoralogixapisAlertsV3EventRatioLessThanOneOfAsComCoralogixapisAlertsV3EventTimeRelativeMoreThan(v *ComCoralogixapisAlertsV3EventRatioLessThanOneOf) ComCoralogixapisAlertsV3EventTimeRelativeMoreThan {
	return ComCoralogixapisAlertsV3EventTimeRelativeMoreThan{
		ComCoralogixapisAlertsV3EventRatioLessThanOneOf: v,
	}
}

// ComCoralogixapisAlertsV3EventRatioLessThanOneOf1AsComCoralogixapisAlertsV3EventTimeRelativeMoreThan is a convenience function that returns ComCoralogixapisAlertsV3EventRatioLessThanOneOf1 wrapped in ComCoralogixapisAlertsV3EventTimeRelativeMoreThan
func ComCoralogixapisAlertsV3EventRatioLessThanOneOf1AsComCoralogixapisAlertsV3EventTimeRelativeMoreThan(v *ComCoralogixapisAlertsV3EventRatioLessThanOneOf1) ComCoralogixapisAlertsV3EventTimeRelativeMoreThan {
	return ComCoralogixapisAlertsV3EventTimeRelativeMoreThan{
		ComCoralogixapisAlertsV3EventRatioLessThanOneOf1: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ComCoralogixapisAlertsV3EventTimeRelativeMoreThan) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ComCoralogixapisAlertsV3EventRatioLessThanOneOf
	err = newStrictDecoder(data).Decode(&dst.ComCoralogixapisAlertsV3EventRatioLessThanOneOf)
	if err == nil {
		jsonComCoralogixapisAlertsV3EventRatioLessThanOneOf, _ := json.Marshal(dst.ComCoralogixapisAlertsV3EventRatioLessThanOneOf)
		if string(jsonComCoralogixapisAlertsV3EventRatioLessThanOneOf) == "{}" { // empty struct
			dst.ComCoralogixapisAlertsV3EventRatioLessThanOneOf = nil
		} else {
			if err = validator.Validate(dst.ComCoralogixapisAlertsV3EventRatioLessThanOneOf); err != nil {
				dst.ComCoralogixapisAlertsV3EventRatioLessThanOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.ComCoralogixapisAlertsV3EventRatioLessThanOneOf = nil
	}

	// try to unmarshal data into ComCoralogixapisAlertsV3EventRatioLessThanOneOf1
	err = newStrictDecoder(data).Decode(&dst.ComCoralogixapisAlertsV3EventRatioLessThanOneOf1)
	if err == nil {
		jsonComCoralogixapisAlertsV3EventRatioLessThanOneOf1, _ := json.Marshal(dst.ComCoralogixapisAlertsV3EventRatioLessThanOneOf1)
		if string(jsonComCoralogixapisAlertsV3EventRatioLessThanOneOf1) == "{}" { // empty struct
			dst.ComCoralogixapisAlertsV3EventRatioLessThanOneOf1 = nil
		} else {
			if err = validator.Validate(dst.ComCoralogixapisAlertsV3EventRatioLessThanOneOf1); err != nil {
				dst.ComCoralogixapisAlertsV3EventRatioLessThanOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ComCoralogixapisAlertsV3EventRatioLessThanOneOf1 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ComCoralogixapisAlertsV3EventRatioLessThanOneOf = nil
		dst.ComCoralogixapisAlertsV3EventRatioLessThanOneOf1 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ComCoralogixapisAlertsV3EventTimeRelativeMoreThan)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ComCoralogixapisAlertsV3EventTimeRelativeMoreThan)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ComCoralogixapisAlertsV3EventTimeRelativeMoreThan) MarshalJSON() ([]byte, error) {
	if src.ComCoralogixapisAlertsV3EventRatioLessThanOneOf != nil {
		return json.Marshal(&src.ComCoralogixapisAlertsV3EventRatioLessThanOneOf)
	}

	if src.ComCoralogixapisAlertsV3EventRatioLessThanOneOf1 != nil {
		return json.Marshal(&src.ComCoralogixapisAlertsV3EventRatioLessThanOneOf1)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ComCoralogixapisAlertsV3EventTimeRelativeMoreThan) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ComCoralogixapisAlertsV3EventRatioLessThanOneOf != nil {
		return obj.ComCoralogixapisAlertsV3EventRatioLessThanOneOf
	}

	if obj.ComCoralogixapisAlertsV3EventRatioLessThanOneOf1 != nil {
		return obj.ComCoralogixapisAlertsV3EventRatioLessThanOneOf1
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ComCoralogixapisAlertsV3EventTimeRelativeMoreThan) GetActualInstanceValue() (interface{}) {
	if obj.ComCoralogixapisAlertsV3EventRatioLessThanOneOf != nil {
		return *obj.ComCoralogixapisAlertsV3EventRatioLessThanOneOf
	}

	if obj.ComCoralogixapisAlertsV3EventRatioLessThanOneOf1 != nil {
		return *obj.ComCoralogixapisAlertsV3EventRatioLessThanOneOf1
	}

	// all schemas are nil
	return nil
}

type NullableComCoralogixapisAlertsV3EventTimeRelativeMoreThan struct {
	value *ComCoralogixapisAlertsV3EventTimeRelativeMoreThan
	isSet bool
}

func (v NullableComCoralogixapisAlertsV3EventTimeRelativeMoreThan) Get() *ComCoralogixapisAlertsV3EventTimeRelativeMoreThan {
	return v.value
}

func (v *NullableComCoralogixapisAlertsV3EventTimeRelativeMoreThan) Set(val *ComCoralogixapisAlertsV3EventTimeRelativeMoreThan) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixapisAlertsV3EventTimeRelativeMoreThan) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixapisAlertsV3EventTimeRelativeMoreThan) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixapisAlertsV3EventTimeRelativeMoreThan(val *ComCoralogixapisAlertsV3EventTimeRelativeMoreThan) *NullableComCoralogixapisAlertsV3EventTimeRelativeMoreThan {
	return &NullableComCoralogixapisAlertsV3EventTimeRelativeMoreThan{value: val, isSet: true}
}

func (v NullableComCoralogixapisAlertsV3EventTimeRelativeMoreThan) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixapisAlertsV3EventTimeRelativeMoreThan) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


