/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
)

// checks if the ComCoralogixQuotaV1TogglePolicyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComCoralogixQuotaV1TogglePolicyRequest{}

// ComCoralogixQuotaV1TogglePolicyRequest struct for ComCoralogixQuotaV1TogglePolicyRequest
type ComCoralogixQuotaV1TogglePolicyRequest struct {
	Enabled *bool `json:"enabled,omitempty"`
	Id *string `json:"id,omitempty"`
}

// NewComCoralogixQuotaV1TogglePolicyRequest instantiates a new ComCoralogixQuotaV1TogglePolicyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComCoralogixQuotaV1TogglePolicyRequest() *ComCoralogixQuotaV1TogglePolicyRequest {
	this := ComCoralogixQuotaV1TogglePolicyRequest{}
	return &this
}

// NewComCoralogixQuotaV1TogglePolicyRequestWithDefaults instantiates a new ComCoralogixQuotaV1TogglePolicyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComCoralogixQuotaV1TogglePolicyRequestWithDefaults() *ComCoralogixQuotaV1TogglePolicyRequest {
	this := ComCoralogixQuotaV1TogglePolicyRequest{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *ComCoralogixQuotaV1TogglePolicyRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixQuotaV1TogglePolicyRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *ComCoralogixQuotaV1TogglePolicyRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *ComCoralogixQuotaV1TogglePolicyRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ComCoralogixQuotaV1TogglePolicyRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixQuotaV1TogglePolicyRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ComCoralogixQuotaV1TogglePolicyRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ComCoralogixQuotaV1TogglePolicyRequest) SetId(v string) {
	o.Id = &v
}

func (o ComCoralogixQuotaV1TogglePolicyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComCoralogixQuotaV1TogglePolicyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableComCoralogixQuotaV1TogglePolicyRequest struct {
	value *ComCoralogixQuotaV1TogglePolicyRequest
	isSet bool
}

func (v NullableComCoralogixQuotaV1TogglePolicyRequest) Get() *ComCoralogixQuotaV1TogglePolicyRequest {
	return v.value
}

func (v *NullableComCoralogixQuotaV1TogglePolicyRequest) Set(val *ComCoralogixQuotaV1TogglePolicyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixQuotaV1TogglePolicyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixQuotaV1TogglePolicyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixQuotaV1TogglePolicyRequest(val *ComCoralogixQuotaV1TogglePolicyRequest) *NullableComCoralogixQuotaV1TogglePolicyRequest {
	return &NullableComCoralogixQuotaV1TogglePolicyRequest{value: val, isSet: true}
}

func (v NullableComCoralogixQuotaV1TogglePolicyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixQuotaV1TogglePolicyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


