/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
)

// checks if the MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1{}

// MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1 struct for MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1
type MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1 struct {
	RetentionPolicy *ComCoralogixMetricsMetricsConfiguratorRetentionPolicyRequest `json:"retentionPolicy,omitempty"`
	S3 *ComCoralogixMetricsMetricsConfiguratorS3Config `json:"s3,omitempty"`
}

// NewMetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1 instantiates a new MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1() *MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1 {
	this := MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1{}
	return &this
}

// NewMetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1WithDefaults instantiates a new MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1WithDefaults() *MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1 {
	this := MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1{}
	return &this
}

// GetRetentionPolicy returns the RetentionPolicy field value if set, zero value otherwise.
func (o *MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1) GetRetentionPolicy() ComCoralogixMetricsMetricsConfiguratorRetentionPolicyRequest {
	if o == nil || IsNil(o.RetentionPolicy) {
		var ret ComCoralogixMetricsMetricsConfiguratorRetentionPolicyRequest
		return ret
	}
	return *o.RetentionPolicy
}

// GetRetentionPolicyOk returns a tuple with the RetentionPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1) GetRetentionPolicyOk() (*ComCoralogixMetricsMetricsConfiguratorRetentionPolicyRequest, bool) {
	if o == nil || IsNil(o.RetentionPolicy) {
		return nil, false
	}
	return o.RetentionPolicy, true
}

// HasRetentionPolicy returns a boolean if a field has been set.
func (o *MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1) HasRetentionPolicy() bool {
	if o != nil && !IsNil(o.RetentionPolicy) {
		return true
	}

	return false
}

// SetRetentionPolicy gets a reference to the given ComCoralogixMetricsMetricsConfiguratorRetentionPolicyRequest and assigns it to the RetentionPolicy field.
func (o *MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1) SetRetentionPolicy(v ComCoralogixMetricsMetricsConfiguratorRetentionPolicyRequest) {
	o.RetentionPolicy = &v
}

// GetS3 returns the S3 field value if set, zero value otherwise.
func (o *MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1) GetS3() ComCoralogixMetricsMetricsConfiguratorS3Config {
	if o == nil || IsNil(o.S3) {
		var ret ComCoralogixMetricsMetricsConfiguratorS3Config
		return ret
	}
	return *o.S3
}

// GetS3Ok returns a tuple with the S3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1) GetS3Ok() (*ComCoralogixMetricsMetricsConfiguratorS3Config, bool) {
	if o == nil || IsNil(o.S3) {
		return nil, false
	}
	return o.S3, true
}

// HasS3 returns a boolean if a field has been set.
func (o *MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1) HasS3() bool {
	if o != nil && !IsNil(o.S3) {
		return true
	}

	return false
}

// SetS3 gets a reference to the given ComCoralogixMetricsMetricsConfiguratorS3Config and assigns it to the S3 field.
func (o *MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1) SetS3(v ComCoralogixMetricsMetricsConfiguratorS3Config) {
	o.S3 = &v
}

func (o MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RetentionPolicy) {
		toSerialize["retentionPolicy"] = o.RetentionPolicy
	}
	if !IsNil(o.S3) {
		toSerialize["s3"] = o.S3
	}
	return toSerialize, nil
}

type NullableMetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1 struct {
	value *MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1
	isSet bool
}

func (v NullableMetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1) Get() *MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1 {
	return v.value
}

func (v *NullableMetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1) Set(val *MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableMetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableMetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1(val *MetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1) *NullableMetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1 {
	return &NullableMetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1{value: val, isSet: true}
}

func (v NullableMetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetricsConfiguratorPublicServiceConfigureTenantRequestOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


