/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
)

// checks if the ComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1{}

// ComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1 struct for ComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1
type ComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1 struct {
	Spans *ComCoralogixapisDashboardsV1AstWidgetsDynamicQuerySpans `json:"spans,omitempty"`
}

// NewComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1 instantiates a new ComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1() *ComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1 {
	this := ComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1{}
	return &this
}

// NewComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1WithDefaults instantiates a new ComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1WithDefaults() *ComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1 {
	this := ComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1{}
	return &this
}

// GetSpans returns the Spans field value if set, zero value otherwise.
func (o *ComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1) GetSpans() ComCoralogixapisDashboardsV1AstWidgetsDynamicQuerySpans {
	if o == nil || IsNil(o.Spans) {
		var ret ComCoralogixapisDashboardsV1AstWidgetsDynamicQuerySpans
		return ret
	}
	return *o.Spans
}

// GetSpansOk returns a tuple with the Spans field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1) GetSpansOk() (*ComCoralogixapisDashboardsV1AstWidgetsDynamicQuerySpans, bool) {
	if o == nil || IsNil(o.Spans) {
		return nil, false
	}
	return o.Spans, true
}

// HasSpans returns a boolean if a field has been set.
func (o *ComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1) HasSpans() bool {
	if o != nil && !IsNil(o.Spans) {
		return true
	}

	return false
}

// SetSpans gets a reference to the given ComCoralogixapisDashboardsV1AstWidgetsDynamicQuerySpans and assigns it to the Spans field.
func (o *ComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1) SetSpans(v ComCoralogixapisDashboardsV1AstWidgetsDynamicQuerySpans) {
	o.Spans = &v
}

func (o ComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Spans) {
		toSerialize["spans"] = o.Spans
	}
	return toSerialize, nil
}

type NullableComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1 struct {
	value *ComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1
	isSet bool
}

func (v NullableComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1) Get() *ComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1 {
	return v.value
}

func (v *NullableComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1) Set(val *ComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1(val *ComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1) *NullableComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1 {
	return &NullableComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1{value: val, isSet: true}
}

func (v NullableComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixapisDashboardsV1AstWidgetsDynamicQueryOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


