/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
)

// checks if the SloExecutionResponse1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SloExecutionResponse1{}

// SloExecutionResponse1 Response for an executed SLO operation.
type SloExecutionResponse1 struct {
	ReplaceSloResponse *ComCoralogixapisSloV1ReplaceSloResponse `json:"replaceSloResponse,omitempty"`
}

// NewSloExecutionResponse1 instantiates a new SloExecutionResponse1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSloExecutionResponse1() *SloExecutionResponse1 {
	this := SloExecutionResponse1{}
	return &this
}

// NewSloExecutionResponse1WithDefaults instantiates a new SloExecutionResponse1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSloExecutionResponse1WithDefaults() *SloExecutionResponse1 {
	this := SloExecutionResponse1{}
	return &this
}

// GetReplaceSloResponse returns the ReplaceSloResponse field value if set, zero value otherwise.
func (o *SloExecutionResponse1) GetReplaceSloResponse() ComCoralogixapisSloV1ReplaceSloResponse {
	if o == nil || IsNil(o.ReplaceSloResponse) {
		var ret ComCoralogixapisSloV1ReplaceSloResponse
		return ret
	}
	return *o.ReplaceSloResponse
}

// GetReplaceSloResponseOk returns a tuple with the ReplaceSloResponse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SloExecutionResponse1) GetReplaceSloResponseOk() (*ComCoralogixapisSloV1ReplaceSloResponse, bool) {
	if o == nil || IsNil(o.ReplaceSloResponse) {
		return nil, false
	}
	return o.ReplaceSloResponse, true
}

// HasReplaceSloResponse returns a boolean if a field has been set.
func (o *SloExecutionResponse1) HasReplaceSloResponse() bool {
	if o != nil && !IsNil(o.ReplaceSloResponse) {
		return true
	}

	return false
}

// SetReplaceSloResponse gets a reference to the given ComCoralogixapisSloV1ReplaceSloResponse and assigns it to the ReplaceSloResponse field.
func (o *SloExecutionResponse1) SetReplaceSloResponse(v ComCoralogixapisSloV1ReplaceSloResponse) {
	o.ReplaceSloResponse = &v
}

func (o SloExecutionResponse1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SloExecutionResponse1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ReplaceSloResponse) {
		toSerialize["replaceSloResponse"] = o.ReplaceSloResponse
	}
	return toSerialize, nil
}

type NullableSloExecutionResponse1 struct {
	value *SloExecutionResponse1
	isSet bool
}

func (v NullableSloExecutionResponse1) Get() *SloExecutionResponse1 {
	return v.value
}

func (v *NullableSloExecutionResponse1) Set(val *SloExecutionResponse1) {
	v.value = val
	v.isSet = true
}

func (v NullableSloExecutionResponse1) IsSet() bool {
	return v.isSet
}

func (v *NullableSloExecutionResponse1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSloExecutionResponse1(val *SloExecutionResponse1) *NullableSloExecutionResponse1 {
	return &NullableSloExecutionResponse1{value: val, isSet: true}
}

func (v NullableSloExecutionResponse1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSloExecutionResponse1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


