/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ComCoralogixapisAlertsV3GetAlertEventResponse - struct for ComCoralogixapisAlertsV3GetAlertEventResponse
type ComCoralogixapisAlertsV3GetAlertEventResponse struct {
	GetAlertEventResponse *GetAlertEventResponse
	GetAlertEventResponse1 *GetAlertEventResponse1
}

// GetAlertEventResponseAsComCoralogixapisAlertsV3GetAlertEventResponse is a convenience function that returns GetAlertEventResponse wrapped in ComCoralogixapisAlertsV3GetAlertEventResponse
func GetAlertEventResponseAsComCoralogixapisAlertsV3GetAlertEventResponse(v *GetAlertEventResponse) ComCoralogixapisAlertsV3GetAlertEventResponse {
	return ComCoralogixapisAlertsV3GetAlertEventResponse{
		GetAlertEventResponse: v,
	}
}

// GetAlertEventResponse1AsComCoralogixapisAlertsV3GetAlertEventResponse is a convenience function that returns GetAlertEventResponse1 wrapped in ComCoralogixapisAlertsV3GetAlertEventResponse
func GetAlertEventResponse1AsComCoralogixapisAlertsV3GetAlertEventResponse(v *GetAlertEventResponse1) ComCoralogixapisAlertsV3GetAlertEventResponse {
	return ComCoralogixapisAlertsV3GetAlertEventResponse{
		GetAlertEventResponse1: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ComCoralogixapisAlertsV3GetAlertEventResponse) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into GetAlertEventResponse
	err = newStrictDecoder(data).Decode(&dst.GetAlertEventResponse)
	if err == nil {
		jsonGetAlertEventResponse, _ := json.Marshal(dst.GetAlertEventResponse)
		if string(jsonGetAlertEventResponse) == "{}" { // empty struct
			dst.GetAlertEventResponse = nil
		} else {
			if err = validator.Validate(dst.GetAlertEventResponse); err != nil {
				dst.GetAlertEventResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.GetAlertEventResponse = nil
	}

	// try to unmarshal data into GetAlertEventResponse1
	err = newStrictDecoder(data).Decode(&dst.GetAlertEventResponse1)
	if err == nil {
		jsonGetAlertEventResponse1, _ := json.Marshal(dst.GetAlertEventResponse1)
		if string(jsonGetAlertEventResponse1) == "{}" { // empty struct
			dst.GetAlertEventResponse1 = nil
		} else {
			if err = validator.Validate(dst.GetAlertEventResponse1); err != nil {
				dst.GetAlertEventResponse1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.GetAlertEventResponse1 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.GetAlertEventResponse = nil
		dst.GetAlertEventResponse1 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ComCoralogixapisAlertsV3GetAlertEventResponse)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ComCoralogixapisAlertsV3GetAlertEventResponse)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ComCoralogixapisAlertsV3GetAlertEventResponse) MarshalJSON() ([]byte, error) {
	if src.GetAlertEventResponse != nil {
		return json.Marshal(&src.GetAlertEventResponse)
	}

	if src.GetAlertEventResponse1 != nil {
		return json.Marshal(&src.GetAlertEventResponse1)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ComCoralogixapisAlertsV3GetAlertEventResponse) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.GetAlertEventResponse != nil {
		return obj.GetAlertEventResponse
	}

	if obj.GetAlertEventResponse1 != nil {
		return obj.GetAlertEventResponse1
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ComCoralogixapisAlertsV3GetAlertEventResponse) GetActualInstanceValue() (interface{}) {
	if obj.GetAlertEventResponse != nil {
		return *obj.GetAlertEventResponse
	}

	if obj.GetAlertEventResponse1 != nil {
		return *obj.GetAlertEventResponse1
	}

	// all schemas are nil
	return nil
}

type NullableComCoralogixapisAlertsV3GetAlertEventResponse struct {
	value *ComCoralogixapisAlertsV3GetAlertEventResponse
	isSet bool
}

func (v NullableComCoralogixapisAlertsV3GetAlertEventResponse) Get() *ComCoralogixapisAlertsV3GetAlertEventResponse {
	return v.value
}

func (v *NullableComCoralogixapisAlertsV3GetAlertEventResponse) Set(val *ComCoralogixapisAlertsV3GetAlertEventResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixapisAlertsV3GetAlertEventResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixapisAlertsV3GetAlertEventResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixapisAlertsV3GetAlertEventResponse(val *ComCoralogixapisAlertsV3GetAlertEventResponse) *NullableComCoralogixapisAlertsV3GetAlertEventResponse {
	return &NullableComCoralogixapisAlertsV3GetAlertEventResponse{value: val, isSet: true}
}

func (v NullableComCoralogixapisAlertsV3GetAlertEventResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixapisAlertsV3GetAlertEventResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


