/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
)

// checks if the ComCoralogixapisAlertsV3ActivityAnalysisStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComCoralogixapisAlertsV3ActivityAnalysisStats{}

// ComCoralogixapisAlertsV3ActivityAnalysisStats struct for ComCoralogixapisAlertsV3ActivityAnalysisStats
type ComCoralogixapisAlertsV3ActivityAnalysisStats struct {
	IsMutedCount *int64 `json:"isMutedCount,omitempty"`
	Rules []string `json:"rules,omitempty"`
}

// NewComCoralogixapisAlertsV3ActivityAnalysisStats instantiates a new ComCoralogixapisAlertsV3ActivityAnalysisStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComCoralogixapisAlertsV3ActivityAnalysisStats() *ComCoralogixapisAlertsV3ActivityAnalysisStats {
	this := ComCoralogixapisAlertsV3ActivityAnalysisStats{}
	return &this
}

// NewComCoralogixapisAlertsV3ActivityAnalysisStatsWithDefaults instantiates a new ComCoralogixapisAlertsV3ActivityAnalysisStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComCoralogixapisAlertsV3ActivityAnalysisStatsWithDefaults() *ComCoralogixapisAlertsV3ActivityAnalysisStats {
	this := ComCoralogixapisAlertsV3ActivityAnalysisStats{}
	return &this
}

// GetIsMutedCount returns the IsMutedCount field value if set, zero value otherwise.
func (o *ComCoralogixapisAlertsV3ActivityAnalysisStats) GetIsMutedCount() int64 {
	if o == nil || IsNil(o.IsMutedCount) {
		var ret int64
		return ret
	}
	return *o.IsMutedCount
}

// GetIsMutedCountOk returns a tuple with the IsMutedCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV3ActivityAnalysisStats) GetIsMutedCountOk() (*int64, bool) {
	if o == nil || IsNil(o.IsMutedCount) {
		return nil, false
	}
	return o.IsMutedCount, true
}

// HasIsMutedCount returns a boolean if a field has been set.
func (o *ComCoralogixapisAlertsV3ActivityAnalysisStats) HasIsMutedCount() bool {
	if o != nil && !IsNil(o.IsMutedCount) {
		return true
	}

	return false
}

// SetIsMutedCount gets a reference to the given int64 and assigns it to the IsMutedCount field.
func (o *ComCoralogixapisAlertsV3ActivityAnalysisStats) SetIsMutedCount(v int64) {
	o.IsMutedCount = &v
}

// GetRules returns the Rules field value if set, zero value otherwise.
func (o *ComCoralogixapisAlertsV3ActivityAnalysisStats) GetRules() []string {
	if o == nil || IsNil(o.Rules) {
		var ret []string
		return ret
	}
	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV3ActivityAnalysisStats) GetRulesOk() ([]string, bool) {
	if o == nil || IsNil(o.Rules) {
		return nil, false
	}
	return o.Rules, true
}

// HasRules returns a boolean if a field has been set.
func (o *ComCoralogixapisAlertsV3ActivityAnalysisStats) HasRules() bool {
	if o != nil && !IsNil(o.Rules) {
		return true
	}

	return false
}

// SetRules gets a reference to the given []string and assigns it to the Rules field.
func (o *ComCoralogixapisAlertsV3ActivityAnalysisStats) SetRules(v []string) {
	o.Rules = v
}

func (o ComCoralogixapisAlertsV3ActivityAnalysisStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComCoralogixapisAlertsV3ActivityAnalysisStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsMutedCount) {
		toSerialize["isMutedCount"] = o.IsMutedCount
	}
	if !IsNil(o.Rules) {
		toSerialize["rules"] = o.Rules
	}
	return toSerialize, nil
}

type NullableComCoralogixapisAlertsV3ActivityAnalysisStats struct {
	value *ComCoralogixapisAlertsV3ActivityAnalysisStats
	isSet bool
}

func (v NullableComCoralogixapisAlertsV3ActivityAnalysisStats) Get() *ComCoralogixapisAlertsV3ActivityAnalysisStats {
	return v.value
}

func (v *NullableComCoralogixapisAlertsV3ActivityAnalysisStats) Set(val *ComCoralogixapisAlertsV3ActivityAnalysisStats) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixapisAlertsV3ActivityAnalysisStats) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixapisAlertsV3ActivityAnalysisStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixapisAlertsV3ActivityAnalysisStats(val *ComCoralogixapisAlertsV3ActivityAnalysisStats) *NullableComCoralogixapisAlertsV3ActivityAnalysisStats {
	return &NullableComCoralogixapisAlertsV3ActivityAnalysisStats{value: val, isSet: true}
}

func (v NullableComCoralogixapisAlertsV3ActivityAnalysisStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixapisAlertsV3ActivityAnalysisStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


