/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
)

// checks if the ComCoralogixapisDashboardsV1CommonSpansAggregationOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComCoralogixapisDashboardsV1CommonSpansAggregationOneOf{}

// ComCoralogixapisDashboardsV1CommonSpansAggregationOneOf struct for ComCoralogixapisDashboardsV1CommonSpansAggregationOneOf
type ComCoralogixapisDashboardsV1CommonSpansAggregationOneOf struct {
	MetricAggregation *ComCoralogixapisDashboardsV1CommonSpansAggregationMetricAggregation `json:"metricAggregation,omitempty"`
}

// NewComCoralogixapisDashboardsV1CommonSpansAggregationOneOf instantiates a new ComCoralogixapisDashboardsV1CommonSpansAggregationOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComCoralogixapisDashboardsV1CommonSpansAggregationOneOf() *ComCoralogixapisDashboardsV1CommonSpansAggregationOneOf {
	this := ComCoralogixapisDashboardsV1CommonSpansAggregationOneOf{}
	return &this
}

// NewComCoralogixapisDashboardsV1CommonSpansAggregationOneOfWithDefaults instantiates a new ComCoralogixapisDashboardsV1CommonSpansAggregationOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComCoralogixapisDashboardsV1CommonSpansAggregationOneOfWithDefaults() *ComCoralogixapisDashboardsV1CommonSpansAggregationOneOf {
	this := ComCoralogixapisDashboardsV1CommonSpansAggregationOneOf{}
	return &this
}

// GetMetricAggregation returns the MetricAggregation field value if set, zero value otherwise.
func (o *ComCoralogixapisDashboardsV1CommonSpansAggregationOneOf) GetMetricAggregation() ComCoralogixapisDashboardsV1CommonSpansAggregationMetricAggregation {
	if o == nil || IsNil(o.MetricAggregation) {
		var ret ComCoralogixapisDashboardsV1CommonSpansAggregationMetricAggregation
		return ret
	}
	return *o.MetricAggregation
}

// GetMetricAggregationOk returns a tuple with the MetricAggregation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisDashboardsV1CommonSpansAggregationOneOf) GetMetricAggregationOk() (*ComCoralogixapisDashboardsV1CommonSpansAggregationMetricAggregation, bool) {
	if o == nil || IsNil(o.MetricAggregation) {
		return nil, false
	}
	return o.MetricAggregation, true
}

// HasMetricAggregation returns a boolean if a field has been set.
func (o *ComCoralogixapisDashboardsV1CommonSpansAggregationOneOf) HasMetricAggregation() bool {
	if o != nil && !IsNil(o.MetricAggregation) {
		return true
	}

	return false
}

// SetMetricAggregation gets a reference to the given ComCoralogixapisDashboardsV1CommonSpansAggregationMetricAggregation and assigns it to the MetricAggregation field.
func (o *ComCoralogixapisDashboardsV1CommonSpansAggregationOneOf) SetMetricAggregation(v ComCoralogixapisDashboardsV1CommonSpansAggregationMetricAggregation) {
	o.MetricAggregation = &v
}

func (o ComCoralogixapisDashboardsV1CommonSpansAggregationOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComCoralogixapisDashboardsV1CommonSpansAggregationOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MetricAggregation) {
		toSerialize["metricAggregation"] = o.MetricAggregation
	}
	return toSerialize, nil
}

type NullableComCoralogixapisDashboardsV1CommonSpansAggregationOneOf struct {
	value *ComCoralogixapisDashboardsV1CommonSpansAggregationOneOf
	isSet bool
}

func (v NullableComCoralogixapisDashboardsV1CommonSpansAggregationOneOf) Get() *ComCoralogixapisDashboardsV1CommonSpansAggregationOneOf {
	return v.value
}

func (v *NullableComCoralogixapisDashboardsV1CommonSpansAggregationOneOf) Set(val *ComCoralogixapisDashboardsV1CommonSpansAggregationOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixapisDashboardsV1CommonSpansAggregationOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixapisDashboardsV1CommonSpansAggregationOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixapisDashboardsV1CommonSpansAggregationOneOf(val *ComCoralogixapisDashboardsV1CommonSpansAggregationOneOf) *NullableComCoralogixapisDashboardsV1CommonSpansAggregationOneOf {
	return &NullableComCoralogixapisDashboardsV1CommonSpansAggregationOneOf{value: val, isSet: true}
}

func (v NullableComCoralogixapisDashboardsV1CommonSpansAggregationOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixapisDashboardsV1CommonSpansAggregationOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


