/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
)

// checks if the ComCoralogixapisNotificationCenterPresetsV1GetPresetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComCoralogixapisNotificationCenterPresetsV1GetPresetResponse{}

// ComCoralogixapisNotificationCenterPresetsV1GetPresetResponse struct for ComCoralogixapisNotificationCenterPresetsV1GetPresetResponse
type ComCoralogixapisNotificationCenterPresetsV1GetPresetResponse struct {
	Preset *ComCoralogixapisNotificationCenterPresetsV1Preset `json:"preset,omitempty"`
}

// NewComCoralogixapisNotificationCenterPresetsV1GetPresetResponse instantiates a new ComCoralogixapisNotificationCenterPresetsV1GetPresetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComCoralogixapisNotificationCenterPresetsV1GetPresetResponse() *ComCoralogixapisNotificationCenterPresetsV1GetPresetResponse {
	this := ComCoralogixapisNotificationCenterPresetsV1GetPresetResponse{}
	return &this
}

// NewComCoralogixapisNotificationCenterPresetsV1GetPresetResponseWithDefaults instantiates a new ComCoralogixapisNotificationCenterPresetsV1GetPresetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComCoralogixapisNotificationCenterPresetsV1GetPresetResponseWithDefaults() *ComCoralogixapisNotificationCenterPresetsV1GetPresetResponse {
	this := ComCoralogixapisNotificationCenterPresetsV1GetPresetResponse{}
	return &this
}

// GetPreset returns the Preset field value if set, zero value otherwise.
func (o *ComCoralogixapisNotificationCenterPresetsV1GetPresetResponse) GetPreset() ComCoralogixapisNotificationCenterPresetsV1Preset {
	if o == nil || IsNil(o.Preset) {
		var ret ComCoralogixapisNotificationCenterPresetsV1Preset
		return ret
	}
	return *o.Preset
}

// GetPresetOk returns a tuple with the Preset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisNotificationCenterPresetsV1GetPresetResponse) GetPresetOk() (*ComCoralogixapisNotificationCenterPresetsV1Preset, bool) {
	if o == nil || IsNil(o.Preset) {
		return nil, false
	}
	return o.Preset, true
}

// HasPreset returns a boolean if a field has been set.
func (o *ComCoralogixapisNotificationCenterPresetsV1GetPresetResponse) HasPreset() bool {
	if o != nil && !IsNil(o.Preset) {
		return true
	}

	return false
}

// SetPreset gets a reference to the given ComCoralogixapisNotificationCenterPresetsV1Preset and assigns it to the Preset field.
func (o *ComCoralogixapisNotificationCenterPresetsV1GetPresetResponse) SetPreset(v ComCoralogixapisNotificationCenterPresetsV1Preset) {
	o.Preset = &v
}

func (o ComCoralogixapisNotificationCenterPresetsV1GetPresetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComCoralogixapisNotificationCenterPresetsV1GetPresetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Preset) {
		toSerialize["preset"] = o.Preset
	}
	return toSerialize, nil
}

type NullableComCoralogixapisNotificationCenterPresetsV1GetPresetResponse struct {
	value *ComCoralogixapisNotificationCenterPresetsV1GetPresetResponse
	isSet bool
}

func (v NullableComCoralogixapisNotificationCenterPresetsV1GetPresetResponse) Get() *ComCoralogixapisNotificationCenterPresetsV1GetPresetResponse {
	return v.value
}

func (v *NullableComCoralogixapisNotificationCenterPresetsV1GetPresetResponse) Set(val *ComCoralogixapisNotificationCenterPresetsV1GetPresetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixapisNotificationCenterPresetsV1GetPresetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixapisNotificationCenterPresetsV1GetPresetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixapisNotificationCenterPresetsV1GetPresetResponse(val *ComCoralogixapisNotificationCenterPresetsV1GetPresetResponse) *NullableComCoralogixapisNotificationCenterPresetsV1GetPresetResponse {
	return &NullableComCoralogixapisNotificationCenterPresetsV1GetPresetResponse{value: val, isSet: true}
}

func (v NullableComCoralogixapisNotificationCenterPresetsV1GetPresetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixapisNotificationCenterPresetsV1GetPresetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


