/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComCoralogixapisAlertsV3LogsThresholdCondition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComCoralogixapisAlertsV3LogsThresholdCondition{}

// ComCoralogixapisAlertsV3LogsThresholdCondition LogsThresholdCondition is a message that defines the condition for log-based threshold alerts.
type ComCoralogixapisAlertsV3LogsThresholdCondition struct {
	// The type of condition for the alert
	ConditionType string `json:"conditionType"`
	// The threshold value for the alert condition
	Threshold float64 `json:"threshold"`
	TimeWindow ComCoralogixapisAlertsV3LogsTimeWindow `json:"timeWindow"`
}

type _ComCoralogixapisAlertsV3LogsThresholdCondition ComCoralogixapisAlertsV3LogsThresholdCondition

// NewComCoralogixapisAlertsV3LogsThresholdCondition instantiates a new ComCoralogixapisAlertsV3LogsThresholdCondition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComCoralogixapisAlertsV3LogsThresholdCondition(conditionType string, threshold float64, timeWindow ComCoralogixapisAlertsV3LogsTimeWindow) *ComCoralogixapisAlertsV3LogsThresholdCondition {
	this := ComCoralogixapisAlertsV3LogsThresholdCondition{}
	this.ConditionType = conditionType
	this.Threshold = threshold
	this.TimeWindow = timeWindow
	return &this
}

// NewComCoralogixapisAlertsV3LogsThresholdConditionWithDefaults instantiates a new ComCoralogixapisAlertsV3LogsThresholdCondition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComCoralogixapisAlertsV3LogsThresholdConditionWithDefaults() *ComCoralogixapisAlertsV3LogsThresholdCondition {
	this := ComCoralogixapisAlertsV3LogsThresholdCondition{}
	return &this
}

// GetConditionType returns the ConditionType field value
func (o *ComCoralogixapisAlertsV3LogsThresholdCondition) GetConditionType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConditionType
}

// GetConditionTypeOk returns a tuple with the ConditionType field value
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV3LogsThresholdCondition) GetConditionTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConditionType, true
}

// SetConditionType sets field value
func (o *ComCoralogixapisAlertsV3LogsThresholdCondition) SetConditionType(v string) {
	o.ConditionType = v
}

// GetThreshold returns the Threshold field value
func (o *ComCoralogixapisAlertsV3LogsThresholdCondition) GetThreshold() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV3LogsThresholdCondition) GetThresholdOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Threshold, true
}

// SetThreshold sets field value
func (o *ComCoralogixapisAlertsV3LogsThresholdCondition) SetThreshold(v float64) {
	o.Threshold = v
}

// GetTimeWindow returns the TimeWindow field value
func (o *ComCoralogixapisAlertsV3LogsThresholdCondition) GetTimeWindow() ComCoralogixapisAlertsV3LogsTimeWindow {
	if o == nil {
		var ret ComCoralogixapisAlertsV3LogsTimeWindow
		return ret
	}

	return o.TimeWindow
}

// GetTimeWindowOk returns a tuple with the TimeWindow field value
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV3LogsThresholdCondition) GetTimeWindowOk() (*ComCoralogixapisAlertsV3LogsTimeWindow, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeWindow, true
}

// SetTimeWindow sets field value
func (o *ComCoralogixapisAlertsV3LogsThresholdCondition) SetTimeWindow(v ComCoralogixapisAlertsV3LogsTimeWindow) {
	o.TimeWindow = v
}

func (o ComCoralogixapisAlertsV3LogsThresholdCondition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComCoralogixapisAlertsV3LogsThresholdCondition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["conditionType"] = o.ConditionType
	toSerialize["threshold"] = o.Threshold
	toSerialize["timeWindow"] = o.TimeWindow
	return toSerialize, nil
}

func (o *ComCoralogixapisAlertsV3LogsThresholdCondition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"conditionType",
		"threshold",
		"timeWindow",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComCoralogixapisAlertsV3LogsThresholdCondition := _ComCoralogixapisAlertsV3LogsThresholdCondition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComCoralogixapisAlertsV3LogsThresholdCondition)

	if err != nil {
		return err
	}

	*o = ComCoralogixapisAlertsV3LogsThresholdCondition(varComCoralogixapisAlertsV3LogsThresholdCondition)

	return err
}

type NullableComCoralogixapisAlertsV3LogsThresholdCondition struct {
	value *ComCoralogixapisAlertsV3LogsThresholdCondition
	isSet bool
}

func (v NullableComCoralogixapisAlertsV3LogsThresholdCondition) Get() *ComCoralogixapisAlertsV3LogsThresholdCondition {
	return v.value
}

func (v *NullableComCoralogixapisAlertsV3LogsThresholdCondition) Set(val *ComCoralogixapisAlertsV3LogsThresholdCondition) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixapisAlertsV3LogsThresholdCondition) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixapisAlertsV3LogsThresholdCondition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixapisAlertsV3LogsThresholdCondition(val *ComCoralogixapisAlertsV3LogsThresholdCondition) *NullableComCoralogixapisAlertsV3LogsThresholdCondition {
	return &NullableComCoralogixapisAlertsV3LogsThresholdCondition{value: val, isSet: true}
}

func (v NullableComCoralogixapisAlertsV3LogsThresholdCondition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixapisAlertsV3LogsThresholdCondition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


