/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
)

// checks if the ComCoralogixapisDashboardsV1AstVariablesConstant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComCoralogixapisDashboardsV1AstVariablesConstant{}

// ComCoralogixapisDashboardsV1AstVariablesConstant struct for ComCoralogixapisDashboardsV1AstVariablesConstant
type ComCoralogixapisDashboardsV1AstVariablesConstant struct {
	Value *string `json:"value,omitempty"`
}

// NewComCoralogixapisDashboardsV1AstVariablesConstant instantiates a new ComCoralogixapisDashboardsV1AstVariablesConstant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComCoralogixapisDashboardsV1AstVariablesConstant() *ComCoralogixapisDashboardsV1AstVariablesConstant {
	this := ComCoralogixapisDashboardsV1AstVariablesConstant{}
	return &this
}

// NewComCoralogixapisDashboardsV1AstVariablesConstantWithDefaults instantiates a new ComCoralogixapisDashboardsV1AstVariablesConstant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComCoralogixapisDashboardsV1AstVariablesConstantWithDefaults() *ComCoralogixapisDashboardsV1AstVariablesConstant {
	this := ComCoralogixapisDashboardsV1AstVariablesConstant{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ComCoralogixapisDashboardsV1AstVariablesConstant) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisDashboardsV1AstVariablesConstant) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ComCoralogixapisDashboardsV1AstVariablesConstant) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ComCoralogixapisDashboardsV1AstVariablesConstant) SetValue(v string) {
	o.Value = &v
}

func (o ComCoralogixapisDashboardsV1AstVariablesConstant) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComCoralogixapisDashboardsV1AstVariablesConstant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableComCoralogixapisDashboardsV1AstVariablesConstant struct {
	value *ComCoralogixapisDashboardsV1AstVariablesConstant
	isSet bool
}

func (v NullableComCoralogixapisDashboardsV1AstVariablesConstant) Get() *ComCoralogixapisDashboardsV1AstVariablesConstant {
	return v.value
}

func (v *NullableComCoralogixapisDashboardsV1AstVariablesConstant) Set(val *ComCoralogixapisDashboardsV1AstVariablesConstant) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixapisDashboardsV1AstVariablesConstant) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixapisDashboardsV1AstVariablesConstant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixapisDashboardsV1AstVariablesConstant(val *ComCoralogixapisDashboardsV1AstVariablesConstant) *NullableComCoralogixapisDashboardsV1AstVariablesConstant {
	return &NullableComCoralogixapisDashboardsV1AstVariablesConstant{value: val, isSet: true}
}

func (v NullableComCoralogixapisDashboardsV1AstVariablesConstant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixapisDashboardsV1AstVariablesConstant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


