/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ComCoralogixapisSloV1SloMetricMissingValues - struct for ComCoralogixapisSloV1SloMetricMissingValues
type ComCoralogixapisSloV1SloMetricMissingValues struct {
	ComCoralogixapisSloV1SloMetricMissingValuesOneOf *ComCoralogixapisSloV1SloMetricMissingValuesOneOf
	ComCoralogixapisSloV1SloMetricMissingValuesOneOf1 *ComCoralogixapisSloV1SloMetricMissingValuesOneOf1
}

// ComCoralogixapisSloV1SloMetricMissingValuesOneOfAsComCoralogixapisSloV1SloMetricMissingValues is a convenience function that returns ComCoralogixapisSloV1SloMetricMissingValuesOneOf wrapped in ComCoralogixapisSloV1SloMetricMissingValues
func ComCoralogixapisSloV1SloMetricMissingValuesOneOfAsComCoralogixapisSloV1SloMetricMissingValues(v *ComCoralogixapisSloV1SloMetricMissingValuesOneOf) ComCoralogixapisSloV1SloMetricMissingValues {
	return ComCoralogixapisSloV1SloMetricMissingValues{
		ComCoralogixapisSloV1SloMetricMissingValuesOneOf: v,
	}
}

// ComCoralogixapisSloV1SloMetricMissingValuesOneOf1AsComCoralogixapisSloV1SloMetricMissingValues is a convenience function that returns ComCoralogixapisSloV1SloMetricMissingValuesOneOf1 wrapped in ComCoralogixapisSloV1SloMetricMissingValues
func ComCoralogixapisSloV1SloMetricMissingValuesOneOf1AsComCoralogixapisSloV1SloMetricMissingValues(v *ComCoralogixapisSloV1SloMetricMissingValuesOneOf1) ComCoralogixapisSloV1SloMetricMissingValues {
	return ComCoralogixapisSloV1SloMetricMissingValues{
		ComCoralogixapisSloV1SloMetricMissingValuesOneOf1: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ComCoralogixapisSloV1SloMetricMissingValues) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ComCoralogixapisSloV1SloMetricMissingValuesOneOf
	err = newStrictDecoder(data).Decode(&dst.ComCoralogixapisSloV1SloMetricMissingValuesOneOf)
	if err == nil {
		jsonComCoralogixapisSloV1SloMetricMissingValuesOneOf, _ := json.Marshal(dst.ComCoralogixapisSloV1SloMetricMissingValuesOneOf)
		if string(jsonComCoralogixapisSloV1SloMetricMissingValuesOneOf) == "{}" { // empty struct
			dst.ComCoralogixapisSloV1SloMetricMissingValuesOneOf = nil
		} else {
			if err = validator.Validate(dst.ComCoralogixapisSloV1SloMetricMissingValuesOneOf); err != nil {
				dst.ComCoralogixapisSloV1SloMetricMissingValuesOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.ComCoralogixapisSloV1SloMetricMissingValuesOneOf = nil
	}

	// try to unmarshal data into ComCoralogixapisSloV1SloMetricMissingValuesOneOf1
	err = newStrictDecoder(data).Decode(&dst.ComCoralogixapisSloV1SloMetricMissingValuesOneOf1)
	if err == nil {
		jsonComCoralogixapisSloV1SloMetricMissingValuesOneOf1, _ := json.Marshal(dst.ComCoralogixapisSloV1SloMetricMissingValuesOneOf1)
		if string(jsonComCoralogixapisSloV1SloMetricMissingValuesOneOf1) == "{}" { // empty struct
			dst.ComCoralogixapisSloV1SloMetricMissingValuesOneOf1 = nil
		} else {
			if err = validator.Validate(dst.ComCoralogixapisSloV1SloMetricMissingValuesOneOf1); err != nil {
				dst.ComCoralogixapisSloV1SloMetricMissingValuesOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ComCoralogixapisSloV1SloMetricMissingValuesOneOf1 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ComCoralogixapisSloV1SloMetricMissingValuesOneOf = nil
		dst.ComCoralogixapisSloV1SloMetricMissingValuesOneOf1 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ComCoralogixapisSloV1SloMetricMissingValues)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ComCoralogixapisSloV1SloMetricMissingValues)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ComCoralogixapisSloV1SloMetricMissingValues) MarshalJSON() ([]byte, error) {
	if src.ComCoralogixapisSloV1SloMetricMissingValuesOneOf != nil {
		return json.Marshal(&src.ComCoralogixapisSloV1SloMetricMissingValuesOneOf)
	}

	if src.ComCoralogixapisSloV1SloMetricMissingValuesOneOf1 != nil {
		return json.Marshal(&src.ComCoralogixapisSloV1SloMetricMissingValuesOneOf1)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ComCoralogixapisSloV1SloMetricMissingValues) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ComCoralogixapisSloV1SloMetricMissingValuesOneOf != nil {
		return obj.ComCoralogixapisSloV1SloMetricMissingValuesOneOf
	}

	if obj.ComCoralogixapisSloV1SloMetricMissingValuesOneOf1 != nil {
		return obj.ComCoralogixapisSloV1SloMetricMissingValuesOneOf1
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ComCoralogixapisSloV1SloMetricMissingValues) GetActualInstanceValue() (interface{}) {
	if obj.ComCoralogixapisSloV1SloMetricMissingValuesOneOf != nil {
		return *obj.ComCoralogixapisSloV1SloMetricMissingValuesOneOf
	}

	if obj.ComCoralogixapisSloV1SloMetricMissingValuesOneOf1 != nil {
		return *obj.ComCoralogixapisSloV1SloMetricMissingValuesOneOf1
	}

	// all schemas are nil
	return nil
}

type NullableComCoralogixapisSloV1SloMetricMissingValues struct {
	value *ComCoralogixapisSloV1SloMetricMissingValues
	isSet bool
}

func (v NullableComCoralogixapisSloV1SloMetricMissingValues) Get() *ComCoralogixapisSloV1SloMetricMissingValues {
	return v.value
}

func (v *NullableComCoralogixapisSloV1SloMetricMissingValues) Set(val *ComCoralogixapisSloV1SloMetricMissingValues) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixapisSloV1SloMetricMissingValues) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixapisSloV1SloMetricMissingValues) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixapisSloV1SloMetricMissingValues(val *ComCoralogixapisSloV1SloMetricMissingValues) *NullableComCoralogixapisSloV1SloMetricMissingValues {
	return &NullableComCoralogixapisSloV1SloMetricMissingValues{value: val, isSet: true}
}

func (v NullableComCoralogixapisSloV1SloMetricMissingValues) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixapisSloV1SloMetricMissingValues) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


