/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
	"time"
)

// checks if the ComCoralogixapisAlertsV3MetricThresholdNotification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComCoralogixapisAlertsV3MetricThresholdNotification{}

// ComCoralogixapisAlertsV3MetricThresholdNotification struct for ComCoralogixapisAlertsV3MetricThresholdNotification
type ComCoralogixapisAlertsV3MetricThresholdNotification struct {
	AvgValueOverThreshold *float64 `json:"avgValueOverThreshold,omitempty"`
	ConditionType *string `json:"conditionType,omitempty"`
	FromTimestamp *time.Time `json:"fromTimestamp,omitempty"`
	IsUndetectedValue *bool `json:"isUndetectedValue,omitempty"`
	MaxValueOverThreshold *float64 `json:"maxValueOverThreshold,omitempty"`
	MinValueOverThreshold *float64 `json:"minValueOverThreshold,omitempty"`
	PctOverThreshold *float64 `json:"pctOverThreshold,omitempty"`
	ToTimestamp *time.Time `json:"toTimestamp,omitempty"`
}

// NewComCoralogixapisAlertsV3MetricThresholdNotification instantiates a new ComCoralogixapisAlertsV3MetricThresholdNotification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComCoralogixapisAlertsV3MetricThresholdNotification() *ComCoralogixapisAlertsV3MetricThresholdNotification {
	this := ComCoralogixapisAlertsV3MetricThresholdNotification{}
	return &this
}

// NewComCoralogixapisAlertsV3MetricThresholdNotificationWithDefaults instantiates a new ComCoralogixapisAlertsV3MetricThresholdNotification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComCoralogixapisAlertsV3MetricThresholdNotificationWithDefaults() *ComCoralogixapisAlertsV3MetricThresholdNotification {
	this := ComCoralogixapisAlertsV3MetricThresholdNotification{}
	return &this
}

// GetAvgValueOverThreshold returns the AvgValueOverThreshold field value if set, zero value otherwise.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) GetAvgValueOverThreshold() float64 {
	if o == nil || IsNil(o.AvgValueOverThreshold) {
		var ret float64
		return ret
	}
	return *o.AvgValueOverThreshold
}

// GetAvgValueOverThresholdOk returns a tuple with the AvgValueOverThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) GetAvgValueOverThresholdOk() (*float64, bool) {
	if o == nil || IsNil(o.AvgValueOverThreshold) {
		return nil, false
	}
	return o.AvgValueOverThreshold, true
}

// HasAvgValueOverThreshold returns a boolean if a field has been set.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) HasAvgValueOverThreshold() bool {
	if o != nil && !IsNil(o.AvgValueOverThreshold) {
		return true
	}

	return false
}

// SetAvgValueOverThreshold gets a reference to the given float64 and assigns it to the AvgValueOverThreshold field.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) SetAvgValueOverThreshold(v float64) {
	o.AvgValueOverThreshold = &v
}

// GetConditionType returns the ConditionType field value if set, zero value otherwise.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) GetConditionType() string {
	if o == nil || IsNil(o.ConditionType) {
		var ret string
		return ret
	}
	return *o.ConditionType
}

// GetConditionTypeOk returns a tuple with the ConditionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) GetConditionTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ConditionType) {
		return nil, false
	}
	return o.ConditionType, true
}

// HasConditionType returns a boolean if a field has been set.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) HasConditionType() bool {
	if o != nil && !IsNil(o.ConditionType) {
		return true
	}

	return false
}

// SetConditionType gets a reference to the given string and assigns it to the ConditionType field.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) SetConditionType(v string) {
	o.ConditionType = &v
}

// GetFromTimestamp returns the FromTimestamp field value if set, zero value otherwise.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) GetFromTimestamp() time.Time {
	if o == nil || IsNil(o.FromTimestamp) {
		var ret time.Time
		return ret
	}
	return *o.FromTimestamp
}

// GetFromTimestampOk returns a tuple with the FromTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) GetFromTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.FromTimestamp) {
		return nil, false
	}
	return o.FromTimestamp, true
}

// HasFromTimestamp returns a boolean if a field has been set.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) HasFromTimestamp() bool {
	if o != nil && !IsNil(o.FromTimestamp) {
		return true
	}

	return false
}

// SetFromTimestamp gets a reference to the given time.Time and assigns it to the FromTimestamp field.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) SetFromTimestamp(v time.Time) {
	o.FromTimestamp = &v
}

// GetIsUndetectedValue returns the IsUndetectedValue field value if set, zero value otherwise.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) GetIsUndetectedValue() bool {
	if o == nil || IsNil(o.IsUndetectedValue) {
		var ret bool
		return ret
	}
	return *o.IsUndetectedValue
}

// GetIsUndetectedValueOk returns a tuple with the IsUndetectedValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) GetIsUndetectedValueOk() (*bool, bool) {
	if o == nil || IsNil(o.IsUndetectedValue) {
		return nil, false
	}
	return o.IsUndetectedValue, true
}

// HasIsUndetectedValue returns a boolean if a field has been set.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) HasIsUndetectedValue() bool {
	if o != nil && !IsNil(o.IsUndetectedValue) {
		return true
	}

	return false
}

// SetIsUndetectedValue gets a reference to the given bool and assigns it to the IsUndetectedValue field.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) SetIsUndetectedValue(v bool) {
	o.IsUndetectedValue = &v
}

// GetMaxValueOverThreshold returns the MaxValueOverThreshold field value if set, zero value otherwise.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) GetMaxValueOverThreshold() float64 {
	if o == nil || IsNil(o.MaxValueOverThreshold) {
		var ret float64
		return ret
	}
	return *o.MaxValueOverThreshold
}

// GetMaxValueOverThresholdOk returns a tuple with the MaxValueOverThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) GetMaxValueOverThresholdOk() (*float64, bool) {
	if o == nil || IsNil(o.MaxValueOverThreshold) {
		return nil, false
	}
	return o.MaxValueOverThreshold, true
}

// HasMaxValueOverThreshold returns a boolean if a field has been set.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) HasMaxValueOverThreshold() bool {
	if o != nil && !IsNil(o.MaxValueOverThreshold) {
		return true
	}

	return false
}

// SetMaxValueOverThreshold gets a reference to the given float64 and assigns it to the MaxValueOverThreshold field.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) SetMaxValueOverThreshold(v float64) {
	o.MaxValueOverThreshold = &v
}

// GetMinValueOverThreshold returns the MinValueOverThreshold field value if set, zero value otherwise.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) GetMinValueOverThreshold() float64 {
	if o == nil || IsNil(o.MinValueOverThreshold) {
		var ret float64
		return ret
	}
	return *o.MinValueOverThreshold
}

// GetMinValueOverThresholdOk returns a tuple with the MinValueOverThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) GetMinValueOverThresholdOk() (*float64, bool) {
	if o == nil || IsNil(o.MinValueOverThreshold) {
		return nil, false
	}
	return o.MinValueOverThreshold, true
}

// HasMinValueOverThreshold returns a boolean if a field has been set.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) HasMinValueOverThreshold() bool {
	if o != nil && !IsNil(o.MinValueOverThreshold) {
		return true
	}

	return false
}

// SetMinValueOverThreshold gets a reference to the given float64 and assigns it to the MinValueOverThreshold field.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) SetMinValueOverThreshold(v float64) {
	o.MinValueOverThreshold = &v
}

// GetPctOverThreshold returns the PctOverThreshold field value if set, zero value otherwise.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) GetPctOverThreshold() float64 {
	if o == nil || IsNil(o.PctOverThreshold) {
		var ret float64
		return ret
	}
	return *o.PctOverThreshold
}

// GetPctOverThresholdOk returns a tuple with the PctOverThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) GetPctOverThresholdOk() (*float64, bool) {
	if o == nil || IsNil(o.PctOverThreshold) {
		return nil, false
	}
	return o.PctOverThreshold, true
}

// HasPctOverThreshold returns a boolean if a field has been set.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) HasPctOverThreshold() bool {
	if o != nil && !IsNil(o.PctOverThreshold) {
		return true
	}

	return false
}

// SetPctOverThreshold gets a reference to the given float64 and assigns it to the PctOverThreshold field.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) SetPctOverThreshold(v float64) {
	o.PctOverThreshold = &v
}

// GetToTimestamp returns the ToTimestamp field value if set, zero value otherwise.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) GetToTimestamp() time.Time {
	if o == nil || IsNil(o.ToTimestamp) {
		var ret time.Time
		return ret
	}
	return *o.ToTimestamp
}

// GetToTimestampOk returns a tuple with the ToTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) GetToTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ToTimestamp) {
		return nil, false
	}
	return o.ToTimestamp, true
}

// HasToTimestamp returns a boolean if a field has been set.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) HasToTimestamp() bool {
	if o != nil && !IsNil(o.ToTimestamp) {
		return true
	}

	return false
}

// SetToTimestamp gets a reference to the given time.Time and assigns it to the ToTimestamp field.
func (o *ComCoralogixapisAlertsV3MetricThresholdNotification) SetToTimestamp(v time.Time) {
	o.ToTimestamp = &v
}

func (o ComCoralogixapisAlertsV3MetricThresholdNotification) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComCoralogixapisAlertsV3MetricThresholdNotification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvgValueOverThreshold) {
		toSerialize["avgValueOverThreshold"] = o.AvgValueOverThreshold
	}
	if !IsNil(o.ConditionType) {
		toSerialize["conditionType"] = o.ConditionType
	}
	if !IsNil(o.FromTimestamp) {
		toSerialize["fromTimestamp"] = o.FromTimestamp
	}
	if !IsNil(o.IsUndetectedValue) {
		toSerialize["isUndetectedValue"] = o.IsUndetectedValue
	}
	if !IsNil(o.MaxValueOverThreshold) {
		toSerialize["maxValueOverThreshold"] = o.MaxValueOverThreshold
	}
	if !IsNil(o.MinValueOverThreshold) {
		toSerialize["minValueOverThreshold"] = o.MinValueOverThreshold
	}
	if !IsNil(o.PctOverThreshold) {
		toSerialize["pctOverThreshold"] = o.PctOverThreshold
	}
	if !IsNil(o.ToTimestamp) {
		toSerialize["toTimestamp"] = o.ToTimestamp
	}
	return toSerialize, nil
}

type NullableComCoralogixapisAlertsV3MetricThresholdNotification struct {
	value *ComCoralogixapisAlertsV3MetricThresholdNotification
	isSet bool
}

func (v NullableComCoralogixapisAlertsV3MetricThresholdNotification) Get() *ComCoralogixapisAlertsV3MetricThresholdNotification {
	return v.value
}

func (v *NullableComCoralogixapisAlertsV3MetricThresholdNotification) Set(val *ComCoralogixapisAlertsV3MetricThresholdNotification) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixapisAlertsV3MetricThresholdNotification) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixapisAlertsV3MetricThresholdNotification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixapisAlertsV3MetricThresholdNotification(val *ComCoralogixapisAlertsV3MetricThresholdNotification) *NullableComCoralogixapisAlertsV3MetricThresholdNotification {
	return &NullableComCoralogixapisAlertsV3MetricThresholdNotification{value: val, isSet: true}
}

func (v NullableComCoralogixapisAlertsV3MetricThresholdNotification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixapisAlertsV3MetricThresholdNotification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


