/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
)

// checks if the ComCoralogixArchiveFormatGenericV1GenericEventAvro type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComCoralogixArchiveFormatGenericV1GenericEventAvro{}

// ComCoralogixArchiveFormatGenericV1GenericEventAvro struct for ComCoralogixArchiveFormatGenericV1GenericEventAvro
type ComCoralogixArchiveFormatGenericV1GenericEventAvro struct {
	Version *string `json:"version,omitempty"`
}

// NewComCoralogixArchiveFormatGenericV1GenericEventAvro instantiates a new ComCoralogixArchiveFormatGenericV1GenericEventAvro object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComCoralogixArchiveFormatGenericV1GenericEventAvro() *ComCoralogixArchiveFormatGenericV1GenericEventAvro {
	this := ComCoralogixArchiveFormatGenericV1GenericEventAvro{}
	return &this
}

// NewComCoralogixArchiveFormatGenericV1GenericEventAvroWithDefaults instantiates a new ComCoralogixArchiveFormatGenericV1GenericEventAvro object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComCoralogixArchiveFormatGenericV1GenericEventAvroWithDefaults() *ComCoralogixArchiveFormatGenericV1GenericEventAvro {
	this := ComCoralogixArchiveFormatGenericV1GenericEventAvro{}
	return &this
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ComCoralogixArchiveFormatGenericV1GenericEventAvro) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixArchiveFormatGenericV1GenericEventAvro) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ComCoralogixArchiveFormatGenericV1GenericEventAvro) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *ComCoralogixArchiveFormatGenericV1GenericEventAvro) SetVersion(v string) {
	o.Version = &v
}

func (o ComCoralogixArchiveFormatGenericV1GenericEventAvro) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComCoralogixArchiveFormatGenericV1GenericEventAvro) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableComCoralogixArchiveFormatGenericV1GenericEventAvro struct {
	value *ComCoralogixArchiveFormatGenericV1GenericEventAvro
	isSet bool
}

func (v NullableComCoralogixArchiveFormatGenericV1GenericEventAvro) Get() *ComCoralogixArchiveFormatGenericV1GenericEventAvro {
	return v.value
}

func (v *NullableComCoralogixArchiveFormatGenericV1GenericEventAvro) Set(val *ComCoralogixArchiveFormatGenericV1GenericEventAvro) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixArchiveFormatGenericV1GenericEventAvro) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixArchiveFormatGenericV1GenericEventAvro) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixArchiveFormatGenericV1GenericEventAvro(val *ComCoralogixArchiveFormatGenericV1GenericEventAvro) *NullableComCoralogixArchiveFormatGenericV1GenericEventAvro {
	return &NullableComCoralogixArchiveFormatGenericV1GenericEventAvro{value: val, isSet: true}
}

func (v NullableComCoralogixArchiveFormatGenericV1GenericEventAvro) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixArchiveFormatGenericV1GenericEventAvro) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


