/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cxsdk

import (
	"encoding/json"
)

// checks if the ComCoralogixEnrichmentV1GetCustomEnrichmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComCoralogixEnrichmentV1GetCustomEnrichmentRequest{}

// ComCoralogixEnrichmentV1GetCustomEnrichmentRequest This is used to retrieve a custom enrichment by id
type ComCoralogixEnrichmentV1GetCustomEnrichmentRequest struct {
	Id *int64 `json:"id,omitempty"`
}

// NewComCoralogixEnrichmentV1GetCustomEnrichmentRequest instantiates a new ComCoralogixEnrichmentV1GetCustomEnrichmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComCoralogixEnrichmentV1GetCustomEnrichmentRequest() *ComCoralogixEnrichmentV1GetCustomEnrichmentRequest {
	this := ComCoralogixEnrichmentV1GetCustomEnrichmentRequest{}
	return &this
}

// NewComCoralogixEnrichmentV1GetCustomEnrichmentRequestWithDefaults instantiates a new ComCoralogixEnrichmentV1GetCustomEnrichmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComCoralogixEnrichmentV1GetCustomEnrichmentRequestWithDefaults() *ComCoralogixEnrichmentV1GetCustomEnrichmentRequest {
	this := ComCoralogixEnrichmentV1GetCustomEnrichmentRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ComCoralogixEnrichmentV1GetCustomEnrichmentRequest) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComCoralogixEnrichmentV1GetCustomEnrichmentRequest) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ComCoralogixEnrichmentV1GetCustomEnrichmentRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *ComCoralogixEnrichmentV1GetCustomEnrichmentRequest) SetId(v int64) {
	o.Id = &v
}

func (o ComCoralogixEnrichmentV1GetCustomEnrichmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComCoralogixEnrichmentV1GetCustomEnrichmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableComCoralogixEnrichmentV1GetCustomEnrichmentRequest struct {
	value *ComCoralogixEnrichmentV1GetCustomEnrichmentRequest
	isSet bool
}

func (v NullableComCoralogixEnrichmentV1GetCustomEnrichmentRequest) Get() *ComCoralogixEnrichmentV1GetCustomEnrichmentRequest {
	return v.value
}

func (v *NullableComCoralogixEnrichmentV1GetCustomEnrichmentRequest) Set(val *ComCoralogixEnrichmentV1GetCustomEnrichmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableComCoralogixEnrichmentV1GetCustomEnrichmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableComCoralogixEnrichmentV1GetCustomEnrichmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComCoralogixEnrichmentV1GetCustomEnrichmentRequest(val *ComCoralogixEnrichmentV1GetCustomEnrichmentRequest) *NullableComCoralogixEnrichmentV1GetCustomEnrichmentRequest {
	return &NullableComCoralogixEnrichmentV1GetCustomEnrichmentRequest{value: val, isSet: true}
}

func (v NullableComCoralogixEnrichmentV1GetCustomEnrichmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComCoralogixEnrichmentV1GetCustomEnrichmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


