{
  "openapi": "3.1.0",
  "info": {
    "title": "",
    "version": "1.0.0"
  },
  "paths": {
    "/notifications/notification-center/v1/connector-schemas": {
      "get": {
        "description": "Returns the schema definition for notification connectors.",
        "operationId": "ConnectorSchemaService_GetConnectorSchema",
        "parameters": [
          {
            "description": "Connector type whose schema to retrieve.",
            "in": "query",
            "name": "type",
            "required": false,
            "schema": {
              "allOf": [
                {
                  "$ref": "#/components/schemas/notification_center.ConnectorType"
                }
              ],
              "description": "Connector type whose schema to retrieve."
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetConnectorSchemaResponse"
                }
              }
            },
            "description": ""
          }
        },
        "summary": "Get Connector Schema",
        "tags": [
          "Connector Schema service"
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "ConnectorConfigSchema": {
        "type": "object",
        "properties": {
          "fields": {
            "maxItems": 100,
            "minItems": 0,
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ConnectorConfigSchemaField"
            },
            "description": "List of fields."
          }
        },
        "description": "Connector config schema.",
        "externalDocs": {
          "url": ""
        }
      },
      "ConnectorConfigSchemaField": {
        "type": "object",
        "properties": {
          "allowOverrides": {
            "type": "boolean",
            "description": "The allow overrides."
          },
          "allowedValues": {
            "maxItems": 100,
            "minItems": 0,
            "type": "array",
            "items": {
              "minLength": 0,
              "type": "string",
              "description": "The allowed values."
            },
            "description": "The allowed values."
          },
          "default": {
            "description": "The default.",
            "maxLength": 4096,
            "minLength": 0,
            "pattern": "^[\\s\\S]*$",
            "type": "string",
            "x-coralogix-presence": true
          },
          "description": {
            "description": "Human-readable description.",
            "maxLength": 4096,
            "minLength": 1,
            "pattern": "^[\\s\\S]*$",
            "type": "string",
            "x-coralogix-presence": true
          },
          "fieldName": {
            "maxLength": 256,
            "minLength": 1,
            "pattern": "^[\\s\\S]*$",
            "type": "string",
            "description": "The field name."
          },
          "fieldType": {
            "$ref": "#/components/schemas/FieldType"
          },
          "required": {
            "type": "boolean",
            "description": "The required."
          }
        }
      },
      "ConnectorSchema": {
        "type": "object",
        "properties": {
          "connectorConfigSchema": {
            "$ref": "#/components/schemas/ConnectorConfigSchema"
          },
          "messageConfigSchemas": {
            "maxItems": 100,
            "minItems": 1,
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/MessageConfigSchema"
            },
            "description": "The message config schemas."
          },
          "supportedPayloadTypes": {
            "maxItems": 100,
            "minItems": 1,
            "type": "array",
            "items": {
              "minLength": 0,
              "type": "string",
              "description": "The supported payload types."
            },
            "description": "The supported payload types."
          },
          "type": {
            "$ref": "#/components/schemas/notification_center.ConnectorType"
          }
        },
        "description": "Connector schema.",
        "externalDocs": {
          "url": ""
        }
      },
      "FieldType": {
        "enum": [
          "FIELD_TYPE_UNSPECIFIED",
          "STRING",
          "NON_EMPTY_STRING",
          "KEY_VALUE_PAIRS",
          "JSON_OBJECT",
          "DATE",
          "URL",
          "ARRAY_OF_STRINGS",
          "BOOLEAN"
        ],
        "type": "string",
        "description": "Field type."
      },
      "FilterPathAndValues": {
        "title": "FilterPathAndValues",
        "required": [
          "path"
        ],
        "type": "object",
        "oneOf": [
          {
            "required": [
              "multipleValues"
            ],
            "type": "object"
          },
          {
            "required": [
              "filters"
            ],
            "type": "object"
          }
        ],
        "properties": {
          "filters": {
            "allOf": [
              {
                "$ref": "#/components/schemas/Filters"
              }
            ],
            "description": "The filters."
          },
          "multipleValues": {
            "$ref": "#/components/schemas/MultipleValues"
          },
          "path": {
            "minLength": 0,
            "type": "string",
            "examples": [
              "test"
            ]
          }
        },
        "description": "This data structure represents a filter path and values",
        "externalDocs": {
          "url": ""
        }
      },
      "Filters": {
        "title": "Filters",
        "required": [
          "pathAndValues"
        ],
        "type": "object",
        "properties": {
          "operator": {
            "allOf": [
              {
                "$ref": "#/components/schemas/v3.FilterOperator"
              }
            ],
            "examples": [
              "FILTER_OPERATOR_OR"
            ]
          },
          "pathAndValues": {
            "minItems": 0,
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/FilterPathAndValues"
            }
          }
        },
        "description": "This data structure represents a filter",
        "externalDocs": {
          "url": ""
        }
      },
      "GetConnectorSchemaResponse": {
        "type": "object",
        "properties": {
          "connectorSchema": {
            "$ref": "#/components/schemas/ConnectorSchema"
          }
        },
        "description": "Response containing the schema definition for a notification connector type.",
        "externalDocs": {
          "url": ""
        }
      },
      "MessageConfigSchema": {
        "type": "object",
        "properties": {
          "fields": {
            "maxItems": 100,
            "minItems": 0,
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/MessageConfigSchemaField"
            },
            "description": "List of fields."
          },
          "payloadType": {
            "maxLength": 256,
            "minLength": 1,
            "pattern": "^[\\s\\S]*$",
            "type": "string",
            "description": "Type of the payload."
          }
        }
      },
      "MessageConfigSchemaField": {
        "type": "object",
        "properties": {
          "allowedValues": {
            "maxItems": 100,
            "minItems": 0,
            "type": "array",
            "items": {
              "maxLength": 4096,
              "minLength": 0,
              "pattern": "^[\\s\\S]*$",
              "type": "string",
              "description": "The allowed values."
            },
            "description": "The allowed values."
          },
          "default": {
            "description": "The default.",
            "maxLength": 4096,
            "minLength": 0,
            "pattern": "^[\\s\\S]*$",
            "type": "string",
            "x-coralogix-presence": true
          },
          "description": {
            "description": "Human-readable description.",
            "maxLength": 4096,
            "minLength": 1,
            "pattern": "^[\\s\\S]*$",
            "type": "string",
            "x-coralogix-presence": true
          },
          "disableOverride": {
            "description": "The disable override.",
            "type": "boolean",
            "x-coralogix-presence": true
          },
          "fieldName": {
            "maxLength": 256,
            "minLength": 1,
            "pattern": "^[\\s\\S]*$",
            "type": "string",
            "description": "The field name."
          },
          "fieldType": {
            "$ref": "#/components/schemas/FieldType"
          },
          "renderingMode": {
            "$ref": "#/components/schemas/TemplateRenderingMode"
          },
          "required": {
            "type": "boolean",
            "description": "The required."
          }
        }
      },
      "MultipleValues": {
        "type": "object",
        "properties": {
          "matcher": {
            "$ref": "#/components/schemas/events.v3.FilterMatcher"
          },
          "values": {
            "minItems": 0,
            "type": "array",
            "items": {
              "minLength": 0,
              "type": "string"
            }
          }
        }
      },
      "TemplateRenderingMode": {
        "enum": [
          "TEMPLATE_RENDERING_MODE_UNSPECIFIED",
          "RELAXED",
          "STRICT"
        ],
        "type": "string",
        "description": "Template rendering mode."
      },
      "events.v3.FilterMatcher": {
        "enum": [
          "FILTER_MATCHER_TEXT_OR_UNSPECIFIED",
          "FILTER_MATCHER_REGEXP"
        ],
        "type": "string"
      },
      "notification_center.ConnectorType": {
        "enum": [
          "CONNECTOR_TYPE_UNSPECIFIED",
          "SLACK",
          "GENERIC_HTTPS",
          "PAGERDUTY",
          "IBM_EVENT_NOTIFICATIONS",
          "SERVICE_NOW",
          "EMAIL",
          "PAGERDUTY_INCIDENTS",
          "MICROSOFT_TEAMS",
          "EVENTBRIDGE",
          "INCIDENT_IO"
        ],
        "type": "string",
        "description": "Connector type."
      },
      "v3.FilterOperator": {
        "enum": [
          "FILTER_OPERATOR_AND_OR_UNSPECIFIED",
          "FILTER_OPERATOR_OR"
        ],
        "type": "string",
        "description": "Filter operator."
      }
    }
  }
}