openapi: 3.0.0
info:
  title: ""
  version: 1.0.0
servers:
- url: /
paths:
  /aaa/custom-roles/v1:
    get:
      description: Returns all custom roles for the authenticated team.
      externalDocs:
        url: ""
      operationId: RoleManagementService_ListCustomRoles
      parameters:
      - description: Team identifier.
        explode: true
        in: query
        name: team_id
        required: false
        schema:
          description: Team identifier.
          format: int64
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListCustomRolesResponse"
          description: ""
        "400":
          content:
            application/json: {}
          description: Bad Request
        "401":
          content:
            application/json: {}
          description: Unauthorized request
        "500":
          content:
            application/json: {}
          description: Internal server error
      summary: List Custom Roles
      tags:
      - Role Management Service
    put:
      description: Creates a new custom role.
      externalDocs:
        url: ""
      operationId: RoleManagementService_CreateRole
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RoleManagementService_CreateRole_request"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateRoleResponse"
          description: ""
        "201":
          content:
            application/json: {}
          description: Role created
        "400":
          content:
            application/json: {}
          description: Bad Request
        "401":
          content:
            application/json: {}
          description: Unauthorized request
        "409":
          content:
            application/json: {}
          description: Role already exists
        "500":
          content:
            application/json: {}
          description: Internal server error
      summary: Create Role
      tags:
      - Role Management Service
  /aaa/custom-roles/v1/{role_id}:
    delete:
      description: Deletes the custom role with the specified ID.
      externalDocs:
        url: ""
      operationId: RoleManagementService_DeleteRole
      parameters:
      - description: The role id.
        explode: false
        in: path
        name: role_id
        required: true
        schema:
          description: The role id.
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteRoleResponse"
          description: ""
        "204":
          content:
            application/json: {}
          description: Role deleted
        "400":
          content:
            application/json: {}
          description: Bad Request
        "401":
          content:
            application/json: {}
          description: Unauthorized request
        "404":
          content:
            application/json: {}
          description: Role not found
        "500":
          content:
            application/json: {}
          description: Internal server error
      summary: Delete Role
      tags:
      - Role Management Service
    get:
      description: Returns the details of the specified custom role.
      externalDocs:
        url: ""
      operationId: RoleManagementService_GetCustomRole
      parameters:
      - description: The role id.
        explode: false
        in: path
        name: role_id
        required: true
        schema:
          description: The role id.
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetCustomRoleResponse"
          description: ""
        "400":
          content:
            application/json: {}
          description: Bad Request
        "401":
          content:
            application/json: {}
          description: Unauthorized request
        "404":
          content:
            application/json: {}
          description: Role not found
        "500":
          content:
            application/json: {}
          description: Internal server error
      summary: Get Custom Role
      tags:
      - Role Management Service
    post:
      description: Updates the specified custom role.
      externalDocs:
        url: ""
      operationId: RoleManagementService_UpdateRole
      parameters:
      - description: The role id.
        explode: false
        in: path
        name: role_id
        required: true
        schema:
          description: The role id.
          format: int64
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RoleManagementService_UpdateRole_request"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateRoleResponse"
          description: ""
        "400":
          content:
            application/json: {}
          description: Bad Request
        "401":
          content:
            application/json: {}
          description: Unauthorized request
        "404":
          content:
            application/json: {}
          description: Role not found
        "500":
          content:
            application/json: {}
          description: Internal server error
      summary: Update Role
      tags:
      - Role Management Service
  /aaa/system-roles/v1:
    get:
      description: Returns all built-in system roles.
      externalDocs:
        url: ""
      operationId: RoleManagementService_ListSystemRoles
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListSystemRolesResponse"
          description: ""
        "400":
          content:
            application/json: {}
          description: Bad Request
        "401":
          content:
            application/json: {}
          description: Unauthorized request
        "500":
          content:
            application/json: {}
          description: Internal server error
      summary: List System Roles
      tags:
      - Role Management Service
components:
  schemas:
    CreateRoleRequestParentRoleId:
      description: Request for creating a custom role.
      externalDocs:
        url: ""
      properties:
        description:
          description: Human-readable description.
          type: string
        name:
          description: Display name.
          type: string
        parentRoleId:
          description: The parent role id.
          format: int64
          type: integer
        permissions:
          description: List of permissions.
          items:
            description: List of permissions.
            type: string
          type: array
        teamId:
          description: Team identifier.
          format: int64
          type: integer
      required:
      - parentRoleId
      type: object
    CreateRoleRequestParentRoleName:
      description: Request for creating a custom role.
      externalDocs:
        url: ""
      properties:
        description:
          description: Human-readable description.
          type: string
        name:
          description: Display name.
          type: string
        parentRoleName:
          description: The parent role name.
          type: string
        permissions:
          description: List of permissions.
          items:
            description: List of permissions.
            type: string
          type: array
        teamId:
          description: Team identifier.
          format: int64
          type: integer
      required:
      - parentRoleName
      type: object
    CreateRoleResponse:
      description: Response returned after successfully creating a custom role.
      example:
        id: 0
      externalDocs:
        url: ""
      properties:
        id:
          description: Unique identifier.
          format: int64
          type: integer
      type: object
    CustomRole:
      description: Custom role.
      example:
        parentRoleName: parentRoleName
        permissions:
        - permissions
        - permissions
        roleId: 6
        teamId: 1
        name: name
        description: description
        parentRoleId: 0
      externalDocs:
        url: ""
      properties:
        description:
          description: Human-readable description.
          type: string
        name:
          description: Display name.
          type: string
        parentRoleId:
          description: The parent role id.
          format: int64
          type: integer
        parentRoleName:
          description: The parent role name.
          type: string
        permissions:
          description: List of permissions.
          items:
            description: List of permissions.
            type: string
          type: array
        roleId:
          description: The role id.
          format: int64
          type: integer
        teamId:
          description: Team identifier.
          format: int64
          type: integer
      type: object
    DeleteRoleResponse:
      additionalProperties: false
      description: Response returned after successfully deleting a custom role.
      externalDocs:
        url: ""
      type: object
    FilterPathAndValues:
      oneOf:
      - $ref: "#/components/schemas/FilterPathAndValuesFilters"
      - $ref: "#/components/schemas/FilterPathAndValuesMultipleValues"
    FilterPathAndValuesFilters:
      description: This data structure represents a filter path and values
      externalDocs:
        url: ""
      properties:
        filters:
          $ref: "#/components/schemas/Filters"
        path:
          example: test
          type: string
      required:
      - filters
      - path
      - values
      title: FilterPathAndValues
      type: object
    FilterPathAndValuesMultipleValues:
      description: This data structure represents a filter path and values
      externalDocs:
        url: ""
      properties:
        multipleValues:
          $ref: "#/components/schemas/MultipleValues"
        path:
          example: test
          type: string
      required:
      - multipleValues
      - path
      - values
      title: FilterPathAndValues
      type: object
    Filters:
      description: This data structure represents a filter
      externalDocs:
        url: ""
      properties:
        operator:
          $ref: "#/components/schemas/v3.FilterOperator"
        pathAndValues:
          items:
            $ref: "#/components/schemas/FilterPathAndValues"
          type: array
      required:
      - pathAndValues
      title: Filters
      type: object
    GetCustomRoleResponse:
      description: Response containing the details of a custom role.
      example:
        role:
          parentRoleName: parentRoleName
          permissions:
          - permissions
          - permissions
          roleId: 6
          teamId: 1
          name: name
          description: description
          parentRoleId: 0
      externalDocs:
        url: ""
      properties:
        role:
          $ref: "#/components/schemas/CustomRole"
      type: object
    ListCustomRolesResponse:
      description: Response containing a list of custom roles.
      example:
        roles:
        - parentRoleName: parentRoleName
          permissions:
          - permissions
          - permissions
          roleId: 6
          teamId: 1
          name: name
          description: description
          parentRoleId: 0
        - parentRoleName: parentRoleName
          permissions:
          - permissions
          - permissions
          roleId: 6
          teamId: 1
          name: name
          description: description
          parentRoleId: 0
      externalDocs:
        url: ""
      properties:
        roles:
          description: List of roles.
          items:
            $ref: "#/components/schemas/CustomRole"
          type: array
      type: object
    ListSystemRolesResponse:
      description: Response containing a list of system roles.
      example:
        roles:
        - permissions:
          - permissions
          - permissions
          roleId: 0
          name: name
          description: description
        - permissions:
          - permissions
          - permissions
          roleId: 0
          name: name
          description: description
      externalDocs:
        url: ""
      properties:
        roles:
          description: List of roles.
          items:
            $ref: "#/components/schemas/SystemRole"
          type: array
      type: object
    MultipleValues:
      properties:
        matcher:
          $ref: "#/components/schemas/events.v3.FilterMatcher"
        values:
          items:
            type: string
          type: array
      type: object
    SystemRole:
      example:
        permissions:
        - permissions
        - permissions
        roleId: 0
        name: name
        description: description
      properties:
        description:
          description: Human-readable description.
          type: string
        name:
          description: Display name.
          type: string
        permissions:
          description: List of permissions.
          items:
            description: List of permissions.
            type: string
          type: array
        roleId:
          description: The role id.
          format: int64
          type: integer
      type: object
    UpdateRoleResponse:
      additionalProperties: false
      description: Response returned after successfully updating a custom role.
      externalDocs:
        url: ""
      type: object
    events.v3.FilterMatcher:
      enum:
      - FILTER_MATCHER_TEXT_OR_UNSPECIFIED
      - FILTER_MATCHER_REGEXP
      type: string
    v2.Permissions:
      description: Permissions.
      externalDocs:
        url: ""
      properties:
        permissions:
          description: List of permissions.
          items:
            description: List of permissions.
            type: string
          type: array
      type: object
    v3.FilterOperator:
      description: Filter operator.
      enum:
      - FILTER_OPERATOR_AND_OR_UNSPECIFIED
      - FILTER_OPERATOR_OR
      type: string
    RoleManagementService_CreateRole_request:
      oneOf:
      - $ref: "#/components/schemas/CreateRoleRequestParentRoleId"
      - $ref: "#/components/schemas/CreateRoleRequestParentRoleName"
      type: object
    RoleManagementService_UpdateRole_request:
      description: Request for updating a custom role.
      properties:
        newDescription:
          description: The new description.
          type: string
        newName:
          description: The new name.
          type: string
        newPermissions:
          $ref: "#/components/schemas/v2.Permissions"
      type: object
