# In coralogix-management-sdk repository
name: "Notify OpenAPI Facade of New Tag and Create Release Branch when LTS"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  notify-openapi-facade:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_READER_TOKEN }}
          repository: coralogix/openapi-facade
          event-type: sdk-tag-created
          client-payload: '{"tag": "${{ github.ref_name }}"}'

      - name: Create Release Branch
        run: |
          git config --global user.email "github@coralogix.com"
          git config --global user.name "Github Actions"
          cargo run --bin create_release_branch -- -r ../..
        working-directory: tools/release-management
        env:
          GITHUB_REF: ${{ github.ref_name }}
