name: Docs
on:
  push:
    branches: [IAC-87-II]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: false
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: rust
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install Protoc # This is required for build.rs
        uses: arduino/setup-protoc@v3
        with:
          version: "26.1"
      - name: Configure cache
        uses: Swatinem/rust-cache@v2
      - name: Setup pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Clean docs folder
        run: cargo clean --doc
      - name: Build docs
        run: cargo doc --no-deps --target-dir=$RUNNER_TEMP
      - name: Add redirect
        run: echo '<meta http-equiv="refresh" content="0;url=aoc/index.html">' > $RUNNER_TEMP/doc/index.html
      - name: Remove lock file
        run: rm $RUNNER_TEMP/doc/.lock
      - name: Tar docs
        run: tar cfz $RUNNER_TEMP/doc.tgz $RUNNER_TEMP/doc
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: $RUNNER_TEMP/doc.tgz
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4