name: Go SDK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  lints:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
    - name: Formatting check
      run: gofmt -l .
    - uses: golangci/golangci-lint-action@v2
    - name: test
      run: go test -v -cover ./...