name: Go SDK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '^1.13.1' # The Go version to download (if necessary) and use.
    - run: go build sdk.go