name: Rust SDK

on:
  push:
    branches: [ master ]
    paths:
      - "rust/**"
      - "proto/**"
  pull_request:
    branches: [ master ]
    paths:
      - "./rust"
      - "./proto"

env:
  CARGO_TERM_COLOR: always

jobs:
  FLT:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "26.1"

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Cargo test
        run: cargo nextest run --all
      
      - name: Cargo run examples
        env:
          TEAM_ID: ${{ secrets.TEAM_ID }}
          AWS_TEST_ROLE: ${{ secrets.AWS_TEST_ROLE }}
          CORALOGIX_ALERTS_RULES_TAGS_API_KEY: ${{ secrets.CORALOGIX_ALERTS_RULES_TAGS_API_KEY }}
          CORALOGIX_API_KEY: ${{ secrets.CORALOGIX_API_KEY }} 
          CORALOGIX_REGION: ${{ secrets.CORALOGIX_REGION }} 
        run: cargo nextest run --all
        working-directory: rust/examples

