name: Rust
on: [pull_request]
env:
  CARGO_TERM_COLOR: always

jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all -- --check
