name: "[Rust] Publish"

permissions:
  pull-requests: write
  contents: write
  actions: write

on:
  workflow_dispatch:

env:
  PROTOC_VERSION: "29.3"

  
jobs:
  crates_io_publish:
    name: "[Rust] Publish to crates.io"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - uses: arduino/setup-protoc@v3
        with:
          version: ${{env.PROTOC_VERSION}}
      - name: "cargo workspace publish"
        run:  | 
          cargo check
          cargo install cargo-workspaces
          cargo workspaces publish --allow-dirty --no-individual-tags  --from-git --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        