name: "[Rust & Go SDK] Tag and Publish"

permissions:
  pull-requests: write
  contents: write
  actions: write

on:
  workflow_dispatch:

env:
  PROTOC_VERSION: "26.1"

  
jobs:
  crates_io_publish:
    name: "[Rust & Go SDK] Tag and Publish to crates.io"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
      - uses: arduino/setup-protoc@v3
        with:
          version: ${{env.PROTOC_VERSION}}
      - name: Copy proto files
        working-directory: ${{ github.workspace }}
        run: |
          echo "Copying proto files from $(pwd)/proto to $(pwd)/rust/cx-api/proto"
          mkdir -p rust/cx-api/proto
          cp -r proto/* rust/cx-api/proto/
      - name: "cargo workspace publish"
        run:  | 
          cargo install cargo-workspaces
          cargo workspaces publish --no-individual-tags  --from-git --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
