name: "[Protofetch] Check Tags"

# permissions:
#   pull-requests: write
#   contents: write

on:
  workflow_dispatch:
  schedule:
      - cron: "0 8 * * *"

jobs:
  checktags:
    name: "[Protofetch] Update tags to latest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}
      - name: Run protofetch tags updater
        run: |
          git config --global user.email "github@coralogix.com"
          git config --global user.name "Github Actions"
          cargo run --bin protofetch_tags_updater  -- -r ../.. -o ${{ github.repository }} -s
        working-directory: tools/release-management
        env:
          GITHUB_TOKEN: ${{ secrets.GH_READER_TOKEN }}
          GH_READER_TOKEN: ${{ secrets.GH_READER_TOKEN }}
          RUST_LOG: debug
