name: "[Protofetch] Check Tags"

permissions:
  pull-requests: write
  contents: write

on:
  pull_request:
    branches: [ IAC-152 ]
    # schedule:
    #     - cron: "0 8 * * *"

  
jobs:
  check_tags:
    name: "[Protofetch] Update tags to latest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Run tools/release-checker
        run: cd tools/release-checker && cargo run 
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}